### DISCUSSION TITLE
Extracting embedded JSON objects with rogue elements

### DISCUSSION THREAD

**Discussion by forthrin** [sparklemotion/nokogiri#2805] [General Q&A] [answered]
**What problem are you trying to solve?**

Does -- or could -- Nokogiri have a built-in way of extracting inline JSON objects in HTML, including handling of rogue elements that appear in the wild? (`undefined` and `function` are  the only ones I've encountered at least.)

Fixing `undefined` is easy, but inline functions can be large and complex, and thus unfeasible to distinguish from the surrounding JSON with regular expressions. I haven't seen an out-of-the-box solution for this anywhere so far.

**Please show your code!**

```
doc='<script>foo={"a": 1, "b": undefined, "c": function(){}};</script><script>bar={"baz": 2};</script>'
Nokogiri.HTML5(doc).css('script').each do |item|
  next unless (match = item.text.match(/foo=(?<json>.*?);/))

  clean = match['json'].gsub(/\bundefined\b/, 'null').gsub(/function\(\)\{\}/, 'null')
  puts json = JSON.parse(clean)
end
```

Would be nice to be able to do someting like this do get the JSON object:

```
json = Nokogiri.HTML5(doc).css('script').json('foo')
```

**Environment**

```
 nokogiri:
      version: 1.14.1
      platform: arm64-darwin22
      description: ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin22]
```
