### DISCUSSION TITLE
using XML::Builder to build a `doc` node

### DISCUSSION THREAD

**Discussion by stoivo** [sparklemotion/nokogiri#3065] [General Q&A] [answered]
**Please describe the bug**

I am working with xsd and I need to build a xml with the node "doc". Using the nokogiri builder I was  expecting to use   `xml.doc() { ... }` but it don't work. This uses method missing which has a name collision. I have added a demo script below. I couldn't find any solutions to this from the docs so I peeked into the source and  make myself a little patch. I changed method missing to call add_node and added new public method add_node
```rb
    def method_missing(method, *args, &block) # :nodoc:
        if @context&.respond_to?(method)
          @context.send(method, *args, &block)
        else
          add_node(method.to_s.sub(/[_!]$/, ""), *args, &block)
        end
      end

      def add_node(name, *args, &block)
        node = @doc.create_element(name, *args) do |n|
          # Set up the namespace
          if @ns.is_a?(Nokogiri::XML::Namespace)
            n.namespace = @ns
            @ns = nil
          end
        end

        if @ns.is_a?(Hash)
          node.namespace = node.namespace_definitions.find { |x| x.prefix == @ns[:pending] }
          if node.namespace.nil?
            raise ArgumentError, "Namespace #{@ns[:pending]} has not been defined"
          end

          @ns = nil
        end

        insert(node, &block)
      end
```

If this is a patch you want included I would very much like to open the PR and contribute to nokogiri.

**Help us reproduce what you're seeing**

I did't write it as a test but I have a script to demo it. 

```ruby
# frozen_string_literal: true

require "nokogiri"

XSD = <<~XSD
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="theDoc" type="Amount"/>
  <xsd:complexType name="Amount">
    <xsd:sequence>
      <xsd:element name="doc" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
XSD

class Scribe
  def self.write_xml(root)
    new.write_xml(root)
  end

  def write_xml(root)
    builder = Nokogiri::XML::Builder.new(encoding: "UTF-8") do |xml|
      build_xsd__root(xml, root)
    end
    builder.to_xml(save_with: Nokogiri::XML::Node::SaveOptions::DEFAULT_XML)
  end

  private

  attr_reader(:xml)

  def build_xsd__root(xml, root)
    # avoid passing the xml builder instance
    @xml = xml
    xml.theDoc() {
      build_amount(root[:theDoc])
    }

    @xml = nil
  end

  def build_xsd_string(str)
    xml.text(str)
  end

  def build_amount(value)
    node = xml.doc.create_element("doc")
    xml.add_node("doc") do
      build_xsd_string(value[:doc] + "new_code")
    end
    xml.doc() {
      build_xsd_string(value[:doc] + "old_code")
    }

    xml.add_node("doco") do
      build_xsd_string(value[:doc] + "new_code")
    end
    xml.doco() {
      build_xsd_string(value[:doc] + "old_code")
    }
  end
end

xml = <<~XML
  <?xml version="1.0" encoding="UTF-8"?>
  <theDoc>
    <doc>info</doc>
  </theDoc>
XML
doc = Nokogiri::XML(xml)
xsd = Nokogiri::XML::Schema(XSD)
pp({doc_errors: doc.errors, xsd_errors: xsd.validate(doc)})


root = {theDoc: {doc: "info"}}

scribed = Scribe.write_xml(root)

puts "====== scribed"
puts scribed
puts "====== xml"
puts xml


# > output
# {:doc_errors=>[], :xsd_errors=>[]}
# ====== scribed
# <?xml version="1.0" encoding="UTF-8"?>
# <theDoc>
#   <doc>infonew_code</doc>
#   <doco>infonew_code</doco>
#   <doco>infoold_code</doco>
# </theDoc>
# ====== xml
# <?xml version="1.0" encoding="UTF-8"?>
# <theDoc>
#   <doc>info</doc>
# </theDoc>
# [Finished in 1.4s]
```

If you haven't included a test, please provide whatever code you can, the inputs (if any), along with the output that you're seeing. We need to reproduce what you're seeing to be able to help!
-->

**Expected behavior**

**Environment**

<!--
```
# Nokogiri (1.15.4)
    ---
    warnings: []
    nokogiri:
      version: 1.15.4
      cppflags:
      - "-I/Users/simon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.4-arm64-darwin/ext/nokogiri"
      - "-I/Users/simon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.4-arm64-darwin/ext/nokogiri/include"
      - "-I/Users/simon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.4-arm64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.2.2
      platform: arm64-darwin22
      gem_platform: arm64-darwin-22
      description: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-update-config.guess-and-config.sub-for-libxml2.patch
      - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch
      libxml2_path: "/Users/simon/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.4-arm64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.11.5
      loaded: 2.11.5
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-config.guess-and-config.sub-for-libxslt.patch
      datetime_enabled: true
      compiled: 1.1.38
      loaded: 1.1.38
    other_libraries:
      zlib: 1.2.13
      libiconv: '1.17'
      libgumbo: 1.0.0-nokogiri
```
**Additional context**
