### DISCUSSION TITLE
RFC: drop native (precompiled) support for out-of-fashion 32-bit architectures

### DISCUSSION THREAD

**Discussion by flavorjones** [sparklemotion/nokogiri#3081] [RFCs]
## Proposal

No longer ship native (precompiled) gems for `x86-mingw32` or `x86-linux` platforms in the next Nokogiri minor release (v1.17.x).

## Rationale

The architectures `x86-mingw32` and `x86-linux` each account for less than 0.01% of recent Nokogiri gem downloads. Some concrete download stats by version and architecture:

```yaml
- v1.3 / 2009-05-30:
  - x86-mingw32:         14,993 (11.50%)
- v1.4 / 2009-10-30:
  - x86-mingw32:        143,688 ( 3.82%)
- v1.5 / 2011-07-01:
  - x86-mingw32:      1,011,724 ( 3.99%)
- v1.6 / 2013-06-08:
  - x86-mingw32:      1,742,592 ( 1.49%)
- v1.7 / 2016-12-27:
  - x86-mingw32:        359,806 ( 2.13%)
- v1.8 / 2017-06-05:
  - x86-mingw32:        289,195 ( 0.32%)
- v1.9 / 2018-12-17:
  - x86-mingw32:         56,064 ( 0.77%)
- v1.10 / 2019-01-04:
  - x86-mingw32:        222,421 ( 0.15%)
- v1.11 / 2021-01-04:
  - x86-mingw32:         24,204 ( 0.03%)
  - x86-linux:           19,737 ( 0.03%)
- v1.12 / 2021-08-02:
  - x86-mingw32:         13,598 ( 0.03%)
  - x86-linux:           11,607 ( 0.02%)
- v1.13 / 2022-01-06:
  - x86-mingw32:         17,675 ( 0.02%)
  - x86-linux:           11,919 ( 0.01%)
- v1.14 / 2023-01-12:
  - x86-mingw32:          5,237 ( 0.01%)
  - x86-linux:            4,064 ( 0.01%)
- v1.15 / 2023-05-15:
  - x86-mingw32:          6,755 ( 0.01%)
  - x86-linux:            3,170 ( 0.01%)
```

These numbers are low enough that they might only be mirrors and bots downloading them.

I'm proposing dropping native (precompiled) support for them both in Nokogiri v1.17.0 which will ship sometime in 2024. Would love to hear reasons for and against.
