### DISCUSSION TITLE
Parsing XSLT 2.0 and 3.0 files

### DISCUSSION THREAD

**Discussion by frantisekrokusek** [sparklemotion/nokogiri#3320] [General Q&A] [answered]
**What problem are you trying to solve?**
We are trying to validate .xml files with 2.0 XSLT schemas.
Here are the schemas in question.
https://github.com/ConnectingEurope/eInvoicing-EN16931/blob/master/cii/xslt/EN16931-CII-validation.xslt

From what I understand is that nokogiri is compiled with libxml2 and libxslt that can only handle version 1 XSLTs ?

Is there a possibility to be able to parse also 2.0 and 3.0 versions ?

**Please show your code!**

Here is the code to reproduce.

```ruby
#! /usr/bin/env ruby

require 'nokogiri'

Nokogiri::XSLT.parse(File.read("/Users/frantisekrokusek/Downloads/EN16931-CII-validation.xslt"))
# fails with error
# RuntimeError: compilation error: element stylesheet
# xsl:version: only 1.1 features are supported
# and more lines
```

**Environment**

```
# Nokogiri (1.16.7)
    ---
    warnings: []
    nokogiri:
      version: 1.16.7
      cppflags:
      - "-I/Users/frantisekrokusek/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.7-arm64-darwin/ext/nokogiri"
      - "-I/Users/frantisekrokusek/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.7-arm64-darwin/ext/nokogiri/include"
      - "-I/Users/frantisekrokusek/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.7-arm64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.3.4
      platform: arm64-darwin23
      gem_platform: arm64-darwin-23
      description: ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-update-config.guess-and-config.sub-for-libxml2.patch
      - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.12.9
      loaded: 2.12.9
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-config.guess-and-config.sub-for-libxslt.patch
      datetime_enabled: true
      compiled: 1.1.39
      loaded: 1.1.39
    other_libraries:
      zlib: 1.3.1
      libiconv: '1.17'
      libgumbo: 1.0.0-nokogiri
```

Thank you very much for your help 🙏
