### ISSUE TITLE
Segfault when using nokogiri under vim

### ISSUE THREAD

**Issue by RunsFor** [sparklemotion/nokogiri#1013]
Hi, 

I got this error, when running rspec command inside vim (`:!rspec`). But when I run it as usual from command line, it works fine.
Here is my ruby version:

```
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin13.0.0]
```

And nokogiri version:

```
⇒ nokogiri -v
# Nokogiri (1.6.0)
    ---
    warnings: []
    nokogiri: 1.6.0
    ruby:
      version: 2.0.0
      platform: x86_64-darwin13.0.0
      description: ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin13.0.0]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: /Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/nokogiri-1.6.0/ports/x86_64-apple-darwin13.0.0/libxml2/2.8.0
      libxslt_path: /Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/nokogiri-1.6.0/ports/x86_64-apple-darwin13.0.0/libxslt/1.1.26
      compiled: 2.8.0
      loaded: 2.8.0
```

Full backtrace is [here](https://gist.github.com/RunsFor/ba6324629c57c4b7a385)

```
/Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/nokogiri-1.6.0/lib/nokogiri/nokogiri.bundle: [BUG] Segmentation fault
ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0017 p:-17574944427400 s:0056 e:000055 TOP    [FINISH]
c:0016 p:---- s:0054 e:000053 CFUNC  :require
c:0015 p:0186 s:0050 e:000049 TOP    /Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/nokogiri-1.6.0/lib/nokogiri.rb:28 [FINISH]
c:0014 p:---- s:0048 e:000047 CFUNC  :require
c:0013 p:0007 s:0044 e:000043 TOP    /Users/runfor/Projects/telepresence_api/lib/telepresence_api.rb:1 [FINISH]
c:0012 p:---- s:0042 e:000041 CFUNC  :require_relative
c:0011 p:0007 s:0038 e:000037 TOP    /Users/runfor/Projects/telepresence_api/spec/spec_helper.rb:1 [FINISH]
c:0010 p:---- s:0036 e:000035 CFUNC  :require
c:0009 p:0007 s:0032 e:000031 TOP    /Users/runfor/Projects/telepresence_api/spec/telepresence_api/conference_spec.rb:1 [FINISH]
c:0008 p:---- s:0030 e:000029 CFUNC  :load
c:0007 p:0018 s:0026 e:000025 BLOCK  /Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896 [FINISH]
c:0006 p:---- s:0023 e:000022 CFUNC  :each
c:0005 p:0011 s:0020 e:000019 METHOD /Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896
c:0004 p:0054 s:0017 e:000016 METHOD /Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:22
c:0003 p:0101 s:0012 e:000011 METHOD /Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:80
c:0002 p:0044 s:0005 e:000004 BLOCK  /Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:17 [FINISH]
c:0001 p:0000 s:0002 E:000208 TOP    [FINISH]

/Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:17:in `block in autorun'
/Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:80:in `run'
/Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:22:in `run'
/Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `load_spec_files'
/Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `each'
/Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
/Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `load'
/Users/runfor/Projects/telepresence_api/spec/telepresence_api/conference_spec.rb:1:in `<top (required)>'
/Users/runfor/Projects/telepresence_api/spec/telepresence_api/conference_spec.rb:1:in `require'
/Users/runfor/Projects/telepresence_api/spec/spec_helper.rb:1:in `<top (required)>'
/Users/runfor/Projects/telepresence_api/spec/spec_helper.rb:1:in `require_relative'
/Users/runfor/Projects/telepresence_api/lib/telepresence_api.rb:1:in `<top (required)>'
/Users/runfor/Projects/telepresence_api/lib/telepresence_api.rb:1:in `require'
/Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/nokogiri-1.6.0/lib/nokogiri.rb:28:in `<top (required)>'
/Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/gems/nokogiri-1.6.0/lib/nokogiri.rb:28:in `require'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------

* Loaded script: /Users/runfor/.rvm/gems/ruby-2.0.0-p247@telepresence/bin/rspec

* Loaded features:

    0 enumerator.so
    1 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/enc/encdb.bundle
    2 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/enc/trans/transdb.bundle
    3 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13/rbconfig.rb
    4 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/compatibility.rb
    5 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/defaults.rb
    6 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/deprecate.rb
    7 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/errors.rb
    8 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb
    9 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/requirement.rb
```
