### ISSUE TITLE
Nokogiri 1.6 Segmentation Fault with irb under verbose and debug flags.

### ISSUE THREAD

**Issue by empjustine** [sparklemotion/nokogiri#1037]
Minimal steps
$ bundle exec irb
```ruby
$VERBOSE = true
$DEBUG = true

require 'nokogiri'

Nokogiri::HTML::parse ''
# segmentation fault or SystemStackError
# often both.
```
Machine 1
Ubuntu Linux 12.04 with RVM
$ bundle exec nokogiri -v 
```
# Nokogiri (1.6.0)
    ---
    warnings: []
    nokogiri: 1.6.0
    ruby:
      version: 1.9.3
      platform: x86_64-linux
      description: ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: /home/ubuntu/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.0/ports/x86_64-linux-gnu/libxml2/2.8.0
      libxslt_path: /home/ubuntu/.rvm/gems/ruby-1.9.3-p484/gems/nokogiri-1.6.0/ports/x86_64-linux-gnu/libxslt/1.1.26
      compiled: 2.8.0
      loaded: 2.8.0
```
Machine 2
Arch Linux with anyenv/rbenv
$ bundle exec ruby nokogiri -v 
```
# Nokogiri (1.6.1)
    ---
    warnings: []
    nokogiri: 1.6.1
    ruby:
      version: 1.9.2
      platform: x86_64-linux
      description: ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: system
      compiled: 2.9.1
      loaded: 2.9.1
```
