### ISSUE TITLE
Nokogiri::XML::SyntaxError when parsing DocumentFragments

### ISSUE THREAD

**Issue by LindseyB** [sparklemotion/nokogiri#1105]
I've been inexplicably getting various Nokogiri::XML::SyntaxErrors when trying to parse document fragments for example:

```
"XML declaration allowed only at the start of the document (Nokogiri::XML::SyntaxError)"
```

The line in question is:

```
html = Nokogiri::HTML::DocumentFragment.parse(body)
```

for where `body` looks like (copying and pasting the string output and I apologize for how big this is):

`
"<h4>Participating in the Weekly E-Learning Challenge</h4>\n<p>This week I thought it would be fun to participate in the Weekly E-Learning Challenge, &quot;hosted&quot; by Articulate Community Manager David Anderson on a weekly basis. The weekly e-learning challenge is an awesome way for e-learning designers to get their creative gears going and come up with the fun projects they don&#39;t typically get asked to do at work. It&#39;s a great way to get experience, try new things, and create cool sample projects to show off in your portfolio. </p>\n<p>&nbsp;</p>\n<p>I really like this week&#39;s topic (<a target=\"_blank\" href=\"http://community.articulate.com/blogs/david/archive/2013/10/11/weekly-e-learning-challenge-converting-static-content-to-interactive.aspx\">Converting Static Content into Interactive Knowledge Checks</a>), which is all about turning static (read: boring) content into more fun and engaging content, simply by using a freeform interaction or something similar. You can turn your content into a pick-one, pick-many, drag and drop, etc. Those are just a few of the options available to you.&nbsp;</p>\n<p>&nbsp;</p>\n<h4>Using Articulate Quizmaker &#39;13</h4>\n<p><span style=\"font-size:12px;line-height:1.5;\">I decided to do this week&#39;s challenge using the awesome new Quizmaker &#39;13. It (like Storyline) offers the super powerful feature of creating freeform slides. Basically it allows you to very easily and painlessly turn any objects, text or images on a slide into interactive quiz objects. In this case, I had a simple content slide that I had built in Powerpoint for a WiFi e-learning project I&#39;m working on. </span></p>\n<p>&nbsp;</p>\n<p><span style=\"font-size:12px;line-height:1.5;\">In my Presenter project, I simply created a new Freeform &quot;pick one&quot; slide in Quizmaker &#39;13 and copy/pasted over the elements from my Powerpoint slide. I then just used the easy form to select my options and correct choice for the quiz. I took a few moments to format my feedback slides and the Results slide, and voila! In about 5 minutes, I&#39;ve created an interactive knowledge check from some basic, static content.&nbsp;</span></p>\n<p>&nbsp;</p>\n<p>Check out the published version: <a href=\"http://artco-temp.s3.amazonaws.com/Nicole/WeeklyChallenge1/presentation.html\" target=\"_blank\">Converting Static Content into an Interactive Knowledge Check - Before and After</a></p>\n<p>&nbsp;</p>\n<h4>Before: Static Content Slide</h4>\n<p>&nbsp;</p>\n<p><span style=\"font-size:12px;line-height:1.5;\"><a href=\"http://community.articulate.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/nicole/1_5F00_img1.png\"><img src=\"http://community.articulate.com/resized-image.ashx/__size/550x0/__key/CommunityServer.Blogs.Components.WeblogFiles/nicole/1_5F00_img1.png\" border=\"0\" alt=\"\" /></a><br /></span></p>\n<h4>After: Interactive Knowledge Check</h4>\n<p>&nbsp;</p>\n<p><a href=\"http://community.articulate.com/cfs-file.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/nicole/1_5F00_img2.png\"><img src=\"http://community.articulate.com/resized-image.ashx/__size/550x0/__key/CommunityServer.Blogs.Components.WeblogFiles/nicole/1_5F00_img2.png\" border=\"0\" alt=\"\" /></a></p>\n<p>&nbsp;</p>\n<p>As you can see, I use basically the same elements on each slide, except in one case it&#39;s a boring, read-only slide. In the second case, it&#39;s a more engaging and thought-provoking knowledge check. It presents similar information but in a way that makes the learner think critically!</p>\n<p>&nbsp;</p>\n<p>Hope you guys like this example, and hope you&#39;ll also take part in this week&#39;s e-learning challenge, as well as the future ones to come! Also, if you&#39;re&nbsp;<span>interesting in getting more e-learning tips, you can&nbsp;</span><a href=\"https://twitter.com/Articulate\">follow us on Twitter</a><span>.</span></p>"
`

my Nokogiri -v output is as follows:

```
# Nokogiri (1.6.2.1)
    ---
    warnings: []
    nokogiri: 1.6.2.1
    ruby:
      version: 2.1.1
      platform: x86_64-darwin13.0
      description: ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin13.0]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.2.1/ports/x86_64-apple-darwin13.1.0/libxml2/2.8.0"
      libxslt_path: "/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.2.1/ports/x86_64-apple-darwin13.1.0/libxslt/1.1.28"
      compiled: 2.8.0
      loaded: 2.8.0
```
