### ISSUE TITLE
Unable to disable '&' to '&amp;' escaping

### ISSUE THREAD

**Issue by ryansch** [sparklemotion/nokogiri#1127]
I have an html document that contains a link of the form:
`http://domain.com/path?foo=bar&dead=beef`

If I parse it and emit it back out via `to_html` I get the following:
`http://domain.com/path?foo=bar&amp;dead=beef`

This breaks the link's functionality and appears to only have the `foo` get param.  How do I get `#to_html` or `#serialize` to behave?
#### Example

``` ruby
doc = %q{<a href="http://domain.com/path?foo=bar&dead=beef">Clicky</a>}
message = Nokogiri::HTML.parse(doc)
message.to_html
```
#### Result

``` ruby
"<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\" \"http://www.w3.org/TR/REC-html40/loose.dtd\">\n<html><body><a href=\"http://domain.com/path?foo=bar&amp;dead=beef\">Clicky</a></body></html>\n"
```

**Comment by nolman** [comment]
So I believe the root cause of this bug is an incompatibility between xml and html and that nokogiri uses libxml2 to build html documents.

[XML does not permit lone &'s](http://www.w3.org/TR/REC-xml/#syntax) instead they must be encoded as ```&amp;```. The code that is converting & to ```&amp;``` is in libxml2:

```
void
xmlBufAttrSerializeTxtContent(xmlBufPtr buf, xmlDocPtr doc,
                              xmlAttrPtr attr, const xmlChar * string)
{   xmlChar *base, *cur;

    if (string == NULL)
        return;
    base = cur = (xmlChar *) string;
    while (*cur != 0) {
 ....
        } else if (*cur == '&') {
            if (base != cur)
                xmlBufAdd(buf, base, cur - base);
            xmlBufAdd(buf, BAD_CAST "&amp;", 5);
            cur++;
            base = cur;
```

**Comment by ryansch** [comment]
Nice find.  I didn't end up having enough time to dig through libxml2.  I was able to work around this bug in our app in a different way.

**Comment by nolman** [comment]
What did you end up doing?

**Comment by ryansch** [comment]
We were able to limit our url generation so that each url only had one get param.  It's not a widely applicable solution.  :frowning:

**Comment by khoan** [comment]
CGI.unescape_html

**Comment by nolman** [comment]
Parsing/substituting HTML via regex is [generally a bad idea](http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags?page=2&tab=votes#tab-top). If one controls the URL and can avoiding multiple query params that is probably a better work around for now $0.02

**Comment by fabn** [comment]
Is there any other workaround not involving regex for this issue?

**Comment by gingerlime** [comment]
Sorry for posting a "me too", but I also bumped into this and find it odd. The regex workaround doesn't always work either. e.g.

```ruby
> frag = "<h2>Introduction</h2><p><img src=\"https://ab.c.com/?ab=c&mark=%2Fimages%2Fwatermark"
> Nokogiri::HTML.fragment(frag).to_html.gsub(%r{https?://[^"]+}) {|s| CGI.unescape_html(s) } == frag
=> false
```

**Comment by flavorjones** [comment]
This behavior is going to depend on what version of libxml2 you're running. With the libxml 2.9.4 that's in Nokogiri v1.7.0.1, this is properly not-escaped.

If you see this issue, please do comment here with the output from `nokogiri -v` so we can see what version of Nokogiri and libxml2 you're running.

**Comment by redjohn** [comment]
I am still having this problem with nokogiri 1.8.0:

```
# Nokogiri (1.8.0)
    ---
    warnings: []
    nokogiri: 1.8.0
    ruby:
      version: 2.3.3
      platform: x86_64-darwin16
      description: ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/mavenlink/.rvm/gems/ruby-2.3.3@mavenlink/gems/nokogiri-1.8.0/ports/x86_64-apple-darwin16.5.0/libxml2/2.9.4"
      libxslt_path: "/Users/mavenlink/.rvm/gems/ruby-2.3.3@mavenlink/gems/nokogiri-1.8.0/ports/x86_64-apple-darwin16.5.0/libxslt/1.1.29"
      libxml2_patches:
      - 0001-Fix-comparison-with-root-node-in-xmlXPathCmpNodes.patch
      - 0002-Fix-XPointer-paths-beginning-with-range-to.patch
      - 0003-Disallow-namespace-nodes-in-XPointer-ranges.patch
      libxslt_patches:
      - 0001-Fix-heap-overread-in-xsltFormatNumberConversion.patch
      - 0002-Check-for-integer-overflow-in-xsltAddTextString.patch
      compiled: 2.9.4
      loaded: 2.9.4
```
