### ISSUE TITLE
build native gem of nokogiri-1.6.2.1

### ISSUE THREAD

**Issue by geeth4sg** [sparklemotion/nokogiri#1136]
https://github.com/sparklemotion/nokogiri/issues/1129

The belows steps done for building nokogiri gem manually.

nokogiri.so file has been created on Slackware14.1, after that how to make .gem file formate.

root@ang154:~/noko/nokogiri-1.6.2.1/ext/nokogiri# ruby extconf.rb 
Building nokogiri using system libraries.
checking for xmlParseDoc() in libxml/parser.h... yes
checking for xsltParseStylesheetDoc() in libxslt/xslt.h... yes
checking for exsltFuncRegister() in libexslt/exslt.h... yes
checking for xmlHasFeature()... yes
checking for xmlFirstElementChild()... yes
checking for xmlRelaxNGSetParserStructuredErrors()... yes
checking for xmlRelaxNGSetParserStructuredErrors()... yes
checking for xmlRelaxNGSetValidStructuredErrors()... yes
checking for xmlSchemaSetValidStructuredErrors()... yes
checking for xmlSchemaSetParserStructuredErrors()... yes
creating Makefile

root@ang154:~/noko/nokogiri-1.6.2.1/ext/nokogiri# make
compiling xml_node_set.c
xml_node_set.c: In function 'dealloc_namespace':
xml_node_set.c:9:13: warning: cast discards '**attribute**((const))' qualifier from pointer target type [-Wcast-qual]
     xmlFree((xmlChar *)ns->href);
             ^
xml_node_set.c:11:13: warning: cast discards '**attribute**((const))' qualifier from pointer target type [-Wcast-qual]
     xmlFree((xmlChar *)ns->prefix);
             ^
compiling xml_xpath_context.c
compiling xml_entity_decl.c
compiling xml_text.c
compiling xml_document_fragment.c
compiling xml_entity_reference.c
compiling xml_document.c

```
                               ^
```

compiling xml_sax_parser_context.c
compiling xml_reader.c
compiling xml_sax_parser.c
compiling xml_attr.c
compiling xml_dtd.c
compiling xml_encoding_handler.c
compiling xml_comment.c
compiling xml_schema.c
compiling xml_relax_ng.c
linking shared-object nokogiri/nokogiri.so
Cleaning files only used during build.
rm -rf /root/noko/nokogiri-1.6.2.1/ports/archives

root@ang154:~/noko/nokogiri-1.6.2.1# ruby -Ilib ./bin/nokogiri -v
# Nokogiri (1.6.2.1)

```

---
warnings: []
nokogiri: 1.6.2.1
ruby:
  version: 2.1.0
  platform: x86_64-linux
  description: ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-linux]
  engine: ruby
libxml:
  binding: extension
  source: packaged
  libxml2_path: "/root/noko/nokogiri-1.6.2.1/ports/x86_64-slackware-linux-gnu/libxml2/2.8.0"
  libxslt_path: "/root/noko/nokogiri-1.6.2.1/ports/x86_64-slackware-linux-gnu/libxslt/1.1.28"
  compiled: 2.8.0
  loaded: 2.8.0
```

root@ang154:~/noko/nokogiri-1.6.2.1# rake compile --trace
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - .cross_rubies
/root/noko/nokogiri-1.6.2.1/Rakefile:93:in `read'
/root/noko/nokogiri-1.6.2.1/Rakefile:93:in`<top (required)>'
/pkg/ruby-lang.org/ruby/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_module.rb:28:in `load'
/pkg/ruby-lang.org/ruby/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_module.rb:28:in`load_rakefile'
/pkg/ruby-lang.org/ruby/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:687:in `raw_load_rakefile'
/pkg/ruby-lang.org/ruby/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:94:in`block in load_rakefile'
/pkg/ruby-lang.org/ruby/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/pkg/ruby-lang.org/ruby/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:93:in`load_rakefile'
/pkg/ruby-lang.org/ruby/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:77:in `block in run'
/pkg/ruby-lang.org/ruby/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in`standard_exception_handling'
/pkg/ruby-lang.org/ruby/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/pkg/ruby-lang.org/ruby/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.2/bin/rake:33:in`<top (required)>'
/pkg/ruby-lang.org/ruby/2.1.0/bin/rake:23:in `load'
/pkg/ruby-lang.org/ruby/2.1.0/bin/rake:23:in`<main>'
