### ISSUE TITLE
#at("table td:first-child") returns nil but #at("table tr td:first-child") returns non-nil value

### ISSUE THREAD

**Issue by jackrg** [sparklemotion/nokogiri#1171]
On the web page "http://www.amazon.com/product-reviews/B006QP63LI/ref=cm_cr_pr_top_recent?ie=UTF8&showViewpoints=0&sortBy=bySubmissionDateDescending", I get the following behavior (note that the only difference between the two is the addition of a "TR" element):

(rdb:1) page.at("table#productReviews td:first-child")
nil
(rdb:1) page.at("table#productReviews tr td:first-child")
# <Nokogiri::XML::Element:0x3fd54c58c74c name="td" ...

This behavior is at odds with what I get with the browser command: document.querySelectorAll("table#productReviews td:first-child") which gives the same results as document.querySelectorAll("table#productReviews tr td:first-child") 

A partial dump of the TR element looks like this: 
# <Nokogiri::XML::Element:0x3fd54c592908 name="tr" children=[#<Nokogiri::XML::Element:0x3fd54c58c74c name="td" ...

so it is clear that the"td" **is** a first child, although not the first-child of the "table" element. I'm wondering if somehow the definition of first-child has gotten changed to "first-child of the previously referenced element". Also, page.at("table#productReviews").at("td:first-child") returns nil but page.at("table#productReviews tr").at("td:first-child") returns the TR element.

I'm running OS X Mavericks with RBENV.  Here is the output from nokogiri -v:
# Nokogiri (1.6.1)

```

---
warnings: []
nokogiri: 1.6.1
ruby:
  version: 1.9.2
  platform: x86_64-darwin11.3.0
  description: ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin11.3.0]
  engine: ruby
libxml:
  binding: extension
  source: packaged
  libxml2_path: /Users/jackrg/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/nokogiri-1.6.1/ports/x86_64-apple-darwin13.1.0/libxml2/2.8.0
  libxslt_path: /Users/jackrg/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/nokogiri-1.6.1/ports/x86_64-apple-darwin13.1.0/libxslt/1.1.26
  compiled: 2.8.0
  loaded: 2.8.0
```

Please let me know if there is any other info you need to troubleshoot this.
