### ISSUE TITLE
Segmentation fault inspecting some entities

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1238]
Originally reported on the `nokogiri-talk` mailing list:

> https://groups.google.com/d/msg/nokogiri-talk/Kl8E_RjBf8w/0zIw9IuiBGIJ

I've rewritten the original example slightly:

``` ruby
require "nokogiri"
require "pp"

doc1 = Nokogiri::HTML('<p></p>')
doc2 = Nokogiri::HTML('<p></p>')

ent = Nokogiri::XML::EntityReference.new(doc1, "amp")

doc2.css("p").each do |pp|
  pp << ent
end
pp doc2
```

running:

``` yaml
# Nokogiri (1.6.6.2)
    ---
    warnings: []
    nokogiri: 1.6.6.2
    ruby:
      version: 2.1.5
      platform: x86_64-linux
      description: ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/miked-public/code/oss/nokogiri/ports/x86_64-unknown-linux-gnu/libxml2/2.9.2"
      libxslt_path: "/home/miked-public/code/oss/nokogiri/ports/x86_64-unknown-linux-gnu/libxslt/1.1.28"
      libxml2_patches:
      - 0001-Revert-Missing-initialization-for-the-catalog-module.patch
      - 0002-Fix-missing-entities-after-CVE-2014-3660-fix.patch
      libxslt_patches:
      - 0001-Adding-doc-update-related-to-1.1.28.patch
      - 0002-Fix-a-couple-of-places-where-f-printf-parameters-wer.patch
      - 0003-Initialize-pseudo-random-number-generator-with-curre.patch
      - 0004-EXSLT-function-str-replace-is-broken-as-is.patch
      - 0006-Fix-str-padding-to-work-with-UTF-8-strings.patch
      - 0007-Separate-function-for-predicate-matching-in-patterns.patch
      - 0008-Fix-direct-pattern-matching.patch
      - 0009-Fix-certain-patterns-with-predicates.patch
      - 0010-Fix-handling-of-UTF-8-strings-in-EXSLT-crypto-module.patch
      - 0013-Memory-leak-in-xsltCompileIdKeyPattern-error-path.patch
      - 0014-Fix-for-bug-436589.patch
      - 0015-Fix-mkdir-for-mingw.patch
      compiled: 2.9.2
      loaded: 2.9.2
```

**Comment by flavorjones** [comment]
I dug into this a little bit, it appears the the `EntityReference` is created with a single child, which is the related `EntityDecl`; and the crash is happening while trying to access that child.

I'm not sure exactly what's wrong with the entity declaration; but its `->doc` value is NULL, meaning it may not be getting parented correctly. When I force a reparent (by setting `->doc` (with or without rooting it)), I get a crash trying to format the output buffer, which indicates there may be other things wrong with that node.

In the meantime, try using `Document#create_entity` for adding entities.

**Comment by flavorjones** [comment]
Looking into this now, can still reproduce this segfault from commit 1691c0d

```
# Nokogiri (1.7.0.1)
    ---
    warnings: []
    nokogiri: 1.7.0.1
    ruby:
      version: 2.4.0
      platform: x86_64-linux
      description: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/flavorjones/code/oss/nokogiri/ports/x86_64-pc-linux-gnu/libxml2/2.9.4"
      libxslt_path: "/home/flavorjones/code/oss/nokogiri/ports/x86_64-pc-linux-gnu/libxslt/1.1.29"
      libxml2_patches:
      - 0001-Fix-comparison-with-root-node-in-xmlXPathCmpNodes.patch
      - 0002-Fix-XPointer-paths-beginning-with-range-to.patch
      - 0003-Disallow-namespace-nodes-in-XPointer-ranges.patch
      libxslt_patches:
      - 0001-Fix-heap-overread-in-xsltFormatNumberConversion.patch
      - 0002-Check-for-integer-overflow-in-xsltAddTextString.patch
      compiled: 2.9.4
      loaded: 2.9.4
```
