### ISSUE TITLE
RuntimeError when calling to_s with jruby

### ISSUE THREAD

**Issue by binaryplease** [sparklemotion/nokogiri#1281]
Hello 
using Jruby with some html tags (Nokogiri xml elements) I get this error which crashes the program
the error doesnt always occur, so it is hard to provide a sample code, but it looks like

``` ruby
doc.css('meta').each do |t|
  puts t
  a << t.to_s
end
```

I think it might have to do with invalid encodings, but it's just a guess.
Is there a woraround for this?

``` code

RuntimeError: Input length = 1
  native_write_to at nokogiri/XmlNode.java:1217
         write_to at /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:686
        serialize at /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:618
        to_format at /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:774
          to_html at /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:630
             to_s at /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node.rb:501
    get_meta_tags at /home/binaryplease/committance/crawler2/crawler/crawler.rb:147
             each at /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node_set.rb:187
             upto at org/jruby/RubyInteger.java:133
             each at /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/node_set.rb:186
    get_meta_tags at /home/binaryplease/committance/crawler2/crawler/crawler.rb:146
  fetch_page_tags at /home/binaryplease/committance/crawler2/crawler/crawler.rb:213
             each at org/jruby/RubyArray.java:1613
  fetch_page_tags at /home/binaryplease/committance/crawler2/crawler/crawler.rb:205
     get_contents at /home/binaryplease/committance/crawler2/crawler/crawler.rb:117
     process_link at /home/binaryplease/committance/crawler2/crawler/worker.rb:104
     process_link at /home/binaryplease/committance/crawler2/crawler/worker.rb:114
             each at org/jruby/RubyArray.java:1613
     process_link at /home/binaryplease/committance/crawler2/crawler/worker.rb:114
            start at /home/binaryplease/committance/crawler2/crawler/worker.rb:74
             each at org/jruby/RubyArray.java:1613
            start at /home/binaryplease/committance/crawler2/crawler/worker.rb:74
            start at /home/binaryplease/committance/crawler2/crawler/worker.rb:58
    process_batch at /home/binaryplease/committance/crawler2/crawler/crawler_client2.rb:120
             call at org/jruby/RubyProc.java:271
       initialize at /home/binaryplease/committance/crawler2/crawler/thread_pool.rb:14
             loop at org/jruby/RubyKernel.java:1507
       initialize at /home/binaryplease/committance/crawler2/crawler/thread_pool.rb:12
            catch at org/jruby/RubyKernel.java:1270
       initialize at /home/binaryplease/committance/crawler2/crawler/thread_pool.rb:11
```

**Comment by flavorjones** [comment]
Hi,

Thanks for reporting this.

Unfortunately, without more information we cannot reproduce and thus won't be able to help. Can you please provide whatever you can to help us reproduce? The XML document in question would be a great help, as would any ruby code running on the script that might crash.

We would additionally need information about your system, which you can get by running `nokogiri -v` and pasting the output here.

**Comment by binaryplease** [comment]
Hello this is the output of nokogiri -v

````
binaryplease➜~(master✗)» rvm use jruby                                                                                                                                                                                               [23:47:14]
Using /home/binaryplease/.rvm/gems/jruby-1.7.19
binaryplease➜~(master✗)» nokogiri -v                                                                                                                                                                                                 [23:47:19]
# Nokogiri (1.6.6.2)
    ---
    warnings: []
    nokogiri: 1.6.6.2
    ruby:
      version: 1.9.3
      platform: java
      description: jruby 1.7.19 (1.9.3p551) 2015-02-21 32f5af0 on OpenJDK 64-Bit Server VM 1.8.0_45-b14 +jit [linux-amd64]
      engine: jruby
      jruby: 1.7.19
    xerces: Xerces-J 2.9.0
    nekohtml: NekoHTML 1.9.12

````

Ill apped any more information about the xml in question when I have it.
Thanks.
