### ISSUE TITLE
html sax parser not fixing not closing attributes

### ISSUE THREAD

**Issue by kostya** [sparklemotion/nokogiri#1286]
1.6.6.2

```ruby
require 'bundler/setup'
require 'nokogiri'

class Doc < Nokogiri::XML::SAX::Document
  def characters(chars)
    p chars
  end
end

str = "<html>
<meta name = 'bla
<body>
body
</body>
</html>
"

parser = Nokogiri::HTML::SAX::Parser.new(Doc.new)
parser.parse_memory(str)
```
output is empty.

but if i change meta to (add '):
```ruby
<meta name = 'bla'
```

nokogiri fixed broken html tags, and output is "\nbody\n"

i think nokogiri also should fix broken html tags in first example;

**Comment by flavorjones** [comment]
Hi,

Thank for reporting this.

Can you provide the output from `nokogiri -v` so that we know what your
environment looks like?

-m

**Comment by kostya** [comment]
```
# Nokogiri (1.6.6.2)
    ---
    warnings: []
    nokogiri: 1.6.6.2
    ruby:
      version: 2.2.0
      platform: x86_64-darwin13
      description: ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/kostya/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2/ports/x86_64-apple-darwin13.0.0/libxml2/2.9.2"
      libxslt_path: "/Users/kostya/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2/ports/x86_64-apple-darwin13.0.0/libxslt/1.1.28"
      libxml2_patches:
      - 0001-Revert-Missing-initialization-for-the-catalog-module.patch
      - 0002-Fix-missing-entities-after-CVE-2014-3660-fix.patch
      libxslt_patches:
      - 0001-Adding-doc-update-related-to-1.1.28.patch
      - 0002-Fix-a-couple-of-places-where-f-printf-parameters-wer.patch
      - 0003-Initialize-pseudo-random-number-generator-with-curre.patch
      - 0004-EXSLT-function-str-replace-is-broken-as-is.patch
      - 0006-Fix-str-padding-to-work-with-UTF-8-strings.patch
      - 0007-Separate-function-for-predicate-matching-in-patterns.patch
      - 0008-Fix-direct-pattern-matching.patch
      - 0009-Fix-certain-patterns-with-predicates.patch
      - 0010-Fix-handling-of-UTF-8-strings-in-EXSLT-crypto-module.patch
      - 0013-Memory-leak-in-xsltCompileIdKeyPattern-error-path.patch
      - 0014-Fix-for-bug-436589.patch
      - 0015-Fix-mkdir-for-mingw.patch
      compiled: 2.9.2
      loaded: 2.9.2
```
