### ISSUE TITLE
Nokogiri changes HTML completely resulting in Chinese characters ( only in Linux )

### ISSUE THREAD

**Issue by fernandomm** [sparklemotion/nokogiri#1317]
I have a strange issue with Nokogiri. I'm running the same gem, ruby and libxml versions in a Linux server and in my OS X dev environment.  The only difference is that in Linux Nokogiri seems to apply some patches automatically ( see Nokogiri::VersionInfo.instance.to_markdown below ).

I have the following string:

```
2.1.0 :056 > html
 => "<meta http-equiv=Content-Type content=\"text/html; charset=unicode\">"
2.1.0 :057 > html.encoding
 => #<Encoding:ASCII-8BIT>
```

I know it's incomplete. But that's the part that causes this problem.

In OS X I get:

```
> doc = Nokogiri::HTML(html)
 => #<Nokogiri::HTML::Document:0x3fd30d1e443c name="document" children=[#<Nokogiri::XML::DTD:0x3fd30d1e4108 name="html">, #<Nokogiri::XML::Element:0x3fd30d1ede88 name="html" children=[#<Nokogiri::XML::Element:0x3fd30d1edca8 name="head" children=[#<Nokogiri::XML::Element:0x3fd30d1edac8 name="meta" attributes=[#<Nokogiri::XML::Attr:0x3fd30d1eda64 name="http-equiv" value="Content-Type">, #<Nokogiri::XML::Attr:0x3fd30d1eda50 name="content" value="text/html; charset=unicode">]>]>]>]>
```

Which is correct. But in Linux I get:

```
> doc = Nokogiri::HTML(html)
 => #<Nokogiri::HTML::Document:0x228f01c name="document" children=[#<Nokogiri::XML::DTD:0x228e3c4 name="html">, #<Nokogiri::XML::Element:0x2287ed4 name="html" children=[#<Nokogiri::XML::Element:0x22879e8 name="body" children=[#<Nokogiri::XML::Element:0x2287358 name="p" children=[#
<Nokogiri::XML::Text:0x2286ebc "洼瑥瑨灴攭畱癩䌽湯整瑮吭灹\u2065潣瑮湥㵴琢硥⽴瑨汭※档牡敳㵴湵捩摯≥">]>]>]>]>
```

Which is wrong. I don't know where these characters come from. Any ideas about what causes and how can I fix this issue?

Nokogiri::VersionInfo.instance.to_markdown output in Linux ( doesn't work ):

```
# Nokogiri (1.6.6.2)
    ---
    warnings: []
    nokogiri: 1.6.6.2
    ruby:
      version: 2.1.3
      platform: x86_64-linux
      description: ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/u/apps/app/current/vendor/bundle/ruby/2.1.0/gems/nokogiri-1.6.6.2/ports/x86_64-unknown-linux-gnu/libxml2/2.9.2"
      libxslt_path: "/u/apps/app/current/vendor/bundle/ruby/2.1.0/gems/nokogiri-1.6.6.2/ports/x86_64-unknown-linux-gnu/libxslt/1.1.28"
      libxml2_patches:
      - 0001-Revert-Missing-initialization-for-the-catalog-module.patch
      - 0002-Fix-missing-entities-after-CVE-2014-3660-fix.patch
      libxslt_patches:
      - 0001-Adding-doc-update-related-to-1.1.28.patch
      - 0002-Fix-a-couple-of-places-where-f-printf-parameters-wer.patch
      - 0003-Initialize-pseudo-random-number-generator-with-curre.patch
      - 0004-EXSLT-function-str-replace-is-broken-as-is.patch
      - 0006-Fix-str-padding-to-work-with-UTF-8-strings.patch
      - 0007-Separate-function-for-predicate-matching-in-patterns.patch
      - 0008-Fix-direct-pattern-matching.patch
      - 0009-Fix-certain-patterns-with-predicates.patch
      - 0010-Fix-handling-of-UTF-8-strings-in-EXSLT-crypto-module.patch
      - 0013-Memory-leak-in-xsltCompileIdKeyPattern-error-path.patch
      - 0014-Fix-for-bug-436589.patch
      - 0015-Fix-mkdir-for-mingw.patch
      compiled: 2.9.2
      loaded: 2.9.2
```

Nokogiri::VersionInfo.instance.to_markdown output in OS X ( works fine! ):

```
# Nokogiri (1.6.6.2)
    ---
    warnings: []
    nokogiri: 1.6.6.2
    ruby:
      version: 2.1.3
      platform: x86_64-darwin14.0
      description: ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/fernando/.rvm/gems/ruby-2.1.3/gems/nokogiri-1.6.6.2/ports/x86_64-apple-darwin14.0.0/libxml2/2.9.2"
      libxslt_path: "/Users/fernando/.rvm/gems/ruby-2.1.3/gems/nokogiri-1.6.6.2/ports/x86_64-apple-darwin14.0.0/libxslt/1.1.28"
      libxml2_patches: []
      libxslt_patches: []
      compiled: 2.9.2
      loaded: 2.9.2
```
