### ISSUE TITLE
nokogiri 1.6.8.rc3 fails to build in a fresh install of ruby 2.3 on OS X

### ISSUE THREAD

**Issue by cbowns** [sparklemotion/nokogiri#1445]
- OS X version: 10.11.3
- ruby version: `ruby 2.3` installed with `ruby-install` to `~/.rubies`, and activated with `chruby`
- nokogiri version: `1.6.8.rc3`

Build error:

```
xmlIO.c:1450:52: error: use of undeclared identifier 'LZMA_OK'
    ret =  (__libxml2_xzclose((xzFile) context) == LZMA_OK ) ? 0 : -1;
                                                   ^
1 error generated.
make[2]: *** [xmlIO.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
========================================================================
*** extconf.rb failed ***
```

Full log is attached at [gem_make.out.txt](https://github.com/sparklemotion/nokogiri/files/167752/gem_make.out.txt)

More configuration info:

I just cloned the repo which calls for `nokogiri` about an hour ago, and installed `ruby 2.3` with `ruby-install`. I then installed bundler (`gem install bundler`), then installed my repo's gems, like `nokogiri`, with `bundle install`:

```
% bundle install
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching https://github.com/dominic/jsonapi-serializers.git
Installing rake 10.5.0
Installing i18n 0.7.0
Using json 1.8.3
Installing minitest 5.8.4
Installing thread_safe 0.3.5
Installing builder 3.2.2
Installing erubis 2.7.0
Installing mini_portile2 2.1.0
Installing pkg-config 1.1.7
Installing rack 1.6.4
Installing mime-types 2.99
Installing arel 6.0.3
Installing unf_ext 0.0.7.1 with native extensions
Installing netrc 0.11.0
Installing rspec-support 3.4.1
Installing diff-lcs 1.2.5
Installing encryptor 1.3.0
Installing bcrypt 3.1.10 with native extensions
Installing debug_inspector 0.0.2 with native extensions
Installing uniform_notifier 1.9.0
Installing byebug 8.2.1 with native extensions
Installing coderay 1.1.0
Installing concurrent-ruby 1.0.0
Installing orm_adapter 0.5.0
Installing thor 0.19.1
Installing docile 1.1.5
Installing dotenv 2.1.0
Installing execjs 2.6.0
Installing multipart-post 2.0.0
Installing ffi 1.9.10 with native extensions
Installing formatador 0.2.5
Installing rb-fsevent 0.9.7
Installing lumberjack 1.0.10
Installing nenv 0.2.0
Installing shellany 0.0.1
Installing method_source 0.8.2
Installing slop 3.6.0
Installing guard-compat 1.2.1
Installing multi_json 1.11.2
Using bundler 1.11.2
Installing mimemagic 0.3.0
Installing pg 0.18.4 with native extensions
Installing puma 2.15.3 with native extensions
Installing rails_serve_static_assets 0.0.4
Installing rails_stdout_logging 0.0.4
Using rdoc 4.2.1
Installing sass 3.4.21
Installing tilt 2.0.2
Installing simplecov-html 0.10.0
Installing spring 1.6.2
Installing swagger-ui_rails 0.1.7
Installing terminal-notifier 1.6.3
Installing terminal-notifier-guard 1.7.0
Installing tzinfo 1.2.2
Installing nokogiri 1.6.8.rc3 with native extensions
…
<error above spits out>
```

I get the same error when I try `gem install nokogiri -v '1.6.8.rc3'`.

Let me know what other information I can get you!

**Comment by flavorjones** [comment]
Does 1.6.7.2 install on this same system? It would be useful to know if it's a behavior change.

If so, please include the output from 'nokogiri -v' in your reply.

**Comment by cbowns** [comment]
1.6.7.2 successfully installs:

```
% ± chruby
   ruby-2.2.1
   ruby-2.2.3
 * ruby-2.3.0

% ± gem install nokogiri -v '1.6.7.2'

Fetching: mini_portile2-2.0.0.gem (100%)
Successfully installed mini_portile2-2.0.0
Fetching: nokogiri-1.6.7.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.7.2
Parsing documentation for mini_portile2-2.0.0
Installing ri documentation for mini_portile2-2.0.0
Parsing documentation for nokogiri-1.6.7.2
Installing ri documentation for nokogiri-1.6.7.2
Done installing documentation for mini_portile2, nokogiri after 4 seconds
2 gems installed
```

Version info:

```
% ± which nokogiri

/usr/local/bin/nokogiri

% ± nokogiri -v

# Nokogiri (1.6.7.2)
    ---
    warnings: []
    nokogiri: 1.6.7.2
    ruby:
      version: 2.3.0
      platform: x86_64-darwin15
      description: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/cbowns/.gem/ruby/2.3.0/gems/nokogiri-1.6.7.2/ports/x86_64-apple-darwin15.3.0/libxml2/2.9.2"
      libxslt_path: "/Users/cbowns/.gem/ruby/2.3.0/gems/nokogiri-1.6.7.2/ports/x86_64-apple-darwin15.3.0/libxslt/1.1.28"
      libxml2_patches:
      - 0001-Revert-Missing-initialization-for-the-catalog-module.patch
      - 0002-Fix-missing-entities-after-CVE-2014-3660-fix.patch
      - 0003-Stop-parsing-on-entities-boundaries-errors.patch
      - 0004-Cleanup-conditional-section-error-handling.patch
      - 0005-CVE-2015-1819-Enforce-the-reader-to-run-in-constant-.patch
      - 0006-Another-variation-of-overflow-in-Conditional-section.patch
      - 0007-Fix-an-error-in-previous-Conditional-section-patch.patch
      - 0008-CVE-2015-8035-Fix-XZ-compression-support-loop.patch
      - 0009-Updated-config.guess.patch
      - 0010-Fix-parsering-short-unclosed-comment-uninitialized-access.patch
      - 0011-Avoid-extra-processing-of-MarkupDecl-when-EOF.patch
      - 0012-Avoid-processing-entities-after-encoding-conversion-.patch
      - 0013-CVE-2015-7497-Avoid-an-heap-buffer-overflow-in-xmlDi.patch
      - 0014-CVE-2015-5312-Another-entity-expansion-issue.patch
      - 0015-Add-xmlHaltParser-to-stop-the-parser.patch
      - 0016-Detect-incoherency-on-GROW.patch
      - 0017-CVE-2015-7500-Fix-memory-access-error-due-to-incorre.patch
      - 0018-CVE-2015-8242-Buffer-overead-with-HTML-parser-in-pus.patch
      - 0019-Do-not-print-error-context-when-there-is-none.patch
      - 0020-xmlStopParser-reset-errNo.patch
      - 0021-Reuse-xmlHaltParser-where-it-makes-sense.patch
      libxslt_patches:
      - 0001-Adding-doc-update-related-to-1.1.28.patch
      - 0002-Fix-a-couple-of-places-where-f-printf-parameters-wer.patch
      - 0003-Initialize-pseudo-random-number-generator-with-curre.patch
      - 0004-EXSLT-function-str-replace-is-broken-as-is.patch
      - 0006-Fix-str-padding-to-work-with-UTF-8-strings.patch
      - 0007-Separate-function-for-predicate-matching-in-patterns.patch
      - 0008-Fix-direct-pattern-matching.patch
      - 0009-Fix-certain-patterns-with-predicates.patch
      - 0010-Fix-handling-of-UTF-8-strings-in-EXSLT-crypto-module.patch
      - 0013-Memory-leak-in-xsltCompileIdKeyPattern-error-path.patch
      - 0014-Fix-for-bug-436589.patch
      - 0015-Fix-mkdir-for-mingw.patch
      - 0016-Fix-for-type-confusion-in-preprocessing-attributes.patch
      - 0017-Updated-config.guess.patch
      compiled: 2.9.2
      loaded: 2.9.2
```
