### ISSUE TITLE
XSD validation skips use="required" in atrribute only in xs:entension

### ISSUE THREAD

**Issue by pedroadame** [sparklemotion/nokogiri#1468]
I'm having an XML and a corresponding XSD. I use the XSD to validate uploaded XMLs by Rails.

My problem is that the XSD defines required attributes for the XML and the validation passes even when the attributes are not present.

Tried a basic XML and XSD in Rails console and all is working correctly.

The XSD part is the following, the required constraints are ignored.
```xml
<xs:element name="AULA">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="num_int_au" use="required"/>
          <xs:attribute type="xs:string" name="abreviatura" use="required"/>
          <xs:attribute type="xs:string" name="nombre" use="required"/>
          <xs:attribute type="xs:string" name="nivel" use="required"/>
          <xs:attribute type="xs:string" name="codigo" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
```

But in fact, here, the constraints work:
```xml
 <xs:element name="CENTRO">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="DATOS"/>
        <xs:element ref="HORARIOS"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="nombre_centro" use="required" />
      <xs:attribute type="xs:string" name="autor"/>
      <xs:attribute type="xs:string" name="fecha"/>
    </xs:complexType>
  </xs:element>
```

Am I doing anything bad?

**Comment by flavorjones** [comment]
Hi,

Please provide a complete working example so that we can reproduce what you're seeing. We'll need your XSD, your code, and information about your platform (you can paste the output of `nokogiri -v`).

Thanks,
-mike

**Comment by pedroadame** [comment]
Hi @flavorjones, here you are! :-)

```
nokogiri -v
# Nokogiri (1.6.7.2)
    ---
    warnings: []
    nokogiri: 1.6.7.2
    ruby:
      version: 2.3.0
      platform: x86_64-linux
      description: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/pedro/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/ports/x86_64-pc-linux-gnu/libxml2/2.9.2"
      libxslt_path: "/home/pedro/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.6.7.2/ports/x86_64-pc-linux-gnu/libxslt/1.1.28"
      libxml2_patches:
      - 0001-Revert-Missing-initialization-for-the-catalog-module.patch
      - 0002-Fix-missing-entities-after-CVE-2014-3660-fix.patch
      - 0003-Stop-parsing-on-entities-boundaries-errors.patch
      - 0004-Cleanup-conditional-section-error-handling.patch
      - 0005-CVE-2015-1819-Enforce-the-reader-to-run-in-constant-.patch
      - 0006-Another-variation-of-overflow-in-Conditional-section.patch
      - 0007-Fix-an-error-in-previous-Conditional-section-patch.patch
      - 0008-CVE-2015-8035-Fix-XZ-compression-support-loop.patch
      - 0009-Updated-config.guess.patch
      - 0010-Fix-parsering-short-unclosed-comment-uninitialized-access.patch
      - 0011-Avoid-extra-processing-of-MarkupDecl-when-EOF.patch
      - 0012-Avoid-processing-entities-after-encoding-conversion-.patch
      - 0013-CVE-2015-7497-Avoid-an-heap-buffer-overflow-in-xmlDi.patch
      - 0014-CVE-2015-5312-Another-entity-expansion-issue.patch
      - 0015-Add-xmlHaltParser-to-stop-the-parser.patch
      - 0016-Detect-incoherency-on-GROW.patch
      - 0017-CVE-2015-7500-Fix-memory-access-error-due-to-incorre.patch
      - 0018-CVE-2015-8242-Buffer-overead-with-HTML-parser-in-pus.patch
      - 0019-Do-not-print-error-context-when-there-is-none.patch
      - 0020-xmlStopParser-reset-errNo.patch
      - 0021-Reuse-xmlHaltParser-where-it-makes-sense.patch
      libxslt_patches:
      - 0001-Adding-doc-update-related-to-1.1.28.patch
      - 0002-Fix-a-couple-of-places-where-f-printf-parameters-wer.patch
      - 0003-Initialize-pseudo-random-number-generator-with-curre.patch
      - 0004-EXSLT-function-str-replace-is-broken-as-is.patch
      - 0006-Fix-str-padding-to-work-with-UTF-8-strings.patch
      - 0007-Separate-function-for-predicate-matching-in-patterns.patch
      - 0008-Fix-direct-pattern-matching.patch
      - 0009-Fix-certain-patterns-with-predicates.patch
      - 0010-Fix-handling-of-UTF-8-strings-in-EXSLT-crypto-module.patch
      - 0013-Memory-leak-in-xsltCompileIdKeyPattern-error-path.patch
      - 0014-Fix-for-bug-436589.patch
      - 0015-Fix-mkdir-for-mingw.patch
      - 0016-Fix-for-type-confusion-in-preprocessing-attributes.patch
      - 0017-Updated-config.guess.patch
      compiled: 2.9.2
      loaded: 2.9.2
```

```ruby
#My code!
# Conversion because the original XML comes in ISO-8859-1
doc = (Nokogiri::XML params[:file].read).serialize(encoding: 'UTF-8') do |c|
      c.format.as_xml
    end
    xml = Nokogiri::XML doc
    Dir.chdir Rails.public_path do
      schema = Nokogiri::XML::Schema(IO.read('database.xsd'))
      errors = schema.validate(xml)
      valid = schema.valid? xml
      if valid && errors.empty?
        logger.debug '---------------- all correct!'
        # Process XML...
      else
        logger.debug '---------------- Ouch, validation errors...'
        errors.each do |e|
          logger.debug "Error: #{e.message}"
        end
      end
    end
```

And my XSD is attached! (As ZIP, GitHub doesn't support XSD files)
[database.xsd.zip](https://github.com/sparklemotion/nokogiri/files/266013/database.xsd.zip)

Hope it gives some light about my problem!
