### ISSUE TITLE
Installed gems using vendored libraries report inappropriate library paths in `nokogiri -v`

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1482]
Cross-compiled windows gem contains misleading and incorrect library paths in `VersionInfo`:

```
C:\Users\admin>nokogiri -v
# Nokogiri (1.6.8)
    ---
    warnings: []
    nokogiri: 1.6.8
    ruby:
      version: 2.2.4
      platform: x64-mingw32
      description: ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/flavorjones/code/oss/nokogiri/ports/x86_64-w64-mingw32/libxml2/2.9.4"
      libxslt_path: "/home/flavorjones/code/oss/nokogiri/ports/x86_64-w64-mingw32/libxslt/1.1.29"
      libxml2_patches: []
      libxslt_patches: []
      compiled: 2.9.4
      loaded: 2.9.4
```

Really, we should alter `VersionInfo` to only contain these paths if using the system libraries, regardless of platform.
