### ISSUE TITLE
adding duplicate child element broken

### ISSUE THREAD

**Issue by akostadinov** [sparklemotion/nokogiri#1484]
This is related to #1200 

I have a reproducer here:
https://gist.github.com/akostadinov/f450c1282cd10e2045befc70db9c506a

Basically duplicating an element under same parent does not work unless the element is `element.dup` before adding it as a second child.

**Comment by flavorjones** [comment]
I'm not sure I understand this bug report, as you haven't specified what output you're **actually** seeing with your version of nokogiri, nor what you **expect** to see.

The output I see using this nokogiri:

```
# Nokogiri (1.7.0.1)
    ---
    warnings: []
    nokogiri: 1.7.0.1
    ruby:
      version: 2.4.0
      platform: x86_64-linux
      description: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/flavorjones/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.7.0.1/ports/x86_64-pc-linux-gnu/libxml2/2.9.4"
      libxslt_path: "/home/flavorjones/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.7.0.1/ports/x86_64-pc-linux-gnu/libxslt/1.1.29"
      libxml2_patches: []
      libxslt_patches: []
      compiled: 2.9.4
      loaded: 2.9.4
```

is

```
== Original document
<?xml version="1.0"?>
<wrapper xmlns="ns">
    <record xmlns:extra="extra" xml:id="r1">
        <field>aaa</field>
        <field extra:type="second">bbb</field>
    </record>
</wrapper>

== New document
== Where is my second record?!!
<?xml version="1.0"?>
<wrapper xmlns="ns">
    
<record xmlns:extra="extra" xml:id="r1">
        <field>aaa</field>
        <field extra:type="second">bbb</field>
    </record></wrapper>
```

which is exactly what I expect, since you're taking the node and putting it back where it came from. At no point are you copying the node.

If you want to make a copy of the node, then make the copy using `#dup`.
