### ISSUE TITLE
Nokogiri::HTML.fragment has no elements on Heroku

### ISSUE THREAD

**Issue by marcandre** [sparklemotion/nokogiri#1548]
**What problems are you experiencing?**

Incredibly, on Heroku:

```
Nokogiri::HTML.fragment('<p>Hello, world</p>').elements # => []
```

Note that only the combination of using `fragment` and `elements` fail. Using `chidren` instead works, or `parse` instead of `fragment` is also fine:

```
Nokogiri::HTML.fragment('<p>Hello, world</p>').children # => [#<Nokogiri::XML::Element...]
Nokogiri::HTML.parse('<html><body>Hello, world</body></html>').elements # => [#<Nokogiri::XML::Element...]
```

**What's the output from `nokogiri -v`?**

```
# Nokogiri (1.6.8.1)
    ---
    warnings: []
    nokogiri: 1.6.8.1
    ruby:
      version: 2.2.4
      platform: x86_64-linux
      description: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: system
      compiled: 2.9.1
      loaded: 2.9.1
```

**Can you provide a self-contained script that reproduces what you're seeing?**

Create an app on Heroku. Push any repository with `nokogiri` in the Gemfile. Then:

```
$ heroku run irb
Running irb on ⬢ your_app_name... up, run.2599 (Free)
irb(main):005:0> require 'nokogiri'
irb(main):005:0> Nokogiri::HTML.fragment('<p>Hello, world</p>').elements
=> []
```
