### ISSUE TITLE
Nokogiri + safe navigation methods chain

### ISSUE THREAD

**Issue by smileart** [sparklemotion/nokogiri#1551]
## Nokogiri + safe navigation methods chain

**What problems are you experiencing?**

Trying to parse an HTML document using chain of methods. In case page contains all the elements for my CSS selectors — everytihing works perfectly fine, but in case I doesn't I'd like to use `.try` or built-in safe navigation operator `&.`, but instead of bubbling up my `nil` through the chain I get this internal exception: `nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:164:in attr': undefined method attribute' for nil:NilClass (NoMethodError)`, since internaly Nokogiri trying to call methods on `nil` values instead of 'trying' or checking `#respond_to?`. 

While I can't realy influence it to do otherwise, the way I fix it is simply breaking my chain and checking if an array after `#css` isn't empty and only then continuing to work with it.

I'm not sure if it's a 'by design' behaviour or something could be done with it, so I decided to submit this issue.

**What's the output from `nokogiri -v`?**

```
# Nokogiri (1.6.8)
    ---
    warnings: []
    nokogiri: 1.6.8
    ruby:
      version: 2.3.1
      platform: x86_64-darwin15
      description: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/usr/local/Cellar/rbenv/1.0.0/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/ports/x86_64-apple-darwin15.6.0/libxml2/2.9.4"
      libxslt_path: "/usr/local/Cellar/rbenv/1.0.0/versions/2.3.1/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/ports/x86_64-apple-darwin15.6.0/libxslt/1.1.29"
      libxml2_patches: []
      libxslt_patches: []
      compiled: 2.9.4
      loaded: 2.9.4
```

**Can you provide a self-contained script that reproduces what you're seeing?**

```ruby
require 'net/http'
require 'uri'
require 'nokogiri'
require 'active_support/core_ext/object/try'

response = Net::HTTP.get(URI('http://example.com'))

Nokogiri::HTML(response).try(:css, '.some-class')
                        .try(:attribute, 'class')
                        .try(:value)

# Nokogiri::HTML(response)&.css('.some-class')
#                         &.attribute('class')
#                         &.value
```
