### ISSUE TITLE
XML parsing fails at vertical tab characters in attributes

### ISSUE THREAD

**Issue by logiclrd** [sparklemotion/nokogiri#1581]
Nokogiri has difficulties if the XML input contains vertical tab characters ("\v") within attribute values. It appears to abort element parsing and treat all following text, up to the next element start, as a text node.

The following script reproduces this:
```
require 'nokogiri'
require 'pp'

print Nokogiri::VersionInfo.new.to_markdown
print "\n"

def test(input)
  print "\n"
  print "input: "
  pp input

  print "output: "
  pp Nokogiri::XML(input).to_xml
end

test "<test attr=\"before\vafter\" />"
test "<test attr=\"before\vafter\" attr2=\"second attribute\" />"
test "<root><test attr=\"before\vafter\" attr2=\"second attribute\" /></root>"
test "<root><test attr=\"before\vafter\" attr2=\"second attribute\" /><test2 attr=\"value\" /></root>"
```

The output from this script on my system is as follows:
```
# Nokogiri (1.7.0.1)
    ---
    warnings: []
    nokogiri: 1.7.0.1
    ruby:
      version: 2.2.3
      platform: i386-mingw32
      description: ruby 2.2.3p173 (2015-08-18 revision 51636) [i386-mingw32]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/flavorjones/code/oss/nokogiri/ports/i686-w64-mingw32/libxml2/2.9.4"
      libxslt_path: "/home/flavorjones/code/oss/nokogiri/ports/i686-w64-mingw32/libxslt/1.1.29"
      libxml2_patches: []
      libxslt_patches: []
      compiled: 2.9.4
      loaded: 2.9.4


input: "<test attr=\"before\vafter\" />"
output: "<?xml version=\"1.0\"?>\n<test attr=\"before\"/>\n"

input: "<test attr=\"before\vafter\" attr2=\"second attribute\" />"
output: "<?xml version=\"1.0\"?>\n<test attr=\"before\"/>\n"

input: "<root><test attr=\"before\vafter\" attr2=\"second attribute\" /></root>"
output: "<?xml version=\"1.0\"?>\n<root><test attr=\"before\"/>after\" attr2=\"second attribute\" /&gt;</root>\n"

input: "<root><test attr=\"before\vafter\" attr2=\"second attribute\" /><test2 attr=\"value\" /></root>"
output: "<?xml version=\"1.0\"?>\n<root><test attr=\"before\"/>after\" attr2=\"second attribute\" /&gt;<test2 attr=\"value\"/></root>\n"
```

Note that when the element being parsed is the root element, the text node that Nokogiri is interpreting as being after the end of the root element disappears. I assume this is because there is nowhere to attach it to the DOM, since it isn't contained within the document element. When there is a place to hook it up, that content becomes text following the element that originally contained it. When another element is encountered, the parser recovers and parses it correctly as another element.

The correct behaviour in this instance seems to be governed by sections 2.3 and 3.3.3 from the XML specification, namely this grammar rule under "Literals" in section 2.3 "Common Syntactic Constructs":

> `[10]   	AttValue	   ::=   	'"' ([^<&"] | Reference)* '"'`
> `                |  "'" ([^<&'] | Reference)* "'"`

..and this section describing the interpretation of the characters captured by the grammar rule:

> # 3.3.3 Attribute-Value Normalization
> 
> Before the value of an attribute is passed to the application or checked for validity, the XML processor must normalize the attribute value by applying the algorithm below, or by using some other method such that the value passed to the application is the same as that produced by the algorithm.
> 
> 1. All line breaks must have been normalized on input to #xA as described in 2.11 End-of-Line Handling, so the rest of this algorithm operates on text normalized in this way.
> 
> 2. Begin with a normalized value consisting of the empty string.
> 
> 3. For each character, entity reference, or character reference in the unnormalized attribute value, beginning with the first and continuing to the last, do the following:
> 
>     * For a character reference, append the referenced character to the normalized value.
> 
>     * For an entity reference, recursively apply step 3 of this algorithm to the replacement text of the entity.
> 
>     * For a white space character (#x20, #xD, #xA, #x9), append a space character (#x20) to the normalized value.
> 
>     * For another character, append the character to the normalized value.

The vertical tab character, #xB, receives no special attention in either of these; the character class rule that defines the content of `AttValue` includes any character other than left angle bracket, ampersand and whichever delimeter character is used in the attribute (' or "), and then characters with value 11 should pass through the "Attribute-Value Normalization" algorithm unchanged, as they would match the final point ("For another character, ...").
