### ISSUE TITLE
Incorrect ruby requirement on rubygems.org for v1.8.0

### ISSUE THREAD

**Issue by glennsarti** [sparklemotion/nokogiri#1648]
On the rubygems.org website it is stated that nokogiri 1.8.0 requires ruby 2.1.0 or above.  However the metadata in the gem says it is ruby 2.2.0 or above

Screenshot of RubyGems.org (5th June)
![image](https://cloud.githubusercontent.com/assets/5819622/26794359/34d3143a-49d6-11e7-8f94-30c8d231a33e.png)

metadata:
```
...
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: '2.2'
  - - "<"
    - !ruby/object:Gem::Version
      version: '2.5'
...
```

This leads to a confusing experience as a user because the documentation is misleading.
