### ISSUE TITLE
Fixnum is deprecated (Ruby 2.4.1)

### ISSUE THREAD

**Issue by oniofchaos** [sparklemotion/nokogiri#1662]
## If you're having trouble installing Nokogiri ...

**Have you tried following [the installation tutorial][tutorial]?**

**What is the output of `gem install`?**

**What are the contents of the `mkmf.log` file?**

**What operating system are you using?**

## If this isn't an installation issue ...

**What problems are you experiencing?**

Deprecation warnings from Ruby's Fixnum => Integer conversion.

```
nokogiri-1.6.7.2/lib/nokogiri/xml/document.rb:44: warning: constant ::Fixnum is deprecated
```

**What's the output from `nokogiri -v`?**
```
# Nokogiri (1.6.7.2)
    ---
    warnings: []
    nokogiri: 1.6.7.2
    ruby:
      version: 2.4.1
      platform: x86_64-darwin16
      description: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/dillonwelch/.rvm/gems/ruby-2.4.1/gems/nokogiri-1.6.7.2/ports/x86_64-apple-darwin16.4.0/libxml2/2.9.2"
      libxslt_path: "/Users/dillonwelch/.rvm/gems/ruby-2.4.1/gems/nokogiri-1.6.7.2/ports/x86_64-apple-darwin16.4.0/libxslt/1.1.28"
      libxml2_patches:
      - 0001-Revert-Missing-initialization-for-the-catalog-module.patch
      - 0002-Fix-missing-entities-after-CVE-2014-3660-fix.patch
      - 0003-Stop-parsing-on-entities-boundaries-errors.patch
      - 0004-Cleanup-conditional-section-error-handling.patch
      - 0005-CVE-2015-1819-Enforce-the-reader-to-run-in-constant-.patch
      - 0006-Another-variation-of-overflow-in-Conditional-section.patch
      - 0007-Fix-an-error-in-previous-Conditional-section-patch.patch
      - '0008-CVE-2015-8035-Fix-XZ-compression-support-loop.patch'
      - '0009-Updated-config.guess.patch'
      - 0010-Fix-parsering-short-unclosed-comment-uninitialized-access.patch
      - 0011-Avoid-extra-processing-of-MarkupDecl-when-EOF.patch
      - 0012-Avoid-processing-entities-after-encoding-conversion-.patch
      - 0013-CVE-2015-7497-Avoid-an-heap-buffer-overflow-in-xmlDi.patch
      - 0014-CVE-2015-5312-Another-entity-expansion-issue.patch
      - 0015-Add-xmlHaltParser-to-stop-the-parser.patch
      - 0016-Detect-incoherency-on-GROW.patch
      - 0017-CVE-2015-7500-Fix-memory-access-error-due-to-incorre.patch
      - '0018-CVE-2015-8242-Buffer-overead-with-HTML-parser-in-pus.patch'
      - '0019-Do-not-print-error-context-when-there-is-none.patch'
      - 0020-xmlStopParser-reset-errNo.patch
      - 0021-Reuse-xmlHaltParser-where-it-makes-sense.patch
      libxslt_patches:
      - 0001-Adding-doc-update-related-to-1.1.28.patch
      - 0002-Fix-a-couple-of-places-where-f-printf-parameters-wer.patch
      - 0003-Initialize-pseudo-random-number-generator-with-curre.patch
      - 0004-EXSLT-function-str-replace-is-broken-as-is.patch
      - 0006-Fix-str-padding-to-work-with-UTF-8-strings.patch
      - 0007-Separate-function-for-predicate-matching-in-patterns.patch
      - '0008-Fix-direct-pattern-matching.patch'
      - '0009-Fix-certain-patterns-with-predicates.patch'
      - 0010-Fix-handling-of-UTF-8-strings-in-EXSLT-crypto-module.patch
      - 0013-Memory-leak-in-xsltCompileIdKeyPattern-error-path.patch
      - 0014-Fix-for-bug-436589.patch
      - 0015-Fix-mkdir-for-mingw.patch
      - 0016-Fix-for-type-confusion-in-preprocessing-attributes.patch
      - 0017-Updated-config.guess.patch
      compiled: 2.9.2
      loaded: 2.9.2
```
**Can you provide a self-contained script that reproduces what you're seeing?**
```
Nokogiri::XML(file)
```

[tutorial]: http://www.nokogiri.org/tutorials/installing_nokogiri.html
