### ISSUE TITLE
Script tag content on jruby has Text type, while on MRI it is CDATA

### ISSUE THREAD

**Issue by kovyrin** [sparklemotion/nokogiri#1680]
## What problems are you experiencing?

When Nokogiri parses an HTML document, there are slight differences in its behavior between MRI and JRuby versions. MRI uses CDATA as the type for `<script>` tag contents, while Jruby version treats the content as text. 

## What's the output from `nokogiri -v`?

On MRI:
```
# Nokogiri (1.8.1)
    ---
    warnings: []
    nokogiri: 1.8.1
    ruby:
      version: 2.2.8
      platform: x86_64-darwin16
      description: ruby 2.2.8p477 (2017-09-14 revision 59906) [x86_64-darwin16]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/kovyrin/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/nokogiri-1.8.1/ports/x86_64-apple-darwin16.7.0/libxml2/2.9.5"
      libxslt_path: "/Users/kovyrin/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/gems/nokogiri-1.8.1/ports/x86_64-apple-darwin16.7.0/libxslt/1.1.30"
      libxml2_patches: []
      libxslt_patches: []
      compiled: 2.9.5
      loaded: 2.9.5
```

On jruby:
```
# Nokogiri (1.8.1)
    ---
    warnings: []
    nokogiri: 1.8.1
    ruby:
      version: 2.3.3
      platform: java
      description: jruby 9.1.13.0 (2.3.3) 2017-09-06 8e1c115 Java HotSpot(TM) 64-Bit Server
        VM 24.80-b11 on 1.7.0_80-b15 +jit [darwin-x86_64]
      engine: jruby
      jruby: 9.1.13.0
    xerces: Xerces-J 2.11.0
    nekohtml: NekoHTML 1.9.21
```

## Can you provide a self-contained script that reproduces what you're seeing?

Yes, you could find a reproducible testcase [in this repository](https://github.com/kovyrin/nokogiri-script-jruby-bug).

Let me know if I could help with any further debugging.
