### ISSUE TITLE
Document fragments with nonstandard tags are added incorrectly to HTML document

### ISSUE THREAD

**Issue by jslabovitz** [sparklemotion/nokogiri#1701]
**What problems are you experiencing?**

I have a toolset that extensively uses Nokogiri's features of adding HTML fragments to existing HTML documents, using Builder. I've found that if the fragments contain nonstandard HTML tags, they are apparently added at the wrong level of the document.

There's certainly a chance I'm doing something out of scope of what Nokogiri is intended to do. I don't mind being told that.

I created a minimal script that triggers this problem (see below). If you run this, you'll see output like the following (minus the doctypes for clarity):

    <html><body><p>z</p></body></html>

    <html><x>z</x></html>

The first line is the document when a fragment with standard tags is added. The second line is with a nonstandard `<x>` tag. You will see that in the case of the latter, the `<body>` element disappears.

**What's the output from `nokogiri -v`?**

````
# Nokogiri (1.8.1)
    ---
    warnings: []
    nokogiri: 1.8.1
    ruby:
      version: 2.4.2
      platform: x86_64-darwin17
      description: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/usr/local/lib/ruby/gems/2.4.0/gems/nokogiri-1.8.1/ports/x86_64-apple-darwin17.0.0/libxml2/2.9.5"
      libxslt_path: "/usr/local/lib/ruby/gems/2.4.0/gems/nokogiri-1.8.1/ports/x86_64-apple-darwin17.0.0/libxslt/1.1.30"
      libxml2_patches: []
      libxslt_patches: []
      compiled: 2.9.5
      loaded: 2.9.5
````

**Can you provide a self-contained script that reproduces what you're seeing?**

````
require 'nokogiri'

def parse(text)
  src = Nokogiri::HTML::Document.parse(text)
  dest = Nokogiri::HTML::Document.new
  Nokogiri::HTML::Builder.with(dest) do |builder|
    builder.html do
      fragment = Nokogiri::HTML::DocumentFragment.parse('')
      Nokogiri::HTML::Builder.with(fragment) do |fragment|
        fragment << src.at_xpath('/html/body').to_html
      end
      builder << fragment.to_html
    end
  end
  dest.to_html
end

%w{
  <html><body><p>z</p></body></html>
  <html><body><x>z</x></body></html>
}.each do |text|
  puts parse(text)
  puts
end
````
