### ISSUE TITLE
JRuby XPATH Memory Usage

### ISSUE THREAD

**Issue by peoplesmeat** [sparklemotion/nokogiri#1749]
When using Nokogiri on jruby with a nested XPATH loop, the document memory footpring explodes in size. 

For example, with a document like
`<items>
  <item>
    <value1>
    <value2>
  <item>`
  ... for many thousands of items

And attempting to use (for example) an xpath like: doc.xpath('items').each { |node| node.xpath('value1') }

You'll wind up with a document that could be hundreds of megabytes large due to caching in the CACHED_XPATH_CONTEXT layer. Specifically the nokogiri.internals.XalanDTMManagerPatch winds up with thousands of values in "m_dtm". I'm not an expert in this area and am unclear what that terminology is referencing. In my case I had a document with 4000 items taking 4GB of memory of cached xpath. And there appears to be no way to clear that specific cache. 

This behavior is not present in the mri ruby version.

**Comment by flavorjones** [comment]
Hi,

Thanks for reporting this. The issue template that you deleted when filing this had a few key questions that will help us reproduce and diagnose this issue:

**What's the output from `nokogiri -v`?**

**Can you provide a self-contained script that reproduces what you're seeing?**

Based on what you've written, I'm assuming we'll be able to reproduce it, but helping us out means we're likely to get to it sooner, and we'll have a test case to work against.

**Comment by flavorjones** [comment]
A couple of things that a working example would clarify: the document structure (are the tags intended to be unclosed, or self-closing, or ...), the query (is the xpath really `value1` or did you mean `//value1`, or ...)

**Comment by flavorjones** [comment]
Here's my attempt to reproduce:

```
#!/usr/bin/env ruby

require 'nokogiri'

xml = '<items>' + '<item><value1/><value2/></item>'*4000

doc = Nokogiri::XML xml

puts "pid is #{$$}"

loop do
  doc.xpath('items').each { |node| node.xpath('//value1') }
  system "cat /proc/#{$$}/status | egrep 'VmSize|VmRSS'"
end
```

on MRI with this config:

```
# Nokogiri (1.8.2)
    ---
    warnings: []
    nokogiri: 1.8.2
    ruby:
      version: 2.4.1
      platform: x86_64-linux
      description: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/flavorjones/.rvm/gems/ruby-2.4.1/gems/nokogiri-1.8.2/ports/x86_64-pc-linux-gnu/libxml2/2.9.7"
      libxslt_path: "/home/flavorjones/.rvm/gems/ruby-2.4.1/gems/nokogiri-1.8.2/ports/x86_64-pc-linux-gnu/libxslt/1.1.32"
      libxml2_patches: []
      libxslt_patches: []
      compiled: 2.9.7
      loaded: 2.9.7
```

memory usage stabilizes at:

```
VmSize:	   75316 kB
VmRSS:	   26968 kB
```

on JRuby with this config:

```
# Nokogiri (1.8.2)
    ---
    warnings: []
    nokogiri: 1.8.2
    ruby:
      version: 2.3.3
      platform: java
      description: jruby 9.1.15.0 (2.3.3) 2017-12-07 929fde8 OpenJDK 64-Bit Server VM
        25.162-b12 on 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12 [linux-x86_64]
      engine: jruby
      jruby: 9.1.15.0
    xerces: Xerces-J 2.11.0
    nekohtml: NekoHTML 1.9.21
```

the memory usage is much larger, stabilizing around:

```
VmSize:	 3068068 kB
VmRSS:	  401372 kB
```

does this match what you're seeing?
