### ISSUE TITLE
XmlSaxPushParser on JRuby and MRI disagree on how it handles empty input

### ISSUE THREAD

**Issue by jvshahid** [sparklemotion/nokogiri#1758]
**What problems are you experiencing?**

the output from the following script is different on JRuby and MRI.

```
#!/usr/bin/env ruby

require 'nokogiri'

class Doc < Nokogiri::XML::SAX::Document
  attr_reader :errors
  def error error
    (@errors ||= []) << error
    super
  end
end
parser = Nokogiri::XML::SAX::PushParser.new(Doc.new)
parser.finish
puts parser.document.errors.inspect
```

on MRI
```
/home/jvshahid/codez/nokogiri/lib/nokogiri/xml/sax/push_parser.rb:47:in `native_write': 1:1: FATAL: Extra content at the end of the document (Nokogiri::XML::SyntaxError)
        from /home/jvshahid/codez/nokogiri/lib/nokogiri/xml/sax/push_parser.rb:47:in `write'
        from /home/jvshahid/codez/nokogiri/lib/nokogiri/xml/sax/push_parser.rb:55:in `finish'
```

on JRuby
```
nil
```

**What's the output from `nokogiri -v`?**

Below is the output for JRuby and MRI

```
# Nokogiri (1.8.2)
    ---
    warnings: []
    nokogiri: 1.8.2
    ruby:
      version: 2.3.3
      platform: java
      description: jruby 9.1.16.0 (2.3.3) 2018-02-21 8f3f95a OpenJDK 64-Bit Server VM
        9-internal+0-2016-04-21-232247.buildd.src on 9-internal+0-2016-04-21-232247.buildd.src
        +jit [linux-x86_64]
      engine: jruby
      jruby: 9.1.16.0
    xerces: Xerces-J 2.11.0
    nekohtml: NekoHTML 1.9.21
```
```
# Nokogiri (1.8.2)
    ---
    warnings:
    - Nokogiri was built against LibXML version 2.9.7, but has dynamically loaded 2.9.8
    nokogiri: 1.8.2
    ruby:
      version: 2.2.3
      platform: x86_64-linux
      description: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/jvshahid/codez/nokogiri/ports/x86_64-pc-linux-gnu/libxml2/2.9.8"
      libxslt_path: "/home/jvshahid/codez/nokogiri/ports/x86_64-pc-linux-gnu/libxslt/1.1.32"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      libxslt_patches: []
      compiled: 2.9.7
      loaded: 2.9.8
```

**Can you provide a self-contained script that reproduces what you're seeing?**

provided above
