### ISSUE TITLE
Inconsistent behavior of NodeSet#to_a between MRI + JRuby

### ISSUE THREAD

**Issue by cbeer** [sparklemotion/nokogiri#1782]
I'm seeing inconsistent behavior with Nokogiri 1.8.4 (and, presumably earlier) with empty nodesets. This example is a little contrived, but at least is simple:

```ruby
doc = Nokogiri::XML('<doc />')
Nokogiri::XML::NodeSet.new(doc).to_a # => in MRI: []
Nokogiri::XML::NodeSet.new(doc).to_a # => in JRuby: nil
```

It seems most of the methods in `XmlNodeSet` seem to guard against this case, but not `to_a`:
https://github.com/sparklemotion/nokogiri/blob/master/ext/java/nokogiri/XmlNodeSet.java#L211

<details>
  <summary>
MRI nokogiri -v
</summary>

```
# Nokogiri (1.8.4)
    ---
    warnings: []
    nokogiri: 1.8.4
    ruby:
      version: 2.4.1
      platform: x86_64-darwin16
      description: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/cabeer/.gem/ruby/2.4.1/gems/nokogiri-1.8.4/ports/x86_64-apple-darwin16.7.0/libxml2/2.9.8"
      libxslt_path: "/Users/cabeer/.gem/ruby/2.4.1/gems/nokogiri-1.8.4/ports/x86_64-apple-darwin16.7.0/libxslt/1.1.32"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      libxslt_patches: []
      compiled: 2.9.8
      loaded: 2.9.8
```

</details>

<details>
  <summary>
JRuby nokogiri -v
</summary>

```
# Nokogiri (1.8.4)
    ---
    warnings: []
    nokogiri: 1.8.4
    ruby:
      version: 2.5.0
      platform: java
      description: jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server
        VM 25.102-b14 on 1.8.0_102-b14 +jit [darwin-x86_64]
      engine: jruby
      jruby: 9.2.0.0
    xerces: Xerces-J 2.11.0
    nekohtml: NekoHTML 1.9.21
```
</details>
