### ISSUE TITLE
XML parser assigns text value to the parent Node instead of actual sub-node

### ISSUE THREAD

**Issue by apchew** [sparklemotion/nokogiri#1783]
**What problems are you experiencing?**

I parsed the following xml in a Nokogiri::XML(xml_string)
```xml
<Report xmlns="http://test.com/2018-03-08" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <SubReport subReportId="https://test.com/transaction/abcd" state="failed">
    <SubSubReport subSubReportId="id://test.com/A/1efg" success="false" recordId="abc123">
      <Message severity="warn" location="//a/b/c" reasonCode="http://test.com/#semantic-issues">
        <Comment>Comment A</Comment>
      </Message>
      
    </SubSubReport >
  </SubReport >
</Report>
```
I then searched using the xpath `//xmlns:SubSubReport[@subSubReportId='id://test.com/A/1efg']/Comment`

Printed out the text value like so:
```ruby
puts Nokogiri::XML(xml_string).xpath("//xmlns:SubSubReport[@subSubReportId='id://test.com/A/1efg']/Comment").text()
```

It outputs nothing.

When I search on the parent node
```ruby
puts Nokogiri::XML(xml_string).xpath("//xmlns:SubSubReport[@subSubReportId='id://test.com/A/1efg']").text()
```

I get: "\n        Comment A\n      "

Surely I expect "Comment A" to exist as text on the Comment Node and not on the Message Node.

**nokogiri -v**
```
# Nokogiri (1.8.2)
    ---
    warnings: []
    nokogiri: 1.8.2
    ruby:
      version: 2.3.6
      platform: x86_64-linux
      description: ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: system
      compiled: 2.9.1
      loaded: 2.9.1
```
