### ISSUE TITLE
Segmentation fault during XSLT transformation

### ISSUE THREAD

**Issue by ojundt** [sparklemotion/nokogiri#1802]
**What problems are you experiencing?**
Nokogiri crashes with a segmentation fault during a XSLT transformation.

**What's the output from `nokogiri -v`?**
```
# Nokogiri (1.8.5)
    ---
    warnings: []
    nokogiri: 1.8.5
    ruby:
      version: 2.5.1
      platform: x86_64-darwin17
      description: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/foobar/.rvm/gems/ruby-2.5.1/gems/nokogiri-1.8.5/ports/x86_64-apple-darwin17.4.0/libxml2/2.9.8"
      libxslt_path: "/Users/foobar/.rvm/gems/ruby-2.5.1/gems/nokogiri-1.8.5/ports/x86_64-apple-darwin17.4.0/libxslt/1.1.32"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Fix-nullptr-deref-with-XPath-logic-ops.patch
      - 0003-Fix-infinite-loop-in-LZMA-decompression.patch
      libxslt_patches: []
      compiled: 2.9.8
      loaded: 2.9.8
```

**Can you provide a self-contained script that reproduces what you're seeing?**
Yes, see [example.zip](https://github.com/sparklemotion/nokogiri/files/2463902/example.zip) for a simple ruby script and example XSL and XML file.
