### ISSUE TITLE
Memory leak when using Nokogiri::XML::Builder with XML namespaces in nested elements

### ISSUE THREAD

**Issue by paddor** [sparklemotion/nokogiri#1810]
**What problems are you experiencing?**
Maybe related or similar to #1771. Memory leak when using `Nokogiri::XML::Builder` and namespaces. Only namespace definitions beginning with `xmlns:` cause the leak (because [Nokogiri::XML::Document#create_element](https://github.com/sparklemotion/nokogiri/blob/master/lib/nokogiri/xml/document.rb#L79-L110) is implemented that way), and nesting seems to be important too. I guess [ Nokogiri::XML::Node#add_namespace_definition](https://github.com/sparklemotion/nokogiri/blob/master/ext/nokogiri/xml_node.c#L1298-L1339) doesn't free that definition when the node is garbage collected.

**What's the output from `nokogiri -v`?**
```
# Nokogiri (1.8.5)
    ---
    warnings: []
    nokogiri: 1.8.5
    ruby:
      version: 2.5.1
      platform: x86_64-linux
      description: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/p/.gem/ruby/2.5.1/gems/nokogiri-1.8.5/ports/x86_64-pc-linux-gnu/libxml2/2.9.8"
      libxslt_path: "/home/p/.gem/ruby/2.5.1/gems/nokogiri-1.8.5/ports/x86_64-pc-linux-gnu/libxslt/1.1.32"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Fix-nullptr-deref-with-XPath-logic-ops.patch
      - 0003-Fix-infinite-loop-in-LZMA-decompression.patch
      libxslt_patches: []
      compiled: 2.9.8
      loaded: 2.9.8
```

**Can you provide a self-contained script that reproduces what you're seeing?**
```
require 'nokogiri'

puts "Nokogiri version: #{Nokogiri::VERSION}"
puts "PID: #{$$}"

NS = {
  'xmlns:env': 'http://schemas.xmlsoap.org/soap/envelope/'
}

100.times do |i|
  puts "##{i}"
  5_000.times do
    Nokogiri::XML::Builder.new do |xml|
      #xml.send 'env:Envelope'
      xml.send 'Envelope', nil, NS do |xml|
        xml.send 'Foobar', nil, NS # no leak without this inner call
      end
    end
  end
  GC.start
end
```

When I run this script, its RSS grows continually from ~12 MB up to 60 MB before it exits.
