### ISSUE TITLE
[jruby] HTML::DocumentFragment.parse throws a NPE when namespaced attributes are used

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1836]
```
# Nokogiri (1.9.0.rc1)
    ---
    warnings: []
    nokogiri: 1.9.0.rc1
    ruby:
      version: 2.5.0
      platform: java
      description: jruby 9.2.4.1 (2.5.0) 2018-11-28 f487d1e OpenJDK 64-Bit Server VM 10.0.2+13-Ubuntu-1ubuntu0.18.04.4
        on 10.0.2+13-Ubuntu-1ubuntu0.18.04.4 [linux-x86_64]
      engine: jruby
      jruby: 9.2.4.1
    xerces: Xerces-J 2.12.0
    nekohtml: NekoHTML 1.9.21
```

```
jruby-9.2.4.1 :001 > Nokogiri::HTML::DocumentFragment.parse "<div xml:base='asdf'>hello</div>"
Traceback (most recent call last):
       16: from org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
       15: from org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:317)
       14: from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
       13: from org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
       12: from org.jruby.RubyKernel$INVOKER$s$send.call(RubyKernel$INVOKER$s$send.gen)
       11: from org.jruby.RubyKernel.send(RubyKernel.java:2172)
       10: from org.jruby.RubyBasicObject.send(RubyBasicObject.java:1716)
        9: from org.jruby.RubyClass.finvoke(RubyClass.java:502)
        8: from org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrN.call(JavaMethod.java:846)
        7: from nokogiri.XmlNode$INVOKER$i$0$0$attribute_nodes.call(XmlNode$INVOKER$i$0$0$attribute_nodes.gen)
        6: from nokogiri.XmlNode.attribute_nodes(XmlNode.java:690)
        5: from nokogiri.internals.NokogiriHelpers.getCachedNodeOrCreate(NokogiriHelpers.java:126)
        4: from nokogiri.internals.NokogiriHelpers.constructNode(NokogiriHelpers.java:147)
        3: from nokogiri.XmlNode.setNode(XmlNode.java:583)
        2: from nokogiri.XmlAttr.setNamespaceIfNecessary(XmlAttr.java:106)
        1: from nokogiri.XmlNamespace.createDefaultNamespace(XmlNamespace.java:167)
Java::JavaLang::NullPointerException ()
```

On MRI this is handled OK:

```
2.5.3 :006 > Nokogiri::HTML::DocumentFragment.parse("<div xml:base='asdf'>hello</div>").to_s
 => "<div xml:base=\"asdf\">hello</div>" 
2.5.3 :007 > Nokogiri::HTML::DocumentFragment.parse("<div asdf:qwer='asdf'>hello</div>")
 => #<Nokogiri::HTML::DocumentFragment:0x2b12a98a8590 name="#document-fragment" children=[#<Nokogiri::XML::Element:0x2b12a98a5f84 name="div" attributes=[#<Nokogiri::XML::Attr:0x2b12a98a5908 name="asdf:qwer" value="asdf">] children=[#<Nokogiri::XML::Text:0x2b12a98a4d00 "hello">]>]> 
```

This is happening in the Loofah test suite, which is attempting to sanitize this input. I'd expect that the attribute would be allowed to exist in the document, but honestly any behavior would be preferable to NPE. :-)
