### ISSUE TITLE
Xpath search time for nodes with classes increases exponentially with document size

### ISSUE THREAD

**Issue by cheald** [sparklemotion/nokogiri#1861]
**Describe the bug**

We have an HTML document of about 1.5MB - mostly HTML tables, which is being styled via premailer. Fundamentally, it inlines your styles by finding nodes which styles in a stylesheet apply to. This is simple enough. However, we found that Nokogiri's xpath search gets EXCEPTIONALLY slow for each search that contains classes or IDs when there are a significant number of nodes in your document.

TL;DR:

![image](https://user-images.githubusercontent.com/9830/51139561-73e60880-1801-11e9-899c-14af1d3079cc.png)

**To Reproduce**

I initially used this to surface which variants produce the pathological behavior:

```ruby
require "nokogiri"
require "benchmark"

doc = Nokogiri::HTML::Document.new
body = doc.create_element("body")
doc.add_child(body)

100.times do
  t = doc.create_element("table")
  body.add_child(t)

  50.times do
    tr = doc.create_element("tr")
    t.add_child tr

    10.times do |i|
      td = doc.create_element("td")
      td["class"] = "elem_#{i}"
      tr.add_child td
    end
  end
end

puts "Using Nokogiri version #{Nokogiri::VERSION}"
puts "Searching #{doc.css("*").length} nodes"

Benchmark.bm do |x|
  x.report("table .elem_100")               { doc.css("table .elem_100") }
  x.report("table .elem_5")                 { doc.css("table .elem_5") }
  x.report("table > tr .elem_5")            { doc.css("table > tr .elem_5") }
  x.report("table td")                      { doc.css("table td") }
  x.report("body table tr td")              { doc.css("body table tr td") }
  x.report("table td.elem_5")               { doc.css("table td.elem_5") }
  x.report("table > tr > td.elem_5")        { doc.css("table > tr > td.elem_5") }
  x.report("body > table > tr > td.elem_5") { doc.css("body > table > tr > td.elem_5") }
end
```
This produces a clear pattern: Any selector which is _not_ fully specified, and which includes a class is quite slow.

```
Searching 55101 nodes
                                 user     system      total        real
table .elem_100                6.430000   0.000000   6.430000 (  6.432713)
table .elem_5                  6.630000   0.000000   6.630000 (  6.644569)
table > tr .elem_5             6.590000   0.000000   6.590000 (  6.585917)
table td                       0.000000   0.000000   0.000000 (  0.005402)
body table tr td               0.010000   0.000000   0.010000 (  0.006842)
table td.elem_5                6.530000   0.000000   6.530000 (  6.540232)
table > tr > td.elem_5         0.120000   0.000000   0.120000 (  0.117247)
body > table > tr > td.elem_5  0.110000   0.000000   0.110000 (  0.114711)
```

It's specifically interesting to note that `table td` is fast, while `table td.elem_5` is slow.

I then used a variant of it to plot runtimes as a function of nodes in the document:

```ruby
require "nokogiri"
require "benchmark"

doc = Nokogiri::HTML::Document.new
body = doc.create_element("body")
doc.add_child(body)

20.times do |n|
  ((n + 1) * 3).times do
    t = doc.create_element("table")
    body.add_child(t)

    50.times do
      tr = doc.create_element("tr")
      t.add_child tr

      10.times do |i|
        td = doc.create_element("td")
        td["class"] = "elem_#{i}"
        tr.add_child td
      end
    end
  end

  t = Benchmark.measure { doc.css("table .elem_100") }
  puts [doc.css("*").length, t.real].join(",")
end
```

This produced the plot above. As you can see, there is an exponential runtime increase with a linear increase in nodes, _per search_. In our case, each selector with a class takes about 90 _seconds_ to run, on a document of only about 80k nodes. Multiply that by the number of selectors in the stylesheet that include classes and we have a Very Big Problem.

**Expected behavior**

Runtime should not increase exponentially with number of nodes searched.

**Environment**

```
# Nokogiri (1.10.1)
    ---
    warnings: []
    nokogiri: 1.10.1
    ruby:
      version: 2.4.3
      platform: x86_64-linux
      description: ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/chris/.rvm/gems/ruby-2.4.3/gems/nokogiri-1.10.1/ports/x86_64-pc-linux-gnu/libxml2/2.9.9"
      libxslt_path: "/home/chris/.rvm/gems/ruby-2.4.3/gems/nokogiri-1.10.1/ports/x86_64-pc-linux-gnu/libxslt/1.1.33"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      libxslt_patches: []
      compiled: 2.9.9
      loaded: 2.9.9
```
