### ISSUE TITLE
Changes to Nokogiri::XML::Element#to_s

### ISSUE THREAD

**Issue by ksolo** [sparklemotion/nokogiri#1862]
**Difference in behavior for Nokogiri::XML::Element#to_s**

**To Reproduce**
Nokogiri Version 1.8.1
```ruby
html = "<p><i for=\"&{<test>}\"></i></p>"
document = Nokogiri::HTML::Document.new
nodes = document.parse(html)
nodes[0].to_s #=> "<p><i for=\"&amp;{&lt;test&gt;}\"></i></p>"
```

Nokogiri Version 1.8.5
```ruby
html = "<p><i for=\"&{<test>}\"></i></p>"
document = Nokogiri::HTML::Document.new
nodes = document.parse(html)
nodes[0].to_s #=> "<p><i for=\"&{<test>}\"></i></p>"
```

**Test case**

```ruby
#! /usr/bin/env ruby

require 'nokogiri'
require 'minitest/autorun'

class Test < MiniTest::Spec
  describe "Nokogiri::XML::Element#to_s" do
    it "" do
      html = "<p><i for=\"&{<test>}\"></i></p>"
      document = Nokogiri::HTML::Document.new
      nodes = document.parse(html)

      assert_equal "<p><i for=\"&amp;{&lt;test&gt;}\"></i></p>", nodes[0].to_s
    end
  end
end
```

**Expected behavior**
Result of #to_s to remain consisted between 1.8.1 and 1.8.5+

**Environment**
```
# Nokogiri (1.8.5)
    ---
    warnings: []
    nokogiri: 1.8.5
    ruby:
      version: 2.5.2
      platform: x86_64-darwin18
      description: ruby 2.5.2p65 (2018-07-02 revision 63309) [x86_64-darwin18]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/gems/2.5.2/ruby/2.5.0/gems/nokogiri-1.8.5/ports/x86_64-apple-darwin18.2.0/libxml2/2.9.8"
      libxslt_path: "/gems/2.5.2/ruby/2.5.0/gems/nokogiri-1.8.5/ports/x86_64-apple-darwin18.2.0/libxslt/1.1.32"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Fix-nullptr-deref-with-XPath-logic-ops.patch
      - 0003-Fix-infinite-loop-in-LZMA-decompression.patch
      libxslt_patches: []
      compiled: 2.9.8
      loaded: 2.9.8
```
