### ISSUE TITLE
Problem matching nodes by xpath in XML file containing a CDATA tag larger than 10MB

### ISSUE THREAD

**Issue by danmolloy** [sparklemotion/nokogiri#1869]
When attempting to find all nodes matching a particular xpath, if one of the nodes contains a CDATA tag larger than 10MB, Nokogiri will return all matching nodes up to and including the one with the large CDATA, and ignore subsequent matches. 

Reproduction script:

```ruby
require 'nokogiri'
require 'active_support'
require 'active_support/core_ext'
require 'rspec'

SMALL_TEMPLATE = <<-HEREDOC
<?xml version="1.0"?>

<issues>
  <issue>
    <info><![CDATA[#{"a" * 9.megabytes}]]></info>
  </issue>
  <issue>
    <info><![CDATA[test data]]></info>
  </issue>
  <issue>
    <info><![CDATA[test data]]></info>
  </issue>
</issues>
HEREDOC

BIG_TEMPLATE = <<-HEREDOC
<?xml version="1.0"?>

<issues>
  <issue>
    <info><![CDATA[#{"a" * 10.megabytes}]]></info>
  </issue>
  <issue>
    <info><![CDATA[test data]]></info>
  </issue>
  <issue>
    <info><![CDATA[test data]]></info>
  </issue>
</issues>
HEREDOC

BIG_TEMPLATE_NO_CDATA = <<-HEREDOC
<?xml version="1.0"?>

<issues>
  <issue>
    <info>#{"a" * 11.megabytes}</info>
  </issue>
  <issue>
    <info><![CDATA[test data]]></info>
  </issue>
  <issue>
    <info><![CDATA[test data]]></info>
  </issue>
</issues>
HEREDOC

describe "Nokogiri::XML#xpath" do
  it 'finds all matches when nodes are small' do
    expect(Nokogiri::XML(SMALL_TEMPLATE).xpath('issues/issue').count).to eq 3
  end

  it 'finds all matches when there is a large CDATA node' do
    # this fails - xpath only returns 1 node
    expect(Nokogiri::XML(BIG_TEMPLATE).xpath('issues/issue').count).to eq 3
  end

  it 'finds all matches when there is a large normal node' do
    expect(Nokogiri::XML(BIG_TEMPLATE_NO_CDATA).xpath('issues/issue').count).to eq 3
  end
end
```

**Environment**

```
# Nokogiri (1.10.1)
    ---
    warnings: []
    nokogiri: 1.10.1
    ruby:
      version: 2.5.1
      platform: x86_64-linux
      description: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/dan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.10.1/ports/x86_64-pc-linux-gnu/libxml2/2.9.9"
      libxslt_path: "/home/dan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/nokogiri-1.10.1/ports/x86_64-pc-linux-gnu/libxslt/1.1.33"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      libxslt_patches: []
      compiled: 2.9.9
      loaded: 2.9.9
```
