### ISSUE TITLE
API for change namespace or remove single namespace prefix

### ISSUE THREAD

**Issue by CAMOBAP795** [sparklemotion/nokogiri#1887]
**Describe the bug**

I faced with need to change namespace but with preserving prefix in a document

**To Reproduce**

I have tried:

```ruby
#! /usr/bin/env ruby

require 'nokogiri'
require 'minitest/autorun'

class Test < MiniTest::Spec
  describe "Node namespaces tests" do
    it 'test namespace update #1' do
      doc = Nokogiri::XML.parse('<ns1:test xmlns:ns1="test:namespace"/>')
      doc.root.namespaces['ns1'] = 'test:namespace:upd1'
    
      expect(doc.to_xml).to eq('<?xml version="1.0"?>
<ns1:test xmlns:ns1="test:namespace:upd1"/>')
    end
    
    it 'test namespace update #2' do
      doc = Nokogiri::XML.parse('<ns1:test xmlns:ns1="test:namespace"/>')
      doc.root.add_namespace 'ns1', 'test:namespace:upd1'
    
      expect(doc.to_xml).to eq('<?xml version="1.0"?>
<ns1:test xmlns:ns1="test:namespace:upd1"/>')
    end
    
    it 'test namespace update #3' do
      doc = Nokogiri::XML.parse('<ns1:test xmlns:ns1="test:namespace"/>')
      doc.root.namespace = doc.root.add_namespace 'ns1', 'test:namespace:upd1'
    
      expect(doc.to_xml).to eq('<?xml version="1.0"?>
<ns1:test xmlns:ns1="test:namespace:upd1"/>')
    end
  end
end
```

Also I tried:

```ruby
it 'test namespace update #3' do
    doc = Nokogiri::XML.parse('<ns1:test xmlns:ns1="test:namespace"/>')
    doc.root.namespace = doc.root.add_namespace 'ns2', 'test:namespace:upd1'

    expect(doc.to_xml).to eq('<?xml version="1.0"?>
<ns2:test xmlns:ns1="test:namespace" xmlns:ns2="test:namespace:upd1"/>')
end
```

But it not allowed to preserve namespace prefix

**Expected behavior**

I'm not sure, I just need an API to be able modify/remove specific namespaces for specific node

**Environment**

```
# Nokogiri (1.10.1)
    ---
    warnings: []
    nokogiri: 1.10.1
    ruby:
      version: 2.5.4
      platform: x86_64-darwin18
      description: ruby 2.5.4p155 (2019-03-13 revision 67245) [x86_64-darwin18]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/nokogiri-1.10.1/ports/x86_64-apple-darwin18.2.0/libxml2/2.9.9"
      libxslt_path: "/Users/camobap/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/nokogiri-1.10.1/ports/x86_64-apple-darwin18.2.0/libxslt/1.1.33"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      libxslt_patches: []
      compiled: 2.9.9
      loaded: 2.9.9
```
