### ISSUE TITLE
'li' tags are treated as no content tags when empty

### ISSUE THREAD

**Issue by freak2100** [sparklemotion/nokogiri#1893]
'li' tags are treated as tags with no content, such as 'img', 'br' etc.
XHTML standard defines a list of tags with no content, described here: https://www.w3.org/TR/2009/NOTE-xhtml-media-types-20090116 under "A.2. Elements that can never have content".

Correct examples:
```ruby
Nokogiri::HTML('<html><body><p></p></body></html>').to_s
```
in the output, the ```<p>``` tag remains: ```<p></p>```
```ruby
Nokogiri::HTML('<html><body><p/></body></html>').to_s
```
in the output, the ```<p>``` tag converts into ```<p></p>```, as 'p' tags should have content
```ruby
Nokogiri::HTML('<html><body><img/></body></html>').to_s
```
int the output, the ```<img>``` remains single img tag, as img tags have no content

Problematic examples:
```ruby
Nokogiri::HTML('<html><body><li></li></body></html>').to_s
```
in the output, the ```<li></li>``` converts into ```<li>```, which should not happen
```ruby
Nokogiri::HTML('<html><body><li/></body></html>').to_s
```
in the output, the ```<li/>``` remains a single no-content tag, although 'li' should have content.

Reproduced on the last version:
```
# Nokogiri (1.10.2)
    ---
    warnings: []
    nokogiri: 1.10.2
    ruby:
      version: 2.5.0
      platform: x86_64-darwin16
      description: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/username/.rvm/gems/ruby-2.5.0/gems/nokogiri-1.10.2/ports/x86_64-apple-darwin16.7.0/libxml2/2.9.9"
      libxslt_path: "/Users/username/.rvm/gems/ruby-2.5.0/gems/nokogiri-1.10.2/ports/x86_64-apple-darwin16.7.0/libxslt/1.1.33"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      libxslt_patches: []
      compiled: 2.9.9
      loaded: 2.9.9
```
