### ISSUE TITLE
A leading newline character immediately following a pre element start tag should be stripped

### ISSUE THREAD

**Issue by leppert** [sparklemotion/nokogiri#1906]
The [HTML 5 spec](https://www.w3.org/TR/html5/grouping-content.html#the-pre-element) states:

> In the HTML syntax, a leading newline character immediately following the pre element start tag is stripped.

Nokogiri, however, retains leading newline characters in pre elements.

```ruby
Nokogiri::HTML("<!DOCTYPE html><html><head><title></title></head><body><pre>\nfoo</pre></body>").at("pre")
 => #<Nokogiri::XML::Element:0x3fe3fbdb5960 name="pre" children=[#<Nokogiri::XML::Text:0x3fe3fbdb567c "\nfoo">]> 
```

My env:
```
# Nokogiri (1.10.3)
    ---
    warnings:
    - Nokogiri was built against LibXML version 2.9.2, but has dynamically loaded 2.9.4
    nokogiri: 1.10.3
    ruby:
      version: 2.4.1
      platform: x86_64-darwin17
      description: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
      engine: ruby
    libxml:
      binding: extension
      source: system
      compiled: 2.9.2
      loaded: 2.9.4
```

For additional context, here's how Safari / Chrome / Firefox handle newlines in pre tags:

```javascript
new DOMParser().parseFromString("<!DOCTYPE html><html><head><title></title></head><body><pre>\nfoo</pre></body>", "text/html").querySelector("pre")
=> <pre>foo</pre>
```
