### ISSUE TITLE
Attributes are being stripped

### ISSUE THREAD

**Issue by stylesuxx** [sparklemotion/nokogiri#1909]
I am using AMP HTML and some of my attributes are being stripped. In the following example I am using the [amp-list](https://amp.dev/documentation/components/amp-list) tag with the *[src]* attribute, this is also the attribute being stripped (it seems that the square brackets are the culprit):

```ruby
#! /usr/bin/env ruby

require 'nokogiri'
require 'minitest/autorun'

class Test < MiniTest::Spec
  describe "AMP#square bracket params" do
    it "should not strip the [src] attribute" do
      html = <<~HEREDOC
        <amp-list src="foo" [src]="bar"></amp-list>
      HEREDOC

      doc = Nokogiri::HTML::Document.parse(html)

      assert_equal 1, doc.css("amp-list").length
      assert_equal "foo", doc.css("amp-list").attr("src").text
      assert nil != doc.css("amp-list").attr("[src]")
      assert_equal "bar", doc.css("amp-list").attr("[src]").text
    end
  end
end
```

**Environment**
```
# Nokogiri (1.10.3)
    ---
    warnings: []
    nokogiri: 1.10.3
    ruby:
      version: 2.3.3
      platform: x86_64-linux-gnu
      description: ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/var/lib/gems/2.3.0/gems/nokogiri-1.10.3/ports/x86_64-pc-linux-gnu/libxml2/2.9.9"
      libxslt_path: "/var/lib/gems/2.3.0/gems/nokogiri-1.10.3/ports/x86_64-pc-linux-gnu/libxslt/1.1.33"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      libxslt_patches:
      - 0001-Fix-security-framework-bypass.patch
      compiled: 2.9.9
      loaded: 2.9.9

```
