### ISSUE TITLE
Too many nested elements in the XML cause the indentation string to get truncated during output

### ISSUE THREAD

**Issue by juraj-blahunka** [sparklemotion/nokogiri#1914]
Too many nested elements in the XML cause the indentation string to get truncated during output.

**To Reproduce**

```ruby
#! /usr/bin/env ruby

require 'nokogiri'

xml = Nokogiri::XML("<root><l1><l2><l3><l4><l5><l6><l7><l8><l9><l10><l11></l11></l10></l9></l8></l7></l6></l5></l4></l3></l2></l1></root>") do |config|
    puts config
    config.huge
end

puts xml.to_xml(:indent => 10)
```
The output is the same with and without using `huge`.
The same effect can be achieved by having an even higher number of nested elements with a smaller indentation argument.

Script output:
```
<?xml version="1.0"?>
<root>
          <l1>
                    <l2>
                              <l3>
                                        <l4>
                                                  <l5>
                                                            <l6>
                                                            <l7>
                                                            <l8>
                                                            <l9>
                                                            <l10>
                                                            <l11/>
                                                            </l10>
                                                            </l9>
                                                            </l8>
                                                            </l7>
                                                            </l6>
                                                  </l5>
                                        </l4>
                              </l3>
                    </l2>
          </l1>
</root>
```

**Expected behavior**

```
<?xml version="1.0"?>
<root>
          <l1>
                    <l2>
                              <l3>
                                        <l4>
                                                  <l5>
                                                            <l6>
                                                                      <l7>
                                                                                <l8>
                                                                                          <l9>
                                                                                                    <l10>
                                                                                                              <l11/>
                                                                                                    </l10>
                                                                                          </l9>
                                                                                </l8>
                                                                      </l7>
                                                            </l6>
                                                  </l5>
                                        </l4>
                              </l3>
                    </l2>
          </l1>
</root>
```

**Environment**

```
# Nokogiri (1.10.3)
    ---
    warnings: []
    nokogiri: 1.10.3
    ruby:
      version: 2.4.2
      platform: x86_64-darwin18
      description: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin18]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/jblahunka/.rvm/gems/ruby-2.4.2/gems/nokogiri-1.10.3/ports/x86_64-apple-darwin18.2.0/libxml2/2.9.9"
      libxslt_path: "/Users/jblahunka/.rvm/gems/ruby-2.4.2/gems/nokogiri-1.10.3/ports/x86_64-apple-darwin18.2.0/libxslt/1.1.33"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      libxslt_patches:
      - 0001-Fix-security-framework-bypass.patch
      compiled: 2.9.9
      loaded: 2.9.9
```
