### ISSUE TITLE
HTML Builder escapes too much

### ISSUE THREAD

**Issue by Ecco** [sparklemotion/nokogiri#1920]
**Describe the bug**

I'm trying to generate a link like to an URL with an accent, `<a href="#Éducation">`. This is valid markup, and is different from `<a href="#%C3%89ducation">`. This doesn't seem to be possible with Nokogiri!

**To Reproduce**

```ruby
#! /usr/bin/env ruby
require "nokogiri"

d = Nokogiri::HTML::Builder.new(:encoding => 'UTF-8') do |doc|
  doc.a(href: "#Éducation")
end

puts d.to_html
```

Doctype aside, this yields

```
<a href="#%C3%89ducation"></a>
```

**Expected behavior**

```
<a href="#Éducation"></a>
```

**Environment**

```
# Nokogiri (1.10.3)
    ---
    warnings: []
    nokogiri: 1.10.3
    ruby:
      version: 2.6.3
      platform: x86_64-darwin17
      description: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin17]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/romain/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.3/ports/x86_64-apple-darwin17.7.0/libxml2/2.9.9"
      libxslt_path: "/Users/romain/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.3/ports/x86_64-apple-darwin17.7.0/libxslt/1.1.33"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      libxslt_patches:
      - 0001-Fix-security-framework-bypass.patch
      compiled: 2.9.9
      loaded: 2.9.9
```
