### ISSUE TITLE
Nokogiri::XML::Reader parsing error 

### ISSUE THREAD

**Issue by kapso** [sparklemotion/nokogiri#1945]
I am parsing a 100MB XML document. I was using the following approach which was resulting in the process using massive amount of memory (~3GB)

```ruby
xml_content = open(url)
elements = Nokogiri::XML(xml_content).xpath('//my/x-path')

elements.each do |element|
  xml_doc = element.to_xml(indent: 1)
end
```

So then I moved to `Nokogiri::XML::Reader` which is great coz now the same process uses ~150MB only.  

```ruby
# Also tried the the following options
# Nokogiri::XML::Reader(open(url), nil, nil, Nokogiri::XML::ParseOptions::DEFAULT_XML)
# Nokogiri::XML::Reader(open(url), nil, 'UTF-8', Nokogiri::XML::ParseOptions::DEFAULT_XML)

Nokogiri::XML::Reader(open(url)).each do |node|
  if node.node_type == Nokogiri::XML::Reader::TYPE_ELEMENT && node.name == 'exch:some-document'
    xml_doc = node.outer_xml
  end
end
```

However I am seeing the following errors while parsing the same XML file using  `Nokogiri::XML::Reader`. Interestingly it is not breaking the script, but still the reader does not like the special characters whereas `Nokogiri::XML(xml_content)` was ok with the special characters.

```
Entity: line 1: parser error : Entity 'YACUTE' not defined
office="CN" sequence="5"><nplcit num="5" npl-type="s"><text>FILIP NOVOTN&YACUTE;

Entity: line 1: parser error : Entity 'reg' not defined
="s"><text>G.J.NEL &#31561;: &quot;Novel Design Aspects of the Tati Activox&reg;
```

**Environment (on our Heroku process)**

```
# Nokogiri (1.10.5)
    ---
    warnings: []
    nokogiri: 1.10.5
    ruby:
      version: 2.6.5
      platform: x86_64-linux
      description: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: system
      compiled: 2.9.4
      loaded: 2.9.4
```
