### ISSUE TITLE
Nokogiri does not extract attributes of an HTML fragment.

### ISSUE THREAD

**Issue by Konafets** [sparklemotion/nokogiri#1950]
**Describe the bug**

Nokogiri does not extract attributes of an HTML fragment.

**To Reproduce**

```ruby
#! ~/.rvm/rubies/ruby-2.6.3/bin/ruby
require 'nokogiri'

fragment = Nokogiri::HTML.fragment('<a href="www.example.com">Foo</a>')
puts fragment.to_html
puts fragment.has_attribute? 'href'
puts fragment.attributes
```

Result:
```
<a href="1">Foo</a>
false
{}
```

Here's an example of how you might structure such a script:

**Expected behavior**

I see the attributes.

**Environment**

```
nokogiri -v
# Nokogiri (1.10.5)
    ---
    warnings: []
    nokogiri: 1.10.5
    ruby:
      version: 2.6.3
      platform: x86_64-darwin17
      description: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin17]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/sok/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.10.5/ports/x86_64-apple-darwin17.7.0/libxml2/2.9.10"
      libxslt_path: "/Users/sok/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.10.5/ports/x86_64-apple-darwin17.7.0/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10
```

**Environment**

I installed Ruby with RVM.
