### ISSUE TITLE
From version 1.10.5, XSD validations differ

### ISSUE THREAD

**Issue by EmmaB** [sparklemotion/nokogiri#1960]
**Describe the bug**

Nokogiri version 1.10.5 produces different validation errors to version 1.10.4 against the [ONIX](https://www.editeur.org/8/ONIX/) 2.1 XSD. 

**To reproduce**

Please unzip the attached folder, `cd` into the root `test_case` directory, and run: 

`$ ruby -Ilib:test 1.10.4/test_case.rb`

The test passes. 

Then run 

`$ ruby -Ilib:test 1.10.5/test_case.rb`

This test, which uses the same fixtures, fails, omitting to return the following error: 
```
"26:0: ERROR: Element 'ProductForm': 'ff' is not a valid value of the atomic type 'List7'."
```

Versions 1.10.6 and 1.10.7 also fail, and the ONIX 3.0 XSD also fails, but are not included here for conciseness. 
[test_case.zip](https://github.com/sparklemotion/nokogiri/files/4002626/test_case.zip)

**Expected behaviour**

Both tests should pass.

**Environment**

Each test explicitly specifies the version of Nokogiri to be used. Here's the output of `nokogiri -v`

```
E test_case $ nokogiri -v
# Nokogiri (1.10.7)
    ---
    warnings: []
    nokogiri: 1.10.7
    ruby:
      version: 2.6.5
      platform: x86_64-darwin17
      description: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin17]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/Emma/.rvm/gems/ruby-2.6.5/gems/nokogiri-1.10.7/ports/x86_64-apple-darwin17.7.0/libxml2/2.9.10"
      libxslt_path: "/Users/Emma/.rvm/gems/ruby-2.6.5/gems/nokogiri-1.10.7/ports/x86_64-apple-darwin17.7.0/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10
```

Thanks!
