### ISSUE TITLE
Deprecation warning from dependent library HTTParty

### ISSUE THREAD

**Issue by walt93** [sparklemotion/nokogiri#1964]
**Do not report Security Vulnerabilities here**

Ok!

**Describe the bug**

At runtime I'm seeing the following warning in the logs:

[DEPRECATION] HTTParty will no longer override `response#nil?`. This functionality will be removed in future versions. Please, add explicit check `response.body.nil? || response.body.empty?`. For more info refer to: https://github.com/jnunemaker/httparty/issues/568

**To Reproduce**

It looks like for all intents and purposes its happening on the 2nd of these two lines of code:
    page = HTTParty.get("https://www.youtube.com/watch?v=vqz8c4ZP3Wg")
    doc = Nokogiri::HTML(page)

**Expected behavior**

Not to see the deprecation warning in the logs.

**Environment**

Please paste the output from `nokogiri -v` here, escaped by triple-backtick.
```
# Nokogiri (1.10.7)
    ---
    warnings: []
    nokogiri: 1.10.7
    ruby:
      version: 2.6.3
      platform: x86_64-darwin18
      description: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/walt/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.7/ports/x86_64-apple-darwin18.5.0/libxml2/2.9.10"
      libxslt_path: "/Users/walt/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.7/ports/x86_64-apple-darwin18.5.0/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10
```

**Additional context**

Nope.
