### ISSUE TITLE
make libxslt version info available as a first-class member of `VersionInfo`

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#1974]
See #1482 for details around removing the path to libxslt, which is the only piece of metadata that tells us what version of libxslt is being used.

I'd like to see something similar for libxslt as we have for libxml2:

* track the version used at compile time
* know the version loaded at runtime
* emit both versions as part of `VersionInfo`

This might result in a breaking change to the structure of `VersionInfo` where `libxslt_patches` is moved to under its own key and renamed, so the output would be something like:

```yaml
  nokogiri: 1.10.7
  ruby:
    ...
  libxml:
      binding: extension
      source: packaged
      patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      compiled: 2.9.10
      loaded: 2.9.10
  libxslt:
      binding: extension
      source: packaged
      patches: []
      compiled: 1.1.34
      loaded: 1.1.34
```
