### ISSUE TITLE
Regular expression is not valid

### ISSUE THREAD

**Issue by gr790** [sparklemotion/nokogiri#1999]
**Nokogiri throws error on regular expression**
I was given a schema definition, against which I have to validate the given XML. 
When I try to validate the XML even though this XML doesn't contains any regular expression of this kind, still throws below error.

Portion of XSD look like this.
1: <xsd:pattern value="((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))(\/(([0-9])|([0-9]{2})|(1[0-1][0-9])|(12[0-8])))"/>
2: <xsd:pattern value="((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))(\/.+)"/>

1st RUN against above portion while 1st line was commented.
ERROR: Element '{http://www.w3.org/2001/XMLSchema}pattern': The value '((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))(\/.+)' of the facet 'pattern' is not a valid regular expression.

2nd RUN against above portion, while 2nd line was commented.
Element '{http://www.w3.org/2001/XMLSchema}pattern': The value '((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))(\/(([0-9])|([0-9]{2})|(1[0-1][0-9])|(12[0-8])))' of the facet 'pattern' is not a valid regular expression.

Could you please help me in this. I am doing normal stuff which I supposed to do with XSD and XML files. 

Just a snippet.
**To Reproduce**

```ruby
#! /usr/bin/env ruby

require 'nokogiri'

Creating Schema instance like below.
         @schema   = Nokogiri::XML::Schema(IO.read('schema.xsd'))

Validating against schema like below, where XML node is node which doesn't have soap headers ...and just contains XML data in line with schema.xsd.
        @schema.validate Nokogiri::XML(xmlnode.to_s)
```

**Expected behavior**

Ideally schema should validate XML files successfully, even if XML files contains regular expression data. But it fails even XML files doesn't have any regular expression data associated with above lines.

**Environment**
```
[root@docker schema_validation]# nokogiri -v
# Nokogiri (1.10.5)
    ---
    warnings: []
    nokogiri: 1.10.5
    ruby:
      version: 2.5.3
      platform: x86_64-linux
      description: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: system
      compiled: 2.9.1
      loaded: 2.9.1
[root@docker schema_validation]#
```
**Additional context**
When I disable above 2 lines, my XML files validated successfully.
