### ISSUE TITLE
Nokogiri 1.10.9 libc errors

### ISSUE THREAD

**Issue by mortenolsrud** [sparklemotion/nokogiri#2009]
**Describe the bug**
I ran bundle update to upgrade my puma dependency in the Rails project I'm working on, and saw that nokogiri-1.10.9 was also pulled in. When I tried running Rails after this through `bundle exec rails s -b 0.0.0.0` I get a stack trace which gives me this conclusion:

> /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri.rb:32:in `require': /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/nokogiri.so) - /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/nokogiri.so (LoadError)

**Expected behavior**

I was unable to provide code due to proprietary code, but I expected Rails to start.

**Environment**
Nokogiri -v fails for 1.10.9:
```
LoadError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/nokogiri.so) - /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/nokogiri.so
  /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri.rb:32:in `require'
  /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri.rb:32:in `rescue in <top (required)>'
  /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri.rb:28:in `<top (required)>'
  /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/bin/nokogiri:6:in `require'
  /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/bin/nokogiri:6:in `<top (required)>'
  /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/bin/nokogiri:23:in `load'
  /home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/bin/nokogiri:23:in `<top (required)>'
```
See env for 1.10.8 below

```
vagrant@tallinn-dev:~/tallinn$ bundle exec nokogiri -v
# Nokogiri (1.10.8)
    ---
    warnings: []
    nokogiri: 1.10.8
    ruby:
      version: 2.6.5
      platform: x86_64-linux
      description: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.8/ports/x86_64-pc-linux-gnu/libxml2/2.9.10"
      libxslt_path: "/home/vagrant/tallinn/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.8/ports/x86_64-pc-linux-gnu/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10

```
