### ISSUE TITLE
Segmentation fault at document_fragment.rb:7:in `new`

### ISSUE THREAD

**Issue by asbjornu** [sparklemotion/nokogiri#2012]
**Describe the bug**

I have [pretty simple Docker setup for Jekyll](https://github.com/SwedbankPay/swedbank-pay-design-guide-jekyll-theme/blob/master/docker-compose.yml) that sometimes goes belly up with a segmentation fault. [The full stack trace can be found in this Gist](https://gist.github.com/asbjornu/dd28617d42ba4a6698487118336268f5).

**To Reproduce**

Clone [the repository](https://github.com/SwedbankPay/swedbank-pay-design-guide-jekyll-theme) and run `docker-compose up`. The segmentation fault seems to happen more during Jekyll's live reload than rebuilds, but can happen on both. It also only seems to happen on macOS (10.14.6), not on Windows. Linux has not been tested.

**Expected behavior**

I expect no segmentation fault to occur.

**Environment**

```
# Nokogiri (1.10.9)
    ---
    warnings: []
    nokogiri: 1.10.9
    ruby:
      version: 2.6.5
      platform: x86_64-linux-musl
      description: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]
      engine: ruby
    libxml:
      binding: extension
      source: system
      compiled: 2.9.9
      loaded: 2.9.9
```

**Additional context**

As mentioned, this happens in Jekyll's Docker container `jekyll/jekyll`. I'm wondering whether [the following lines from Jekyll's `Dockerfile`](https://github.com/envygeeks/jekyll-docker/blob/d567ca8e579ba0798a1a1137f3aab0fd06a75fb6/repos/jekyll/Dockerfile#L127-L129) are relevant:

```ruby
# Stops slow Nokogiri!
RUN gem install <%=@meta.gems %> -- \
  --use-system-libraries
```
