### ISSUE TITLE
Huge input lookup when parsing (SAX) 

### ISSUE THREAD

**Issue by juskoljo** [sparklemotion/nokogiri#2028]
Hi 

Apologies if this has been submitted already. I have problem parsing a big XML file that has ~20mb base64 encoded file attached. It seems that when parsing from IO and content has "\r\n" as line separators causes "Huge input lookup" error.

Reproduced "successfully" this with 1.10.9 and older versions

Thanks,
Jussi 

Example:

```ruby
#! /usr/bin/env ruby

# encoding: utf-8

require 'nokogiri'
require 'stringio'

template = <<-XML
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <something>value</something>
  <more>value</more>
  <boom>%s</boom>
</root>
XML

class Handler < Nokogiri::XML::SAX::Document
  def error(message)
    raise message
  end
end

parser = Nokogiri::XML::SAX::Parser.new(Handler.new)

# OK
xml = template % "#{'X' * 77}\n" * 300_000
parser.parse(xml)

# OK
xml = template % "#{'X' * 77}\r\n" * 300_000
parser.parse(xml)

# OK
xml = StringIO.new(template %  "#{'X' * 77}\n" * 400_000)
parser.parse(xml)

# internal error: Huge input lookup (RuntimeError)
xml = StringIO.new(template % "#{'X' * 77}\r\n" * 300_000)
parser.parse(xml)
```

**Environment**

```
# Nokogiri (1.10.9)
    ---
    warnings: []
    nokogiri: 1.10.9
    ruby:
      version: 2.6.5
      platform: x86_64-darwin18
      description: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/Users/jussi/.rvm/gems/ruby-2.6.5/gems/nokogiri-1.10.9/ports/x86_64-apple-darwin18.7.0/libxml2/2.9.10"
      libxslt_path: "/Users/jussi/.rvm/gems/ruby-2.6.5/gems/nokogiri-1.10.9/ports/x86_64-apple-darwin18.7.0/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10
```

**Comment by flavorjones** [comment]
@juskoljo Thanks for reporting, and sorry you're having a problem. I'll try to take a look later today.

**Comment by juskoljo** [comment]
Hi, any updates on this? 👍

**Comment by flavorjones** [comment]
@juskoljo Hi! Apologies for the slow response, it's been hard for me to find time to work on OSS recently.

I'm having difficulty reproducing what you're seeing, here's what I get using the script you provided:

```
Traceback (most recent call last):
	4: from /home/flavorjones/baz.rb:27:in `<main>'
	3: from /home/flavorjones/.rvm/gems/ruby-2.7.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/sax/parser.rb:83:in `parse'
	2: from /home/flavorjones/.rvm/gems/ruby-2.7.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/sax/parser.rb:110:in `parse_memory'
	1: from /home/flavorjones/.rvm/gems/ruby-2.7.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/sax/parser.rb:110:in `parse_with'
/home/flavorjones/baz.rb:19:in `error': XML declaration allowed only at the start of the document (RuntimeError)
```

This is because the generated XML has multiple XML declarations.

I took a few minutes to rewrite the script to avoid multiple decls (as well as multiple roots) and still can't reproduce. Here's what I did:

```ruby
#! /usr/bin/env ruby

# encoding: utf-8

require "nokogiri"
require "stringio"

start_xml = <<-XML
<?xml version="1.0" encoding="UTF-8"?>
<root>
XML

end_xml = <<-XML
</root>
XML

template = <<-XML
<node>
  <something>value</something>
  <more>value</more>
  <boom>%s</boom>
</node>
XML

class Handler < Nokogiri::XML::SAX::Document
  def error(message)
    raise message
  end
end

parser = Nokogiri::XML::SAX::Parser.new(Handler.new)

# OK
xml = start_xml + (template % "#{"X" * 77}\n" * 300_000) + end_xml
parser.parse(xml)
puts "ok"

# OK
xml = start_xml + (template % "#{"X" * 77}\r\n" * 300_000) + end_xml
parser.parse(xml)
puts "ok"

# OK
xml = StringIO.new(start_xml + (template % "#{"X" * 77}\n" * 400_000) + end_xml)
parser.parse(xml)
puts "ok"

# internal error: Huge input lookup (RuntimeError)
xml = StringIO.new(start_xml + (template % "#{"X" * 77}\r\n" * 300_000) + end_xml)
parser.parse(xml)
puts "ok"
```

which prints out four "ok"s.

Can you help me reproduce this? Or help me discover what I'm doing differently from you (or what's different about my system)?

My nokogiri is:

```
~ $ nokogiri -v
# Nokogiri (1.10.9)
    ---
    warnings: []
    nokogiri: 1.10.9
    ruby:
      version: 2.7.0
      platform: x86_64-linux
      description: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/flavorjones/.rvm/gems/ruby-2.7.0/gems/nokogiri-1.10.9/ports/x86_64-pc-linux-gnu/libxml2/2.9.10"
      libxslt_path: "/home/flavorjones/.rvm/gems/ruby-2.7.0/gems/nokogiri-1.10.9/ports/x86_64-pc-linux-gnu/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10
```

**Comment by juskoljo** [comment]
Hi @flavorjones 

No worries! :). You are right, the first script generated something that was not my intention... Note to myself: Never edit a script online while posting ;). Following script should reproduce the issue.

The script is simulating a scenario when there is a big XML node (base64 encoded file) with CR and/or LF after every 77 chars.  

```
# encoding: utf-8

require 'nokogiri'

template = <<-XML
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <something>value</something>
  <more>value</more>
  <boom>%s</boom>
</root>
XML

class Handler < Nokogiri::XML::SAX::Document
  def error(message)
    raise message
  end
end

parser = Nokogiri::XML::SAX::Parser.new(Handler.new)

# OK
xml = template % ("#{'X' * 77}\n" * 300_000)
parser.parse(xml)

# OK
xml = template % ("#{'X' * 77}\r\n" * 300_000)
parser.parse(xml)

# OK
xml = StringIO.new(template % ("#{'X' * 77}\n" * 400_000))
parser.parse(xml)

# internal error: Huge input lookup (RuntimeError)
xml = StringIO.new(template % ("#{'X' * 77}\r\n" * 300_000))
parser.parse(xml)
``` 

My nokogiri seem to be the same as yours except:

```
   ruby:
      version: 2.3.8
      platform: x86_64-darwin18
      description: ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-darwin18]
```
