### ISSUE TITLE
CSS case insensitive attribute selector operator

### ISSUE THREAD

**Issue by Juice10** [sparklemotion/nokogiri#2036]
**Describe the bug**

When using `.css(input[type=checkbox i]` Nokogiri kicks up an error: `Nokogiri::CSS::SyntaxError (unexpected ' ' after '[:equal, "checkbox"]')`

**To Reproduce**
```ruby
#! /usr/bin/env ruby

require 'nokogiri'
require 'minitest/autorun'

class Test < MiniTest::Spec
  describe "Node#css" do
    it "should find a div using chained classes" do
      html = <<~HEREDOC
        <html>
          <body>
            <input type="CHECKBOX" />
      HEREDOC
      
      doc = Nokogiri::HTML::Document.parse(html)
      
      assert_equal 1, doc.css("input[type=checkbox i]").length
    end
  end
end
```

**Expected behavior**

The `i` modifier should make the attribute selector case-insensitive.

**Environment**

```
# Nokogiri (1.10.9)
    ---
    warnings: []
    nokogiri: 1.10.9
    ruby:
      version: 2.7.1
      platform: x86_64-darwin19
      description: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
      engine: ruby
    libxml:
      binding: extension
      source: system
      compiled: 2.9.4
      loaded: 2.9.4
```

**Additional context**

More information on attribute selector operators: https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors
