### ISSUE TITLE
Nokogiri removing AMP html attribute

### ISSUE THREAD

**Issue by brian-kephart** [sparklemotion/nokogiri#2045]
**Describe the bug**

AMP uses a lightning bolt attribute on the HTML tag, which is required for validation. This attribute is removed by Nokogiri during parsing.

**To Reproduce**
```ruby
#! /usr/bin/env ruby

require 'nokogiri'
require 'minitest/autorun'

class Test < MiniTest::Spec
  describe "honors AMP HTML attribute" do
    it "should not remove the attribute" do
      html = "<!DOCTYPE html><html ⚡></html>"
      doc = Nokogiri::HTML::Document.parse html

      doc.to_html.must_match /<html ⚡>/
    end
  end
end
```

**Environment**
```
# Nokogiri (1.10.9)
    ---
    warnings: []
    nokogiri: 1.10.9
    ruby:
      version: 2.7.1
      platform: x86_64-darwin19
      description: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
      engine: ruby
    libxml:

      binding: extension
      source: packaged
      libxml2_path: "/Users/briankephart/.rvm/gems/ruby-2.7.1/gems/nokogiri-1.10.9/ports/x86_64-apple-darwin19.4.0/libxml2/2.9.10"
      libxslt_path: "/Users/briankephart/.rvm/gems/ruby-2.7.1/gems/nokogiri-1.10.9/ports/x86_64-apple-darwin19.4.0/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10
```
