### ISSUE TITLE
warning: calling URI.open via Kernel#open is deprecated

### ISSUE THREAD

**Issue by pfeifferj** [sparklemotion/nokogiri#2066]
**Describe the bug**

`Nokogiri::HTML(open('https://foo.bar'))` (cf. [nokogiri docs](https://nokogiri.org/tutorials/parsing_an_html_xml_document.html#from-the-internets)) results in error message `warning: calling URI.open via Kernel#open is
deprecated, call URI.open directly or use URI#open` after upgrading ruby version.

The same thing happens using `Nokogiri::XML`

Probably related to [this open-uri deprecation](https://bugs.ruby-lang.org/issues/15893)
I tried changing the line to `xml_doc = URI('https://foo.bar').open`, which (obviously) didn't work and also couldn't find a workaround for this.

**To Reproduce**

Excerpt of my rake task:

```
require 'rss'
require 'open-uri'
require 'nokogiri'
require 'pry'
namespace :sync do
  task feeds: [:environment] do
    Feed.all.each do |feeds|
      xml_doc = Nokogiri::HTML(open(feeds.url))
...
```

**Expected behavior**

The rake task worked normally before upgrading ruby from `2.6.3` to `2.7.1`

**Environment**

```
# Nokogiri (1.10.10)
    ---
    warnings: []
    nokogiri: 1.10.10
    ruby:
      version: 2.7.1
      platform: x86_64-linux
      description: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/pfeifferj/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/nokogiri-1.10.10/ports/x86_64-pc-linux-gnu/libxml2/2.9.10"
      libxslt_path: "/home/pfeifferj/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/nokogiri-1.10.10/ports/x86_64-pc-linux-gnu/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10
```
