### ISSUE TITLE
[help] Nokogiri xpath without root element

### ISSUE THREAD

**Issue by sean-yeoh** [sparklemotion/nokogiri#2091]
Hi guys, I'm not too sure where to ask for help so I'm trying my luck here. Please feel free to close this and direct me to a proper channel if there's one. Thanks!

**To Reproduce**
I'm trying to query the xml partial string below in the variable `text`. It's in Open XML format. When I tried to query it without adding a root element, I get the `Undefined namespace prefix` error.
```ruby
text = "<w:p>"\
          "<w:r>"\
            "<w:t xml:space=\"preserve\"></w:t>"\
          "</w:r>"\
          "<w:hyperlink r:id=\"https://facebook.com\" w:history=\"1\">"\
            "<w:r>"\
              "<w:rPr>"\
                "<w:rStyle w:val=\"Hyperlink\"/>"\
              "</w:rPr>"\
              "<w:t>Facebook</w:t>"\
            "</w:r>"\
          "</w:hyperlink>"\
          "<w:r>"\
            "<w:t xml:space=\"preserve\"></w:t>"\
          "</w:r>"\
        "</w:p>"

xml = Nokogiri::XML(text)
xml.xpath('//w:hyperlink') # => Nokogiri::XML::XPath::SyntaxError: ERROR: Undefined namespace prefix: //w:hyperlink
```
I then tried adding a root element and adding namespaces manually. It doesn't raise an error now but It's returning an empty array.

```ruby
require 'nokogiri'

text = "<w:p>"\
          "<w:r>"\
            "<w:t xml:space=\"preserve\"></w:t>"\
          "</w:r>"\
          "<w:hyperlink r:id=\"https://facebook.com\" w:history=\"1\">"\
            "<w:r>"\
              "<w:rPr>"\
                "<w:rStyle w:val=\"Hyperlink\"/>"\
              "</w:rPr>"\
              "<w:t>Facebook</w:t>"\
            "</w:r>"\
          "</w:hyperlink>"\
          "<w:r>"\
            "<w:t xml:space=\"preserve\"></w:t>"\
          "</w:r>"\
        "</w:p>"

xml_namespaces = [
  { aink: 'http://schemas.microsoft.com/office/drawing/2016/ink' },
  { am3d: 'http://schemas.microsoft.com/office/drawing/2017/model3d' },
  { cx: 'http://schemas.microsoft.com/office/drawing/2014/chartex' },
  { cx1: 'http://schemas.microsoft.com/office/drawing/2015/9/8/chartex' },
  { cx2: 'http://schemas.microsoft.com/office/drawing/2015/10/21/chartex' },
  { cx3: 'http://schemas.microsoft.com/office/drawing/2016/5/9/chartex' },
  { cx4: 'http://schemas.microsoft.com/office/drawing/2016/5/10/chartex' },
  { cx5: 'http://schemas.microsoft.com/office/drawing/2016/5/11/chartex' },
  { cx6: 'http://schemas.microsoft.com/office/drawing/2016/5/12/chartex' },
  { cx7: 'http://schemas.microsoft.com/office/drawing/2016/5/13/chartex' },
  { cx8: 'http://schemas.microsoft.com/office/drawing/2016/5/14/chartex' },
  { m: 'http://schemas.openxmlformats.org/officeDocument/2006/math' },
  { mc: 'http://schemas.openxmlformats.org/markup-compatibility/2006' },
  { o: 'urn:schemas-microsoft-com:office:office' },
  { r: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships' },
  { v: 'urn:schemas-microsoft-com:vml' },
  { w: 'http://schemas.openxmlformats.org/wordprocessingml/2006/main' },
  { w10: 'urn:schemas-microsoft-com:office:word' },
  { w14: 'http://schemas.microsoft.com/office/word/2010/wordml' },
  { w15: 'http://schemas.microsoft.com/office/word/2012/wordml' },
  { w16: 'http://schemas.microsoft.com/office/word/2018/wordml' },
  { w16cex: 'http://schemas.microsoft.com/office/word/2018/wordml/cex' },
  { w16cid: 'http://schemas.microsoft.com/office/word/2016/wordml/cid' },
  { w16se: 'http://schemas.microsoft.com/office/word/2015/wordml/symex' },
  { wne: 'http://schemas.microsoft.com/office/word/2006/wordml' },
  { wp: 'http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing' },
  { wp14: 'http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing' },
  { wpc: 'http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas' },
  { wpg: 'http://schemas.microsoft.com/office/word/2010/wordprocessingGroup' },
  { wpi: 'http://schemas.microsoft.com/office/word/2010/wordprocessingInk' },
  { wps: 'http://schemas.microsoft.com/office/word/2010/wordprocessingShape' }
]

xml = Nokogiri::XML("<w:root>#{text}</w:root>")
xml_namespaces.each do |namespace|
  xml.root.add_namespace_definition(namespace.keys[0].to_s, namespace.values[0].to_s) 
end

xml.xpath('//w:hyperlink') # => []
```
I would like to find all `<w:hyperlink>` nodes within a xml partial.

**Expected behavior**
It should return the `<w:hyperlink>` node.

**Environment**

Please paste the output from `nokogiri -v` here, escaped by triple-backtick.
```
# Nokogiri (1.10.10)
    ---
    warnings: []
    nokogiri: 1.10.10
    ruby:
      version: 2.4.1
      platform: x86_64-linux
      description: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/sean/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10/ports/x86_64-pc-linux-gnu/libxml2/2.9.10"
      libxslt_path: "/home/sean/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10/ports/x86_64-pc-linux-gnu/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10
```
This output will tell us what version of Ruby you're using, how you installed nokogiri, what versions of the underlying libraries you're using, and what operating you're using.

**Additional context**
