### ISSUE TITLE
Unable to output the HTML::Document in the original encoding

### ISSUE THREAD

**Issue by romanbsd** [sparklemotion/nokogiri#215]
Consider this scenario:

```
require 'open-uri'
require 'nokogiri'
puts Nokogiri::VERSION_INFO
puts Nokogiri::LIBXML_ICONV_ENABLED
f = open('http://www.hometheater.co.il/').read; true
puts f.encoding.to_s
p = Nokogiri::HTML(f); true
puts p.encoding
puts p.meta_encoding
p.to_html
```

Result:
```
{"warnings"=>[], "nokogiri"=>"1.4.1", "libxml"=>{"binding"=>"extension", "compiled"=>"2.7.6", "loaded"=>"2.7.6"}}
true
ASCII-8BIT
windows-1255
windows-1255
encoding error : output conversion failed due to conv error, bytes 0xEE 0xD7 0x92 0xD7
I/O error : encoder error
```

So it effectively prohibits me from outputting this page in the original "windows-1255" encoding.

**Comment by flavorjones** [comment]
This appears to be fine now, with iconv 2.23 and

```
# Nokogiri (1.7.0.1)
    ---
    warnings: []
    nokogiri: 1.7.0.1
    ruby:
      version: 2.4.0
      platform: x86_64-linux
      description: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/flavorjones/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.7.0.1/ports/x86_64-pc-linux-gnu/libxml2/2.9.4"
      libxslt_path: "/home/flavorjones/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.7.0.1/ports/x86_64-pc-linux-gnu/libxslt/1.1.29"
      libxml2_patches: []
      libxslt_patches: []
      compiled: 2.9.4
      loaded: 2.9.4
```

If this is still an issue for you, please comment and we'll reopen.
