### ISSUE TITLE
[bug] Some HTML character entities get escaped when they shouldn't.

### ISSUE THREAD

**Issue by Biep** [sparklemotion/nokogiri#2159]
**Please describe the bug**

When parsing HTML using `Nokogiri::HTML.parse`, HTML character entities get treated inconsistently.  What I want is for them to remain untouched.  Instead, some are replaced by the characters they represent (so `&loz;` is replaced by `◊`), whereas others get the ampersand escaped (so `&square;` is replaced by `&amp;square;`).  The former is for my goals acceptable, but the latter isn't.

**Help us reproduce what you're seeing**
```
irb
require 'nokogiri'
Nokogiri::HTML.parse("<p>A &square; is not a &loz;.</p>").children[1].children[0].children[0].children[0].text
```
The output shows as `"A &square; is not a ◊."`.  In web page sources, it shows as `A &amp;square; is not a ◊.`
The correct web page source output would be `A &square; is not a &loz;.`.

Here is another example:
```
irb(main):004:0> print Nokogiri::HTML.parse('<p>&curarr;</p>')
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p>&amp;curarr;</p></body></html>
```
Where it says `&amp;curarr;` it should just say `&curarr`.

**Environment**

```
# Nokogiri (1.10.10)
    ---
    warnings: []
    nokogiri: 1.10.10
    ruby:
      version: 2.7.0
      platform: x86_64-linux-gnu
      description: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/var/lib/gems/2.7.0/gems/nokogiri-1.10.10/ports/x86_64-pc-linux-gnu/libxml2/2.9.10"
      libxslt_path: "/var/lib/gems/2.7.0/gems/nokogiri-1.10.10/ports/x86_64-pc-linux-gnu/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10
```
