### ISSUE TITLE
[bug] dl structures parsed incorrectly if a dt has no dd.

### ISSUE THREAD

**Issue by Biep** [sparklemotion/nokogiri#2160]
**Please describe the bug**

Nokogiri::HTML.parse doesn't close `dt` tags when encountering the next `dt` tag.  So if some list entries have no `dd`, the structure ends up wrong.

**Help us reproduce what you're seeing**
```
irb(main):003:0> print Nokogiri::HTML.parse('<dl><dt>1<dt>2<dt>3</dl>')
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><dl><dt>1<dt>2<dt>3</dt>
</dt>
</dt></dl></body></html>
```

**Expected behavior**

The correct structure would be
```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><dl><dt>1</dt>
<dt>2</dt>
<dt>3</dt>
</dl></body></html>

```

**Environment**

```
# Nokogiri (1.10.10)
    ---
    warnings: []
    nokogiri: 1.10.10
    ruby:
      version: 2.7.0
      platform: x86_64-linux-gnu
      description: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/var/lib/gems/2.7.0/gems/nokogiri-1.10.10/ports/x86_64-pc-linux-gnu/libxml2/2.9.10"
      libxslt_path: "/var/lib/gems/2.7.0/gems/nokogiri-1.10.10/ports/x86_64-pc-linux-gnu/libxslt/1.1.34"
      libxml2_patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      libxslt_patches: []
      compiled: 2.9.10
      loaded: 2.9.10
```
