### ISSUE TITLE
[bug] Very long lines (or maybe very long attributes?) are silently corrupted, on parsing and immediately saving file

### ISSUE THREAD

**Issue by matkoniecz** [sparklemotion/nokogiri#2201]
**Please describe the bug**

Very long lines (or maybe very long attributes?) are silently corrupted, on parsing and immediately saving file.

 `"/>` at end of element with long attribute is turned into `"/&gt;`

**Help us reproduce what you're seeing**

```ruby
require 'nokogiri'

text = File.open('bug.svg').read
svg_merged = Nokogiri::XML(text, &:noblanks)
code = svg_merged.to_xml(indent:3, indent_text:" ")
code_not_pretty = svg_merged.to_xml()
puts text[-26..-10]
puts code[-26..-10]
puts code_not_pretty[-26..-10]
```
To run this code with data triggering it at least on my computer:

```
git clone https://github.com/matkoniecz/nokogiri_testcase.git
cd nokogiri_testcase
ruby bug.rb
```

Expected output that demonstrates bug (note `"/>` vs `"/&gt;`):

```
2.75 355.79"/>
</
 355.79"/&gt;
</g
 355.79"/&gt;
</g

```
There is also sample file not triggering it. In general once line is less outrageously long, corruption is disappearing.

**Expected behavior**

No corruption or at least a crash rather than a silent corruption of data.

**Environment**

```
# Nokogiri (1.11.1)
    ---
    warnings: []
    nokogiri:
      version: 1.11.1
      cppflags:
      - "-I/home/mateusz/.gem/ruby/2.7.0/gems/nokogiri-1.11.1-x86_64-linux/ext/nokogiri"
      - "-I/home/mateusz/.gem/ruby/2.7.0/gems/nokogiri-1.11.1-x86_64-linux/ext/nokogiri/include"
      - "-I/home/mateusz/.gem/ruby/2.7.0/gems/nokogiri-1.11.1-x86_64-linux/ext/nokogiri/include/libxml2"
    ruby:
      version: 2.7.0
      platform: x86_64-linux-gnu
      gem_platform: x86_64-linux
      description: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      - 0006-htmlParseComment-treat-as-if-it-closed-the-comment.patch
      - 0007-use-new-htmlParseLookupCommentEnd-to-find-comment-en.patch
      - '0008-use-glibc-strlen.patch'
      - '0009-avoid-isnan-isinf.patch'
      libxml2_path: "/home/mateusz/.gem/ruby/2.7.0/gems/nokogiri-1.11.1-x86_64-linux/ext/nokogiri"
      iconv_enabled: true
      compiled: 2.9.10
      loaded: 2.9.10
    libxslt:
      source: packaged
      precompiled: true
      patches: []
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      zlib: 1.2.11
```

**Additional context**

It is file from actual use, not some deliberately silly attempt.

I have taken ocean data from OpenStreetMap, converted to geojson and later generated SVG.

I am trying to use nokogiri to merge this SVG file with another parts of the map (as one of final steps toward burning this map on wood using laser cutter).

Lubuntu Image Viewer also refuses to work with this file, but at least clearly crashes

> XML parse error: Error domain 1 code 73 on line 4 column 10000011 of data: Couldn't find end of Start Tag path line 4

Inkscape opens both files without complaints.

For my use case I would be fine with crash (simplifying data input was on my todo list anyway, 10MB in one line is quite weird), but silent data corruption is irritating. Though supporting such input would be probably nice.
