### ISSUE TITLE
[bug] [jruby] Java ClassCastException exposed; not wrapped in Ruby Exception

### ISSUE THREAD

**Issue by byteit101** [sparklemotion/nokogiri#2211]
**Actual Behavior**

```
jruby-9.2.7.0 :001 > require 'nokogiri'
 => true 
jruby-9.2.7.0 :002 > Nokogiri::HTML.parse("<p>").css("p")["class"]
Traceback (most recent call last):
            <...snip>
        3: from nokogiri.XmlNodeSet$INVOKER$i$slice.call(XmlNodeSet$INVOKER$i$slice.gen)
        2: from nokogiri.XmlNodeSet.slice(XmlNodeSet.java:356)
        1: from nokogiri.XmlNodeSet.rangeBeginLength(XmlNodeSet.java:314)
Java::JavaLang::ClassCastException (org.jruby.RubyString cannot be cast to org.jruby.RubyRange)
jruby-9.2.7.0 :003 > 
```
I'm aware the correct syntax is `Nokogiri::HTML.parse("<p>").css("p").first["class"]`. This bug report is about an error in the error :-)

**Expected behavior**

If there is an exception, it is a Ruby Exception, not a Java Exception, as shown on MRI:

```
2.6.2 :001 > require 'nokogiri'
 => true 
2.6.2 :002 > Nokogiri::HTML.parse("<p>").css("p")["class"]
Traceback (most recent call last):
            <...snip>
        2: from (irb):2
        1: from (irb):2:in `[]'
TypeError (no implicit conversion of String into Integer)
2.6.2 :003 > 

```

**Environment**

```
# Nokogiri (1.11.2)
    ---
    warnings: []
    nokogiri:
      version: 1.11.2
    ruby:
      version: 2.5.3
      platform: java
      gem_platform: universal-java-1.8
      description: jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 Java HotSpot(TM) 64-Bit Server
        VM 25.201-b09 on 1.8.0_201-b09 +jit [linux-x86_64]
      engine: jruby
      jruby: 9.2.7.0
    other_libraries:
      xerces: Xerces-J 2.12.0
      nekohtml: NekoHTML 1.9.21
```
