### ISSUE TITLE
[bug] Nokogiri::XML::SyntaxError when parsing <img> tag with 2+ query parameters

### ISSUE THREAD

**Issue by halgorithm** [sparklemotion/nokogiri#2219]
**Please describe the bug**
It appears Nokogiri's HTML parser returns parse errors for valid img tags with src urls that contain two or more query parameters.

**Help us reproduce what you're seeing**
Open irb and run the following script. Observe that parsing `one_qp` does not produce any errors, whereas parsing `two_qp` does.

```ruby
one_qp = "<img src='https://example.com?a=1' />"
Nokogiri::HTML.parse(one_qp).errors # []
two_qp = "<img src='https://example.com?a=1&b=2' />"
Nokogiri::HTML.parse(two_qp).errors # [#<Nokogiri::XML::SyntaxError: 1:36: ERROR: htmlParseEntityRef: expecting ';'>]
```

**Expected behavior**
Parsing a string containing a single image tag with two query parameters should not return any errors.

**Environment**
```
# Nokogiri (1.11.3)
    ---
    warnings: []
    nokogiri:
      version: 1.11.3
      cppflags:
      - "-I/Users/hal/.gem/gems/nokogiri-1.11.3-x86_64-darwin/ext/nokogiri"
      - "-I/Users/hal/.gem/gems/nokogiri-1.11.3-x86_64-darwin/ext/nokogiri/include"
      - "-I/Users/hal/.gem/gems/nokogiri-1.11.3-x86_64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.6.5
      platform: x86_64-darwin19
      gem_platform: x86_64-darwin-19
      description: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
      - 0002-Remove-script-macro-support.patch
      - 0003-Update-entities-to-remove-handling-of-ssi.patch
      - 0004-libxml2.la-is-in-top_builddir.patch
      - 0005-Fix-infinite-loop-in-xmlStringLenDecodeEntities.patch
      - 0006-htmlParseComment-treat-as-if-it-closed-the-comment.patch
      - 0007-use-new-htmlParseLookupCommentEnd-to-find-comment-en.patch
      - '0008-use-glibc-strlen.patch'
      - '0009-avoid-isnan-isinf.patch'
      - 0010-parser.c-shrink-the-input-buffer-when-appropriate.patch
      - 0011-update-automake-files-for-arm64.patch
      libxml2_path: "/Users/hal/.gem/gems/nokogiri-1.11.3-x86_64-darwin/ext/nokogiri"
      iconv_enabled: true
      compiled: 2.9.10
      loaded: 2.9.10
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      zlib: 1.2.11
      libiconv: '1.15'
```
