### ISSUE TITLE
[bug] Nokogiri::HTML::DocumentFragment#path causes a segmentation fault

### ISSUE THREAD

**Issue by cbeer** [sparklemotion/nokogiri#2250]
**Please describe the bug**

Nokogiri 1.11.4+ segfaults when you call `path` on a Nokogiri::HTML::DocumentFragment.

```

a.rb:14: [BUG] Segmentation fault at 0x0000000000000000
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]

-- Control frame information -----------------------------------------------
c:0024 p:---- s:0131 e:000130 CFUNC  :path
c:0023 p:0031 s:0127 e:000124 BLOCK  a.rb:14 [FINISH]
....
```

**Help us reproduce what you're seeing**

```ruby
#! /usr/bin/env ruby

require 'nokogiri'
require 'minitest/autorun'

class Test < MiniTest::Spec
  describe "Nokogiri::HTML::DocumentFragment#path" do
    it "should return the expected value" do
      html = <<~HEREDOC
        <div></div>
      HEREDOC

      fragment = Nokogiri::HTML.fragment(html)
      assert_equal "?", fragment.path
    end
  end
end
```

**Expected behavior**

Nokogiri 1.11.3 and below returned `?` (as does Nokogiri::XML::DocumentFragment#path), but 1.11.4 and 1.11.5 both segfault.

**Environment**

```
# Nokogiri (1.11.5)
    ---
    warnings: []
    nokogiri:
      version: 1.11.5
      cppflags:
      - "-I/Users/cabeer/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/nokogiri-1.11.5/ext/nokogiri"
      - "-I/Users/cabeer/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/nokogiri-1.11.5/ext/nokogiri/include"
      - "-I/Users/cabeer/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/nokogiri-1.11.5/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.0.0
      platform: x86_64-darwin19
      gem_platform: x86_64-darwin-19
      description: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
      engine: ruby
    libxml:
      source: packaged
      precompiled: false
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      libxml2_path: "/Users/cabeer/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/nokogiri-1.11.5/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: false
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries: {}
```

**Additional context**

Initially reported to https://github.com/teamcapybara/capybara/issues/2466.
