### ISSUE TITLE
[install] Bundler platform and mini_portile2

### ISSUE THREAD

**Issue by tmaier** [sparklemotion/nokogiri#2286]
## Background

Heroku recommends to set in bundler the platform to `ruby` and `x86_64-linux`. (See related [Heroku documentation](https://devcenter.heroku.com/articles/bundler-version#bundler-2-2-3))

When doing so, the `Gemfile.lock` gets updated and has now the following entries

```
GEM
  remote: https://rubygems.org/
  specs:
    nokogiri (1.11.7)
      mini_portile2 (~> 2.5.0)
      racc (~> 1.4)
    nokogiri (1.11.7-x86_64-linux)
      racc (~> 1.4)

PLATFORMS
  ruby
  x86_64-linux

RUBY VERSION
   ruby 2.7.4p191

BUNDLED WITH
   2.2.21
```

New is the second platform `x86_64-linux` and the second entry for `nokogiri (1.11.7-x86_64-linux)`
Note that the second entry does not refer to `mini_portile2` anymore.

This leads to the following error message when running the application

```
/usr/local/bundle/gems/bundler-2.2.21/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find mini_portile2-2.5.3 in any of the sources (Bundler::GemNotFound)
246	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/spec_set.rb:90:in `map!'
247	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/spec_set.rb:90:in `materialize'
248	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/definition.rb:191:in `specs'
249	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/definition.rb:260:in `specs_for'
250	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/definition.rb:242:in `requested_specs'
251	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/runtime.rb:91:in `block in definition_method'
252	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/runtime.rb:20:in `setup'
253	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler.rb:149:in `setup'
254	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/setup.rb:20:in `block in <top (required)>'
255	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/ui/shell.rb:136:in `with_level'
256	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/ui/shell.rb:88:in `silence'
257	from /usr/local/bundle/gems/bundler-2.2.21/lib/bundler/setup.rb:20:in `<top (required)>'
258	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
259	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
260	from /usr/src/app/config/boot.rb:5:in `<top (required)>'
261	from bin/rails:3:in `require_relative'
262	from bin/rails:3:in `<main>'
263
```

The following focuses now on `gem install`, where a similar behaviour can be seen.
But to be honest, I don't know how Bundler handles the two platforms configured...

## Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?

- [x] Yes!

### with `platform=x86_64-linux`
```
# gem install nokogiri --platform=x86_64-linux
Fetching nokogiri-1.11.7-x86_64-linux.gem
Successfully installed nokogiri-1.11.7-x86_64-linux
1 gem installed
```

### with `platform=ruby `

```
gem install nokogiri --platform=ruby
Fetching mini_portile2-2.5.3.gem
Fetching nokogiri-1.11.7.gem
Successfully installed mini_portile2-2.5.3
Building native extensions. This could take a while...
Successfully installed nokogiri-1.11.7
2 gems installed
```

### with `platform=x86_64-linux`

```
# Nokogiri (1.11.7)
    ---
    warnings: []
    nokogiri:
      version: 1.11.7
      cppflags:
      - "-I/usr/local/bundle/gems/nokogiri-1.11.7-x86_64-linux/ext/nokogiri"
      - "-I/usr/local/bundle/gems/nokogiri-1.11.7-x86_64-linux/ext/nokogiri/include"
      - "-I/usr/local/bundle/gems/nokogiri-1.11.7-x86_64-linux/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.7.4
      platform: x86_64-linux-musl
      gem_platform: x86_64-linux-musl
      description: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-musl]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      libxml2_path: "/usr/local/bundle/gems/nokogiri-1.11.7-x86_64-linux/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      zlib: 1.2.11
```

### with `platform=ruby `

```
# nokogiri -v
# Nokogiri (1.11.7)
    ---
    warnings: []
    nokogiri:
      version: 1.11.7
      cppflags:
      - "-I/usr/local/bundle/gems/nokogiri-1.11.7/ext/nokogiri"
      - "-I/usr/local/bundle/gems/nokogiri-1.11.7/ext/nokogiri/include"
      - "-I/usr/local/bundle/gems/nokogiri-1.11.7/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.7.4
      platform: x86_64-linux-musl
      gem_platform: x86_64-linux-musl
      description: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-musl]
      engine: ruby
    libxml:
      source: packaged
      precompiled: false
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      libxml2_path: "/usr/local/bundle/gems/nokogiri-1.11.7/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: false
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries: {}
```

## Tell us about your system!

What is the output from `ruby -v`? `ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-musl]`

What is the output from `gem -v`? `3.1.6`

What is the output from `gem env`?

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.6
  - RUBY VERSION: 2.7.4 (2021-07-07 patchlevel 191) [x86_64-linux-musl]
  - INSTALLATION DIRECTORY: /usr/local/bundle
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /usr/local/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/bundle/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux-musl
  - GEM PATHS:
     - /usr/local/bundle
     - /root/.gem/ruby/2.7.0
     - /usr/local/lib/ruby/gems/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-document"
     - "update" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /root/.vscode-server/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/bin
     - /usr/local/bin/adr-tools-3.0.0/src
     - /usr/src/app/bin
     - /usr/local/bundle/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
```

If you're using Bundler:
- what is the output from `bundle version`? `Bundler version 2.2.21 (2021-06-23 commit 0b5db72094)`
- what is the output from `bundle config`? (Take care to redact any credentials)

```
Settings are listed in order of priority. The top value will be used.
app_config
Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"

build.ffi
Set for the current user (/root/.bundle/config): "--enable-system-libffi"

build.nokogiri
Set for the current user (/root/.bundle/config): "--use-system-libraries"

gemfile
Set via BUNDLE_GEMFILE: "/usr/src/app/Gemfile"

jobs
Set for your local app (/usr/local/bundle/config): 6

silence_root_warning
```

- output of `bundle platform`

```
Your platform is: x86_64-linux-musl

Your app has gems that work on these platforms:
* ruby
* x86_64-linux

Your Gemfile specifies a Ruby version requirement:
* ruby 2.7.4p191
```

If Linux or a BSD variant, please note:
- the distro you're using `Alpine 3.13` with Docker image `ruby:2.7-alpine3.13`
- the output of `uname -a`: `Linux 040486625b79 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 Linux`
- the contents of `/etc/lsb-release`: File does not exist
