### ISSUE TITLE
[bug] Possible regression in XML generation

### ISSUE THREAD

**Issue by mscrivo** [sparklemotion/nokogiri#2317]
**Please describe the bug**

We use the [Viewpoint gem](https://github.com/WinRb/Viewpoint) to communicate with on-prem & office 365 exchange instances. The Viewpoint gem has a dependency on nokogiri and appears to use both the Nokogiri::XML and Nokogiri::XML:SAX namespaces in its code. After upgrading our version of nokogiri from 1.11.7 to 1.12, all integrations with exchange servers broke with a non-helpful SOAP XML error. I did a little testing of what the XML generated looks like between the 1.11.7 version and 1.12 and it looks like this:

1.11.7:
```xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">
  <soap:Header>
    <t:RequestServerVersion Version="Exchange2010"/>
  </soap:Header>
  <soap:Body>
    <SyncFolderHierarchy xmlns="http://schemas.microsoft.com/exchange/services/2006/messages">
      <FolderShape>
        <t:BaseShape>Default</t:BaseShape>
      </FolderShape>
    </SyncFolderHierarchy>
  </soap:Body>
</soap:Envelope>
```

1.12+:
```xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">
  <Header>
    <t:RequestServerVersion Version="Exchange2010"/>
  </Header>
  <Body>
    <SyncFolderHierarchy xmlns="http://schemas.microsoft.com/exchange/services/2006/messages">
      <FolderShape>
        <t:BaseShape>Default</t:BaseShape>
      </FolderShape>
    </SyncFolderHierarchy>
  </Body>
</soap:Envelope>
```

Both are valid XML, but notice how the new one does not have any namespace prefix on the Header, Body, etc. I don't know the XML spec that well, but this [page](http://books.xmlschemata.org/relaxng/relax-CHP-11-SECT-1.html) seems to indicate that unless your parent has a default namespace (in this case Envelope doesn't), then the child elements don't inherit it and are thus unnamespaced?

I believe the issue was introduced with this commit: https://github.com/sparklemotion/nokogiri/pull/2230/commits/cd6941fff5320b2b9ba1ff9154d74c096448d5fb

**Help us reproduce what you're seeing**

reproducing requires access to an exchange server, but the XML output above should suffice to show the problem

**Expected behavior**

The XML generated should properly follow the spec, or how the spec has been adapted in the wild. It's entirely possible that the issue here is with the Viewpoint code since it's quite old and hasn't been updated, or how Exchange is interpreting the XML, I'm not sure, but since it broke with this upgrade, I'd figure this would be a good place to start just in case there was a regression in the aforementioned commit.

**Environment**

```
# Nokogiri (1.12.3)
    ---
    warnings: []
    nokogiri:
      version: 1.12.3
      cppflags:
      - "-I/Users/michaelscrivo/affinity/vendor/bundle/ruby/3.0.0/gems/nokogiri-1.12.3-x86_64-darwin/ext/nokogiri"
      - "-I/Users/michaelscrivo/affinity/vendor/bundle/ruby/3.0.0/gems/nokogiri-1.12.3-x86_64-darwin/ext/nokogiri/include"
      - "-I/Users/michaelscrivo/affinity/vendor/bundle/ruby/3.0.0/gems/nokogiri-1.12.3-x86_64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.0.2
      platform: x86_64-darwin20
      gem_platform: x86_64-darwin-20
      description: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      libxml2_path: "/Users/michaelscrivo/affinity/vendor/bundle/ruby/3.0.0/gems/nokogiri-1.12.3-x86_64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      datetime_enabled: true
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      zlib: 1.2.11
      libiconv: '1.15'
      libgumbo: 1.0.0-nokogiri
```
