### ISSUE TITLE
XPath OR is 5-30% faster than union depending on number of CSS selectors

### ISSUE THREAD

**Issue by ilyazub** [sparklemotion/nokogiri#2323]
[`Nokogiri::Searcheable#css`](https://github.com/sparklemotion/nokogiri/blob/b2645bc2ff9dad3f8070adb2117c035dfa80bbb9/lib/nokogiri/xml/searchable.rb#L212-L218) uses `Nokogiri::CSS.xpath_query_from_css_rule` which joins XPaths using unions. Manually converted union to OR speeds up execution by 5-30%.

Union is different from OR in XPath but for my tests it results in the same set of nodes.

<details><summary>Benchmark results</summary>

**Small HTML file**

```
$ ruby slow_parsing_benchmark.rb
Searching 2545 nodes
Warming up --------------------------------------
 container: XPath OR    21.000  i/100ms
      container: CSS    20.000  i/100ms
container: XPath union
                        20.000  i/100ms
Calculating -------------------------------------
 container: XPath OR    217.863  (± 1.8%) i/s -      1.092k in   5.013857s
      container: CSS    207.020  (± 1.0%) i/s -      1.040k in   5.024347s
container: XPath union
                        208.429  (± 1.4%) i/s -      1.060k in   5.086638s

Comparison:
 container: XPath OR:      217.9 i/s
container: XPath union:      208.4 i/s - 1.05x  (± 0.00) slower
      container: CSS:      207.0 i/s - 1.05x  (± 0.00) slower

Warming up --------------------------------------
 selector1: XPath OR    20.000  i/100ms
      selector1: CSS    13.000  i/100ms
selector1: XPath union
                        10.000  i/100ms
Calculating -------------------------------------
 selector1: XPath OR    209.189  (± 1.4%) i/s -      1.060k in   5.068393s
      selector1: CSS    159.103  (± 5.0%) i/s -    793.000  in   5.000679s
selector1: XPath union
                        162.034  (± 3.1%) i/s -    810.000  in   5.003069s

Comparison:
 selector1: XPath OR:      209.2 i/s
selector1: XPath union:      162.0 i/s - 1.29x  (± 0.00) slower
      selector1: CSS:      159.1 i/s - 1.31x  (± 0.00) slower
```

**Big HTML file**

```
$ ruby slow_parsing_benchmark.rb

Searching 7786 nodes
Warming up --------------------------------------
 container: XPath OR     7.000  i/100ms
      container: CSS     6.000  i/100ms
container: XPath union
                         6.000  i/100ms
Calculating -------------------------------------
 container: XPath OR     71.807  (± 1.4%) i/s -    364.000  in   5.071297s
      container: CSS     68.182  (± 2.9%) i/s -    342.000  in   5.018614s
container: XPath union
                         68.755  (± 1.5%) i/s -    348.000  in   5.061887s

Comparison:
 container: XPath OR:       71.8 i/s
container: XPath union:       68.8 i/s - 1.04x  (± 0.00) slower
      container: CSS:       68.2 i/s - 1.05x  (± 0.00) slower

Warming up --------------------------------------
 selector1: XPath OR     6.000  i/100ms
 selector1: CSS     5.000  i/100ms
 selector1: XPath union
                         5.000  i/100ms
Calculating -------------------------------------
 selector1: XPath OR     68.351  (± 2.9%) i/s -    342.000  in   5.010494s
      selector1: CSS     53.403  (± 5.6%) i/s -    270.000  in   5.070224s
selector1: XPath union
                         54.080  (± 1.8%) i/s -    275.000  in   5.086061s

Comparison:
 selector1: XPath OR:       68.4 i/s
selector1: XPath union:       54.1 i/s - 1.26x  (± 0.00) slower
      selector1: CSS:       53.4 i/s - 1.28x  (± 0.00) slower
```

</details>

<details><summary>Benchmark code</summary>

```ruby
# frozen_string_literal: true

gem "benchmark-ips"
require "benchmark/ips"

gem "nokogiri"
require "nokogiri"

html = File.read("tmp/pc_game_big_shopping.html")

doc = Nokogiri::HTML5.parse(html)

puts "Searching #{doc.css("*").length} nodes"

Benchmark.ips do |x|
  x.report("container: XPath OR") { doc.xpath(".//*[nokogiri-builtin:css-class(@class,'sh-dlr__list-result') or nokogiri-builtin:css-class(@class,'sh-dgr__grid-result')]") }
  x.report("container: CSS") { doc.css(".sh-dlr__list-result, .sh-dgr__grid-result") }
  x.report("container: XPath union") { doc.xpath(".//*[nokogiri-builtin:css-class(@class,'sh-dlr__list-result')] | .//*[nokogiri-builtin:css-class(@class,'sh-dgr__grid-result')]") }

  x.compare!
end

Benchmark.ips do |x|
  x.report("selector1: XPath OR") { doc.xpath(".//*[nokogiri-builtin:css-class(@class,'eIuuYe')]//a | .//a[nokogiri-builtin:css-class(@class,'EI11Pd') or nokogiri-builtin:css-class(@class,'AGVhpb') or nokogiri-builtin:css-class(@class,'GyDBsd') or nokogiri-builtin:css-class(@class,'VQN8fd') or nokogiri-builtin:css-class(@class,'VZTCjd') or nokogiri-builtin:css-class(@class,'REX1ub') or nokogiri-builtin:css-class(@class,'sHaywe') or nokogiri-builtin:css-class(@class,'eaGTj')]") }
  x.report("selector1: CSS") { doc.css(".eIuuYe a, a.EI11Pd, a.AGVhpb, a.GyDBsd, a.VQN8fd, a.VZTCjd, a.REX1ub, a.sHaywe, a.eaGTj") }
  x.report("selector1: XPath union") { doc.xpath(".//*[nokogiri-builtin:css-class(@class,'eIuuYe')]//a | .//a[nokogiri-builtin:css-class(@class,'EI11Pd')] | .//a[nokogiri-builtin:css-class(@class,'AGVhpb')] | .//a[nokogiri-builtin:css-class(@class,'GyDBsd')] | .//a[nokogiri-builtin:css-class(@class,'VQN8fd')] | .//a[nokogiri-builtin:css-class(@class,'VZTCjd')] | .//a[nokogiri-builtin:css-class(@class,'REX1ub')] | .//a[nokogiri-builtin:css-class(@class,'sHaywe')] | .//a[nokogiri-builtin:css-class(@class,'eaGTj')]") }

  x.compare!
end
```

[File used for the benchmark.html.gz](https://github.com/sparklemotion/nokogiri/files/7098196/pc_game_big_shopping.html.gz)

</details>

Compare XPath query from `Nokogiri::CSS.xpath_query_from_css_rule` and manually converted version:

```ruby
# Manually converted to 'or'
.//*[nokogiri-builtin:css-class(@class,'eIuuYe')]//a | .//a[nokogiri-builtin:css-class(@class,'EI11Pd') or nokogiri-builtin:css-class(@class,'AGVhpb') or nokogiri-builtin:css-class(@class,'GyDBsd') or nokogiri-builtin:css-class(@class,'VQN8fd') or nokogiri-builtin:css-class(@class,'VZTCjd') or nokogiri-builtin:css-class(@class,'REX1ub') or nokogiri-builtin:css-class(@class,'sHaywe') or nokogiri-builtin:css-class(@class,'eaGTj')]

# Union from xpath_query_from_css_rule
.//*[nokogiri-builtin:css-class(@class,'eIuuYe')]//a | .//a[nokogiri-builtin:css-class(@class,'EI11Pd')] | .//a[nokogiri-builtin:css-class(@class,'AGVhpb')] | .//a[nokogiri-builtin:css-class(@class,'GyDBsd')] | .//a[nokogiri-builtin:css-class(@class,'VQN8fd')] | .//a[nokogiri-builtin:css-class(@class,'VZTCjd')] | .//a[nokogiri-builtin:css-class(@class,'REX1ub')] | .//a[nokogiri-builtin:css-class(@class,'sHaywe')] | .//a[nokogiri-builtin:css-class(@class,'eaGTj')]
```

**Environment**

```
# Nokogiri (1.12.4)
    ---
    warnings: []
    nokogiri:
      version: 1.12.4
      cppflags:
      - "-I/home/ilyazub/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.4-x86_64-linux/ext/nokogiri"
      - "-I/home/ilyazub/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.4-x86_64-linux/ext/nokogiri/include"
      - "-I/home/ilyazub/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.4-x86_64-linux/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.7.2
      platform: x86_64-linux
      gem_platform: x86_64-linux
      description: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      libxml2_path: "/home/ilyazub/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.4-x86_64-linux/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      datetime_enabled: true
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      zlib: 1.2.11
      libgumbo: 1.0.0-nokogiri
```

I'd like to speed up `xpath_query_from_css_rule` but it seems that optimization should be done on the libxml2 side.

@flavorjones What do you think and what additional information do you want to see?
