### ISSUE TITLE
HTML5 parser closes <math> before <span>

### ISSUE THREAD

**Issue by syakovyn** [sparklemotion/nokogiri#2335]
HTML5 parser differs in output from HTML4 parser. We consider the HTML4 parser output is the right one.

A script to reproduce the bug:

```ruby
#! /usr/bin/env ruby

require 'nokogiri'
require 'minitest/autorun'

class Test < MiniTest::Spec
  describe "HTML5 parser" do
    it "produces the same output as HTML4" do
      html = <<-HTML
<mjx-container>
<mjx-assistive-mml>
<math xmlns=\"http://www.w3.org/1998/Math/MathML\">
            <msqrt><span>\n\n  </span>
                <mn>3</mn>
            </msqrt>
        </math>
        <script>window.destroyAllHumans()</script>
        \n\n
        <msqrt>
            <mn>4</mn>
        </msqrt>
    </mjx-assistive-mml>
</mjx-container>
      HTML
      html5 = Nokogiri::HTML5.fragment(html).to_s
      html4 = Nokogiri::HTML4.fragment(html).to_s

      assert_equal html4, html5
    end
  end
end
```

**Environment**

```
# Nokogiri (1.12.5)
    ---
    warnings: []
    nokogiri:
      version: 1.12.5
      cppflags:
      - "-I/Users/syakovyn/.rvm/gems/ruby-2.7.4/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri"
      - "-I/Users/syakovyn/.rvm/gems/ruby-2.7.4/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri/include"
      - "-I/Users/syakovyn/.rvm/gems/ruby-2.7.4/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.7.4
      platform: x86_64-darwin20
      gem_platform: x86_64-darwin-20
      description: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin20]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      libxml2_path: "/Users/syakovyn/.rvm/gems/ruby-2.7.4/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      datetime_enabled: true
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      zlib: 1.2.11
      libiconv: '1.15'
      libgumbo: 1.0.0-nokogiri
```
