### ISSUE TITLE
[bug] Nokogiri 1.12.0+ breaks YAML serialization of Nokogiri::XML::Node

### ISSUE THREAD

**Issue by Dantemss** [sparklemotion/nokogiri#2336]
**Please describe the bug**

Nokogiri 1.12.0+ breaks YAML serialization of Nokogiri::XML::Node (and subclasses).
That means Nokogiri::XML::Node#to_yaml and YAML.load("resulting string") do not work as expected.
This is because YAML serialization uses Class#allocate which is broken in 1.12.0+.

**Help us reproduce what you're seeing**

A minimal example of the broken code in 1.12.0+:
```
irb(main):001:0> YAML.load "--- !ruby/object:Nokogiri::XML::Node {}\n"
Traceback (most recent call last):
        1: from (irb):1
TypeError (allocator undefined for Nokogiri::XML::Node)
```

This works in 1.11.7 but you get an unrelated error whenever the console tries to print the node which is why I like to call the `class` method on the result:
```
irb(main):001:0> YAML.load("--- !ruby/object:Nokogiri::XML::Node {}\n").class
=> Nokogiri::XML::Node
```

While investigating I discovered that in 1.11.7 Nokogiri::XML::Node#allocate works normally:
```
irb(main):001:0> Nokogiri::XML::Node.allocate.class
=> Nokogiri::XML::Node
```

However, in 1.12.0 Nokogiri::XML::Node#allocate throws an exception:
```
irb(main):001:0> Nokogiri::XML::Node.allocate.class
Traceback (most recent call last):
        2: from (irb):1
        1: from (irb):1:in `allocate'
TypeError (allocator undefined for Nokogiri::XML::Node)
```

I have not yet managed to figure out why that is.

**Expected behavior**

Either the allocate method should work or the fact that it does not should be documented somewhere (as well as the lack of support for YAML serialization, if that path is chosen).

**Environment**

This is the version I was trying to update to, but the same issue happens in 1.12.0.
```
# Nokogiri (1.12.5)
    ---
    warnings: []
    nokogiri:
      version: 1.12.5
      cppflags:
      - "-I/home/dante/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/ext/nokogiri"
      - "-I/home/dante/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/ext/nokogiri/include"
      - "-I/home/dante/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.7.2
      platform: x86_64-linux
      gem_platform: x86_64-linux
      description: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      libxml2_path: "/home/dante/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      datetime_enabled: true
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      zlib: 1.2.11
      libgumbo: 1.0.0-nokogiri
```

**Additional context**

I had the Nokogiri nodes serialized for performance reasons.
I suppose I could try dropping the serialization and see what would be the performance penalty...
