### ISSUE TITLE
Native gem not installed on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by airblade** [sparklemotion/nokogiri#2341]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [x] Yes!

**What is the complete output of `gem install` or `bundle install`?**

<details>
<summary>Initially Nokogiri failed to install via bundler:</summary>

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5/ext/nokogiri
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20211014-134361-1lbbnwu.rb extconf.rb
checking for whether -std=c99 is accepted as CFLAGS... yes
checking for whether -Wno-declaration-after-statement is accepted as CFLAGS...
yes
checking for whether -g is accepted as CFLAGS... yes
checking for whether -Winline is accepted as CFLAGS... yes
checking for whether -Wmissing-noreturn is accepted as CFLAGS... yes
Building nokogiri using packaged libraries.
Static linking is enabled.
Cross build is disabled.
checking for gzdopen() in -lz... yes
Using mini_portile version 2.6.1
checking for iconv... yes
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libxml2-2.9.12.
Configuration options: --host\=x86_64-pc-linux-gnu --enable-static
--disable-shared
--libdir\=/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5/ports/x86_64-pc-linux-gnu/libxml2/2.9.12/lib
--with-iconv\=yes --disable-dependency-tracking --without-python
--without-readline --with-c14n --with-debug --with-threads --disable-shared
--enable-static CFLAGS\=-O2\ -U_FORTIFY_SOURCE\ -g\ -fPIC
The following patches are being applied:
  - 0001-Remove-script-macro-support.patch
  - 0002-Update-entities-to-remove-handling-of-ssi.patch
  - 0003-libxml2.la-is-in-top_builddir.patch
  - 0004-use-glibc-strlen.patch
  - 0005-avoid-isnan-isinf.patch
  - 0006-update-automake-files-for-arm64.patch
  - 0007-Fix-XPath-recursion-limit.patch

The Nokogiri maintainers intend to provide timely security updates, but if
this is a concern for you and want to use your OS/distro system library
instead, then abort this installation process and install nokogiri as
instructed at:

https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries

Note, however, that nokogiri cannot guarantee compatibility with every
version of libxml2 that may be provided by OS/package vendors.

Extracting libxml2-2.9.12.tar.gz into
tmp/x86_64-pc-linux-gnu/ports/libxml2/2.9.12... OK
Running git apply with
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5/patches/libxml2/0001-Remove-script-macro-support.patch...
OK
Running git apply with
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5/patches/libxml2/0002-Update-entities-to-remove-handling-of-ssi.patch...
OK
Running git apply with
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5/patches/libxml2/0003-libxml2.la-is-in-top_builddir.patch...
OK
Running git apply with
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5/patches/libxml2/0004-use-glibc-strlen.patch...
OK
Running git apply with
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5/patches/libxml2/0005-avoid-isnan-isinf.patch...
OK
Running git apply with
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5/patches/libxml2/0006-update-automake-files-for-arm64.patch...
OK
Running git apply with
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5/patches/libxml2/0007-Fix-XPath-recursion-limit.patch...
OK
Running 'configure' for libxml2 2.9.12... OK
Running 'compile' for libxml2 2.9.12... ERROR, review
'/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5/ext/nokogiri/tmp/x86_64-pc-linux-gnu/ports/libxml2/2.9.12/compile.log'
to see what happened. Last lines are:
========================================================================
make[1]: Entering directory '/var/www/lorhub.co'
make[1]: *** No rule to make target 'stamp-h1'.  Stop.
make[1]: Leaving directory '/var/www/lorhub.co'
make: *** [Makefile:934: config.h] Error 2
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--prevent-strip
	--enable-system-libraries
	--disable-system-libraries
	--use-system-libraries
	--enable-system-libraries
	--disable-system-libraries
	--use-system-libraries
	--enable-static
	--disable-static
	--enable-cross-build
	--disable-cross-build
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--with-xml2-source-dir
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:443:in
`block in execute': Failed to complete compile task (RuntimeError)
from
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:409:in
`chdir'
from
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:409:in
`execute'
from
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:137:in
`compile'
from
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:180:in
`cook'
	from extconf.rb:511:in `block (2 levels) in process_recipe'
	from extconf.rb:296:in `block in chdir_for_build'
	from extconf.rb:295:in `chdir'
	from extconf.rb:295:in `chdir_for_build'
	from extconf.rb:511:in `block in process_recipe'
	from extconf.rb:415:in `tap'
	from extconf.rb:415:in `process_recipe'
	from extconf.rb:752:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0-static/nokogiri-1.12.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5 for inspection.
Results logged to
/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0-static/nokogiri-1.12.5/gem_make.out

  /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:99:in `run'
/usr/local/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:48:in `block in
build'
  /usr/local/lib/ruby/2.7.0/tempfile.rb:291:in `open'
  /usr/local/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:30:in `build'
/usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:169:in `block in
build_extension'
  /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `synchronize'
  /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `build_extension'
/usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:210:in `block in
build_extensions'
  /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `each'
  /usr/local/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `build_extensions'
  /usr/local/lib/ruby/2.7.0/rubygems/installer.rb:844:in `build_extensions'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/rubygems_gem_installer.rb:66:in
`build_extensions'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/rubygems_gem_installer.rb:26:in
`install'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/source/rubygems.rb:186:in
`install'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/installer/gem_installer.rb:54:in
`install'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/worker.rb:62:in
`apply_func'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/worker.rb:57:in
`block in process_queue'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/worker.rb:54:in
`loop'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/worker.rb:54:in
`process_queue'
/usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.2.25/lib/bundler/worker.rb:91:in
`block (2 levels) in create_threads'

An error occurred while installing nokogiri (1.12.5), and Bundler cannot
continue.

In Gemfile:
  activestorage-validator was resolved to 0.1.4, which depends on
    rails was resolved to 6.1.4.1, which depends on
      actioncable was resolved to 6.1.4.1, which depends on
        actionpack was resolved to 6.1.4.1, which depends on
          actionview was resolved to 6.1.4.1, which depends on
            rails-dom-testing was resolved to 2.0.3, which depends on
              nokogiri
    --> failed
```
</details>

Then I installed it "by hand" (`gem install nokogiri`) and it worked, though it compiled the native extensions.

<details>
<summary>Then I re-tried bundler again and this time it worked, though again it compiled the native extensions.</summary>

```
Fetching nokogiri 1.12.5
Installing nokogiri 1.12.5 with native extensions
```
</details>

**If installation completed but is broken, what is the complete output from `nokogiri -v`?**

```
# Nokogiri (1.12.5)
    ---
    warnings: []
    nokogiri:
      version: 1.12.5
      cppflags:
      - "-I/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5/ext/nokogiri"
      - "-I/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5/ext/nokogiri/include"
      - "-I/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.7.2
      platform: x86_64-linux
      gem_platform: x86_64-linux
      description: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
      engine: ruby
    libxml:
      source: packaged
      precompiled: false
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      libxml2_path: "/var/www/lorhub.co/vendor/bundle/ruby/2.7.0/gems/nokogiri-1.12.5/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: false
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      datetime_enabled: true
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      libgumbo: 1.0.0-nokogiri
```

**Tell us about your system!**

What is the output from `ruby -v`?  `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]`

What is the output from `gem -v`?  `3.1.4`

What is the output from `gem env`?

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.4
  - RUBY VERSION: 2.7.2 (2020-10-01 patchlevel 137) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.7.0
  - USER INSTALLATION DIRECTORY: /home/deploy/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /usr/local/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/deploy/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.7.0
     - /home/deploy/.gem/ruby/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
```

If you're using Bundler:
- what is the output from `bundle version`? `Bundler version 2.2.25 (2021-07-30 commit 7f0f257c7a)`
- what is the output from `bundle config`? (Take care to redact any credentials)

```
Settings are listed in order of priority. The top value will be used.
deployment
Set for your local app (/var/www/lorhub.co/.bundle/config): true

path
Set for your local app (/var/www/lorhub.co/.bundle/config): "vendor/bundle"

without
Set for your local app (/var/www/lorhub.co/.bundle/config): [:development, :test]
```

If Linux or a BSD variant, please note:
- the distro you're using: `Ubuntu 20.04 LTS`
- the output of `uname -a`: `Linux lorhub 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- the contents of `/etc/lsb-release`:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

According to the [installation docs on native gems](https://nokogiri.org/#native-gems-faster-more-reliable-installation), there are two requirements:

- a compatible platform: mine is `x86_64-linux` (via `ruby -e 'puts Gem::Platform.local.to_s'`)
- glibc >= 2.17: mine is 2.31 (via `ldd --version`)

I'm not too interested in why Nokogiri didn't bundle correctly the first time.

However I would like to know how I can get it to install a native gem.

Thanks!
