### ISSUE TITLE
[install]

### ISSUE THREAD

**Issue by amritha** [sparklemotion/nokogiri#2343]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [X] Yes!

My issue is that everytime I try to create a new project in rails, nokogiri fails and gives me this error:
Bundle complete! 17 Gemfile dependencies, 75 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  webpacker:install
rails aborted!
LoadError: cannot load such file -- nokogiri/nokogiri

**What is the complete output of `gem install` or `bundle install`?**

```
///amrithaprasad@amrithas-mbp workspace % gem install nokogiri
///Successfully installed nokogiri-1.12.5-x86_64-darwin
///1 gem installed

```

**If installation completed but is broken, what is the complete output from `nokogiri -v`?**

```
# Nokogiri (1.12.5)
    ---
    warnings: []
    nokogiri:
      version: 1.12.5
      cppflags:
      - "-I/Users/amrithaprasad/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri"
      - "-I/Users/amrithaprasad/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri/include"
      - "-I/Users/amrithaprasad/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.0.2
      platform: x86_64-darwin20
      gem_platform: x86_64-darwin-20
      description: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      libxml2_path: "/Users/amrithaprasad/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      datetime_enabled: true
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      zlib: 1.2.11
      libiconv: '1.15'
      libgumbo: 1.0.0-nokogiri

```

**If installation failed during compilation, what are the complete contents of the `mkmf.log` file generated during the failed installation?**

```
the mkmf.log file contents go here
```

**Tell us about your system!**

What is the output from `ruby -v`?
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

What is the output from `gem -v`?
3.2.29

What is the output from `gem env`?

```
the output of "gem env" output goes here
```

If you're using Bundler:
- what is the output from `bundle version`?
- what is the output from `bundle config`? (Take care to redact any credentials)

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.29
  - RUBY VERSION: 3.0.2 (2021-07-07 patchlevel 107) [x86_64-darwin20]
  - INSTALLATION DIRECTORY: /Users/amrithaprasad/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0
  - USER INSTALLATION DIRECTORY: /Users/amrithaprasad/.gem/ruby/3.0.0
  - RUBY EXECUTABLE: /Users/amrithaprasad/.asdf/installs/ruby/3.0.2/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /Users/amrithaprasad/.asdf/installs/ruby/3.0.2/bin
  - SPEC CACHE DIRECTORY: /Users/amrithaprasad/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/amrithaprasad/.asdf/installs/ruby/3.0.2/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-darwin-20
  - GEM PATHS:
     - /Users/amrithaprasad/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0
     - /Users/amrithaprasad/.gem/ruby/3.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/amrithaprasad/.asdf/installs/ruby/3.0.2/bin
     - /Users/amrithaprasad/.asdf/shims
     - /usr/local/Cellar/asdf/0.8.1_1/libexec/bin
     - /usr/local/opt/ruby/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin

```

If you're on MacOS, please note:
- the version of XCode you have installed (if you know)
- the output of `gcc -v` or `clang -v`
-gcc-v:
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

If Linux or a BSD variant, please note:
- the distro you're using
- the output of `uname -a`
- the contents of `/etc/lsb-release`.

If Windows, please note:
- whether you're installing the precompiled gems, or compiling yourself with DevKit
- the version of RubyInstaller you've installed
- or if you're not using RubyInstaller, how did you install Ruby?
