### ISSUE TITLE
[bug] Inconsistent behavior on JRuby/CRuby

### ISSUE THREAD

**Issue by dometto** [sparklemotion/nokogiri#2355]
The following snippet produces different results on JRuby and CRuby:

```ruby
require 'nokogiri'
data = "<h1>First H1</h1>"
doc = Nokogiri::HTML::DocumentFragment.parse(data)
header = doc.css('h1').first
a = Nokogiri::XML::Node.new('a', doc)
header.children.before(a)
puts header.to_xml({:save_with => Nokogiri::XML::Node::SaveOptions::DEFAULT_XHTML ^ 1})
```

On CRuby, it produces what one would expect:

```
<h1><a></a>First H1</h1>
```

However, on JRuby, it producs the following invalid XHTML:

```
<h1><a>First H1</h1>
```

**Environment**

CRuby:
```
# Nokogiri (1.12.5)
    ---
    warnings: []
    nokogiri:
      version: 1.12.5
      cppflags:
      - "-I/Users/redacted/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri"
      - "-I/Users/redacted/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri/include"
      - "-I/Users/redacted/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.6.3
      platform: x86_64-darwin18
      gem_platform: x86_64-darwin-18
      description: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      libxml2_path: "/Users/redacted/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      datetime_enabled: true
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      zlib: 1.2.11
      libiconv: '1.15'
      libgumbo: 1.0.0-nokogiri
```

JRuby:

```
# Nokogiri (1.12.5)
    ---
    warnings: []
    nokogiri:
      version: 1.12.5
    ruby:
      version: 2.5.8
      platform: java
      gem_platform: universal-java-11
      description: jruby 9.2.18.0 (2.5.8) 2021-06-08 d67cb7d6e0 OpenJDK 64-Bit Server
        VM 11.0.13+8 on 11.0.13+8 +jit [darwin-x86_64]
      engine: jruby
      jruby: 9.2.18.0
    other_libraries:
      xerces: Xerces-J 2.12.0
      nekohtml: NekoHTML 1.9.21
```

**Additional context**

This bug was not present on version `1.11.7`
