### ISSUE TITLE
[bug] HTML5 foreign element namespaces should not be required by CSS queries

### ISSUE THREAD

**Issue by danblaker** [sparklemotion/nokogiri#2376]
After upgrading to Nokogiri v1.12.0, I am unable to target inline svg elements via css or xpath selectors. Sample console commands:

```
html = <<-HTML.strip_heredoc
<!DOCTYPE html>
<html>
<head>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <title>svg test</title>
</head>
<body>
  <div id="svg-container">
    <svg version="1.1" width="300" height="200" xmlns="http://www.w3.org/2000/svg">

      <rect width="100%" height="100%" fill="red" />

      <circle cx="150" cy="100" r="80" fill="green" />

      <text x="150" y="125" font-size="60" text-anchor="middle" fill="white">SVG</text>
    </svg>
  </div>
</body>
</html>
HTML

doc = Nokogiri::HTML5.parse(html)
doc.at('svg') # nil
doc.at_css('svg') # nil
doc.at_xpath('//svg') # nil
```

**Expected behavior**

Using the previous versions of Nokogiri (v 1.10.10) + nokogumbo (1.5.0), I was able to target SVG elements without any problems.

**Environment**

```
# Nokogiri (1.12.5)
    ---
    warnings: []
    nokogiri:
      version: 1.12.5
      cppflags:
      - "-I/usr/local/bundle/gems/nokogiri-1.12.5/ext/nokogiri"
      - "-I/usr/local/bundle/gems/nokogiri-1.12.5/ext/nokogiri/include"
      - "-I/usr/local/bundle/gems/nokogiri-1.12.5/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.6.8
      platform: aarch64-linux-musl
      gem_platform: aarch64-linux
      description: ruby 2.6.8p205 (2021-07-07 revision 67951) [aarch64-linux-musl]
      engine: ruby
    libxml:
      source: packaged
      precompiled: false
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      libxml2_path: "/usr/local/bundle/gems/nokogiri-1.12.5/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: false
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      datetime_enabled: true
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      libgumbo: 1.0.0-nokogiri
```
