### ISSUE TITLE
Apple Silicon MacOS Monterey Missing OS Dependencies

### ISSUE THREAD

**Issue by daBee** [sparklemotion/nokogiri#2378]
`bundle doctor` reports the following:

```
The following gems are missing OS dependencies:
 * nokogiri: /usr/lib/libSystem.B.dylib
 * nokogiri: /usr/lib/liblzma.5.dylib
 * nokogiri: /usr/lib/libobjc.A.dylib
 ```

    gem "nokogiri"

That's how to reproduce it in the `Gemfile`.

```
➜ nokogiri -v
# Nokogiri (1.12.5)
    ---
    warnings: []
    nokogiri:
      version: 1.12.5
      cppflags:
      - "-I/Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-arm64-darwin/ext/nokogiri"
      - "-I/Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-arm64-darwin/ext/nokogiri/include"
      - "-I/Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-arm64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.7.4
      platform: arm64-darwin21
      gem_platform: arm64-darwin-21
      description: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [arm64-darwin21]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      libxml2_path: "/Users/rich/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-arm64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      datetime_enabled: true
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      zlib: 1.2.11
      libiconv: '1.15'
      libgumbo: 1.0.0-nokogiri
```

Please let me know if you need anything else.  Cheers
