### ISSUE TITLE
[bug] Call on terminated object

### ISSUE THREAD

**Issue by rfatemi-r7** [sparklemotion/nokogiri#2393]
Hi there,

I've been running into some issues where my method is called by a terminated object. This is most likely related to some external libraries used by `nokogiri` as I don't think this is something that can happen in pure ruby due to how the garbage collection works.

My bug report isn't going to be the most useful as I can't share much, whether it's data or ruby script. However, I can share these error logs so you can see where it happens.

```
[2021-12-21 15:08:09] [ERROR] [saw:159] [Object] -- Exception occurred while parsing <redacted>: method `<=>' called on terminated object (0x00007fc0d9e04448)
	/Users/rfatemi/<redacted>.rb:105:in `sort!'
	/Users/rfatemi/<redacted>.rb:105:in `<<'
	/Users/rfatemi/<redacted>.rb:51:in `block (2 levels) in parse_xml'
	/Users/rfatemi/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
	/Users/rfatemi/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
	/Users/rfatemi/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
	/Users/rfatemi/rapid7/vuln-tools/saw/apache/httpd/httpd_parser.rb:50:in `block in parse_xml'
	/Users/rfatemi/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
	/Users/rfatemi/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
	/Users/rfatemi/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
	/Users/rfatemi/<redacted>.rb:30:in `parse_xml'
	/Users/rfatemi/<redacted>.rb:111:in `parse'
	/Users/rfatemi/<redacted>:157:in `<main>'
```

**Environment**
```
# Nokogiri (1.12.5)
    ---
    warnings: []
    nokogiri:
      version: 1.12.5
      cppflags:
      - "-I/Users/rfatemi/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri"
      - "-I/Users/rfatemi/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri/include"
      - "-I/Users/rfatemi/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.6.3
      platform: x86_64-darwin20
      gem_platform: x86_64-darwin-20
      description: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin20]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      libxml2_path: "/Users/rfatemi/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      datetime_enabled: true
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      zlib: 1.2.11
      libiconv: '1.15'
      libgumbo: 1.0.0-nokogiri
```

Also tested with `ruby 3.0.2`.

**Additional context**

Sometimes it turns into a segmentation fault error
```
[BUG] Segmentation fault at 0x0000000000000000
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin20]

<redacted>
c:0011 p:0009 s:0085 e:000084 BLOCK  /Users/rfatemi/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/lib/nokogiri/xml/node_set.rb:239 [FINISH]
c:0010 p:---- s:0081 e:000080 CFUNC  :upto
c:0009 p:0024 s:0076 e:000075 METHOD /Users/rfatemi/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/lib/nokogiri/xml/node_set.rb:238
c:0008 p:0130 s:0072 e:000071 BLOCK  /Users/rfatemi/rapid7/<redacted>.rb:50
c:0007 p:0009 s:0064 e:000063 BLOCK  /Users/rfatemi/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/lib/nokogiri/xml/node_set.rb:239 [FINISH]
c:0006 p:---- s:0060 e:000059 CFUNC  :upto
c:0005 p:0024 s:0055 e:000054 METHOD /Users/rfatemi/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.12.5-x86_64-darwin/lib/nokogiri/xml/node_set.rb:238
<redacted>
```
Which again is related to that ruby sort function.
While unlikely, I hope this includes enough information to replicate the problem.

Cheers
