### ISSUE TITLE
[bug][jruby] Strikethrough tag causes incorrect HTML parsing in JRuby

### ISSUE THREAD

**Issue by davue** [sparklemotion/nokogiri#2436]
**Please describe the bug**
If you parse an HTML string containing a `<s></s>` tag. The elements above the `<s></s>` tag are duplicated into a seperate child element without content and the other child with the actual content will have inverted order. Strangely this only seems to happen with `<s></s>` tags, all other tags are parsed just fine.

**Help us reproduce what you're seeing**
Open a JRuby Rails console and run:
```
Nokogiri::HTML4::DocumentFragment.parse("<!DOCTYPE HTML><html><body><strong><s>Test</s></strong></body></html>")
```
The output will show that the parser created an additional `strong` child even though it is not present in the HTML input and the order of tags is inverted for the other child:
```
#(DocumentFragment:0x888 {
  name = "#document-fragment",
  children = [
    #(Element:0x88a { name = "strong" }),
    #(Element:0x88c { name = "s", children = [ #(Element:0x88e { name = "strong", children = [ #(Text "Test")] })] })]
  })
```

**Expected behavior**
I expect the output to look like in the CRuby implementation, where only one child element is present and the order is correct:
```
#(DocumentFragment:0x13254 {
  name = "#document-fragment",
  children = [
    #(Element:0x13268 { name = "strong", children = [ #(Element:0x1327c { name = "s", children = [ #(Text "Test")] })] })]
  })
```

**Environment**
```
# Nokogiri (1.13.1)
    ---
    warnings: []
    nokogiri:
      version: 1.13.1
    ruby:
      version: 2.6.8
      platform: java
      gem_platform: universal-java-1.8
      description: jruby 9.3.2.0 (2.6.8) 2021-12-01 0b8223f905 OpenJDK 64-Bit Server VM
        25.302-b08 on 1.8.0_302-b08 +jit [linux-x86_64]
      engine: jruby
      jruby: 9.3.2.0
    other_libraries:
      xerces: Xerces-J 2.12.0
      nekohtml: NekoHTML 1.9.21
```
