### ISSUE TITLE
HTML5 parser moves last child text node of <form> tag outside the tag

### ISSUE THREAD

**Issue by npickens** [sparklemotion/nokogiri#2450]
**Please describe the bug**

HTML5 parser moves the last child text node of a `<form>` tag outside the tag (as next sibling). Example:

```ruby
Nokogiri::HTML5.fragment('<form>Some text here</form>').to_html
# => "<form></form>Some text here"
```

Expected behavior:

```ruby
Nokogiri::HTML5.fragment('<form>Some text here</form>').to_html
# => "<form>Some text here</form>"
```

**Help us reproduce what you're seeing**

```ruby
#!/usr/bin/env ruby

require 'nokogiri'
require 'minitest/autorun'

class Test < MiniTest::Spec
  describe "HTML5::fragment" do
    it "should parse last child text node of <form> tag as last child text node" do
      html = '<form>Some text here</form>'
      doc = Nokogiri::HTML5.fragment(html)
      
      assert_equal(html, doc.to_html)
    end
  end
end
```

**Environment**

```
# Nokogiri (1.13.1)
    ---
    warnings: []
    nokogiri:
      version: 1.13.1
      cppflags:
      - "-I[...]/ruby/3.0.0/gems/nokogiri-1.13.1-x86_64-darwin/ext/nokogiri"
      - "-I[...]/ruby/3.0.0/gems/nokogiri-1.13.1-x86_64-darwin/ext/nokogiri/include"
      - "-I[...]/ruby/3.0.0/gems/nokogiri-1.13.1-x86_64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.0.3
      platform: x86_64-darwin21
      gem_platform: x86_64-darwin-21
      description: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin21]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - 0007-Fix-XPath-recursion-limit.patch
      - '0008-htmlParseComment-handle-abruptly-closed-comments.patch'
      - '0009-allow-wildcard-namespaces.patch'
      libxml2_path: "[...]/ruby/3.0.0/gems/nokogiri-1.13.1-x86_64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.12
      loaded: 2.9.12
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      - 0002-Fix-xml2-config-check-in-configure-script.patch
      datetime_enabled: true
      compiled: 1.1.34
      loaded: 1.1.34
    other_libraries:
      zlib: 1.2.11
      libiconv: '1.16'
      libgumbo: 1.0.0-nokogiri
```
