### ISSUE TITLE
Breaking Change in to_xpath method breaks webrat

### ISSUE THREAD

**Issue by petergoldstein** [sparklemotion/nokogiri#2469]
**Please describe the bug**

A recent breaking change to `to_xpath` to remove the default argument (made [here](https://github.com/sparklemotion/nokogiri/commit/b24efcca08cc93881c29c95a31c2068002b591ba)) broke [webrat](https://github.com/brynary/webrat).

[This requires locking the Devise Gemfile to a version of nokogiri from before this change](https://github.com/heartcombo/devise/pull/5450#issuecomment-1051046519)

[The relevant line in webrat](https://github.com/brynary/webrat/blob/8947ea89c16a4ffef06ccbb871e3452fa3aeb169/lib/webrat/core/matchers/have_selector.rb#L40)

Because webrat has been unmaintained for a decade this issue is very difficult to resolve there.

**Help us reproduce what you're seeing**

I don't have a short script, but if you look at my comment in the Devise PR above, you'll note that you can reproduce the issue by simply removing the Nokogiri version restriction from the `Gemfile` in the Devise repo and running the test suite.

**Expected behavior**

Webrat should work with nokogiri without error.

**Environment**

```
# Nokogiri (1.13.3)
    ---
    warnings: []
    nokogiri:
      version: 1.13.3
      cppflags:
      - "-I/Users/peter/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.13.3-x86_64-darwin/ext/nokogiri"
      - "-I/Users/peter/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.13.3-x86_64-darwin/ext/nokogiri/include"
      - "-I/Users/peter/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.13.3-x86_64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.0.3
      platform: x86_64-darwin21
      gem_platform: x86_64-darwin-21
      description: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin21]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - '0008-htmlParseComment-handle-abruptly-closed-comments.patch'
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-Revert-Different-approach-to-fix-quadratic-behavior.patch
      libxml2_path: "/Users/peter/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.13.3-x86_64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.13
      loaded: 2.9.13
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.35
      loaded: 1.1.35
    other_libraries:
      zlib: 1.2.11
      libiconv: '1.16'
      libgumbo: 1.0.0-nokogiri
```
