### ISSUE TITLE
Ampersand (&) is no longer converted to &amp; in link tags

### ISSUE THREAD

**Issue by strzibny** [sparklemotion/nokogiri#2483]
I am upgrading Nokogiri to version 1.13.x and hitting a possible bug where an ampersand (`&`) in the URL is not treated as ampersand.

The code:

```ruby
require 'nokogiri'
doc = Nokogiri::XML::Builder.new(encoding: 'UTF-8') do |xml|
  xml.root do
     xml.string({}) {  
        xml << "ss <a href=\"http://www.example.com?foo=bar&bar=foo&amp;test=amp\">sss</a> ss"
     }
  end
end
puts doc.to_xml
```

Nokogiri before 1.13.0 (notice it accepted both `&` and `&amp;`):

```
<?xml version="1.0" encoding="UTF-8"?>
<root>
    <string>ss <a href="http://www.example.com?foo=bar&amp;bar=foo&amp;test=amp">sss</a> ss</string>
</root>
```

Nokogiri after 1.13.0 (notice the single `&`  disappeared together with the "bar" key just after):

```
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <string>ss <a href="http://www.example.com?foo=bar=foo&amp;test=amp">sss</a> ss</string>
</root>


```
Looks like `&bar` got treated as an escape sign but with no value so it disappeared.

Here's the script again:

```ruby
#! /usr/bin/env ruby

require 'nokogiri'
doc = Nokogiri::XML::Builder.new(encoding: 'UTF-8') do |xml|
  xml.root do
      xml.string({}) {  
        xml << "ss <a href=\"http://www.example.com?foo=bar&bar=foo&amp;test=amp\">sss</a> ss"
      }
  end
end
puts doc.to_xml
```

**Expected behavior**

I would expect the old behaviour where the  `&` sign in URL gets transformed to `&amp;`. Not sure if this is wrong, but that's what I would expect.

**Environment**

```bash
$ nokogiri -v
# Nokogiri (1.13.3)
    ---
    warnings: []
    nokogiri:
      version: 1.13.3
      cppflags:
      - "-I/home/strzibny/.gem/ruby/3.0.3/gems/nokogiri-1.13.3-x86_64-linux/ext/nokogiri"
      - "-I/home/strzibny/.gem/ruby/3.0.3/gems/nokogiri-1.13.3-x86_64-linux/ext/nokogiri/include"
      - "-I/home/strzibny/.gem/ruby/3.0.3/gems/nokogiri-1.13.3-x86_64-linux/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.0.3
      platform: x86_64-linux
      gem_platform: x86_64-linux
      description: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - '0008-htmlParseComment-handle-abruptly-closed-comments.patch'
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-Revert-Different-approach-to-fix-quadratic-behavior.patch
      libxml2_path: "/home/strzibny/.gem/ruby/3.0.3/gems/nokogiri-1.13.3-x86_64-linux/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.13
      loaded: 2.9.13
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.35
      loaded: 1.1.35
    other_libraries:
      zlib: 1.2.11
      libgumbo: 1.0.0-nokogiri
```
Note I tested 1.13.0 as well, which is the version where this behaviour was likely introduced.

**Comment by strzibny** [comment]
Okay so it's not just about URLs, it's about ampersand in general.

Here's another example:

```ruby
require 'nokogiri'
doc = Nokogiri::XML::Builder.new(encoding: 'UTF-8') do |xml|
  xml.root do
      xml.string({}) {  
        xml << "bar & bar"
      }
  end
end
puts doc.to_xml
```
and on Nokogiri > 1.13.0 the result escapes it:

```
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <string>bar  bar</string>
</root>
```

**Comment by stevecheckoway** [comment]
I'm not an expert on XML, but isn't
```ruby
xml << "bar & bar"
```
invalid because the right hand side is supposed to be a raw XML string but it has the `&` in it.

**Comment by stevecheckoway** [comment]
@strzibny For your second example, you should use the `text` method.
```ruby
require 'nokogiri'
doc = Nokogiri::XML::Builder.new(encoding: 'UTF-8') do |xml|
  xml.root do
      xml.string {
        xml.text("bar & bar")
      }
  end
end
puts doc.to_xml
```

For your first example, you'll either need to provide valid XML on the right hand side of `<<` (as I suspected, your XML [is invalid](https://stackoverflow.com/a/14500841)) or you'll need to use the builder API to construct the anchor.

**Comment by flavorjones** [comment]
Sorry for my slow reply, I was on vacation for a bit last week.

### Summary

I'll spend a bit of time today bisecting libxml2 just to make sure I understand when this behavior changed, but right now I think that attribute entity is handled consistently and correctly; and the dropped bare ampersand in a text node is a duplicate of #2267 which was reported upstream at https://gitlab.gnome.org/GNOME/libxml2/-/issues/270 and is still unresolved.


### Details

I'm going to unify the two things being reported, simplify by using the DOM parser (not the Builder) and demonstrate how the parsers behave in the XML, HTML4, and HTML5 parsers, along with any parsing errors encountered:

```ruby
#! /usr/bin/env ruby

require 'nokogiri'

html = <<~HTML
<html><body>
  <a href=\"http://www.example.com?foo=bar&bar=foo&amp;test=amp\"> foo & bar </a>
</body></html>
HTML

document = Nokogiri::XML::Document.parse(html)
puts document.to_xml
pp document.errors

puts "----------"

document = Nokogiri::HTML4::Document.parse(html)
puts document.to_html
pp document.errors

puts "----------"

if defined?(Nokogiri::HTML5)
  document = Nokogiri::HTML5::Document.parse(html)
  puts document.to_html
  pp document.errors
end
```

outputs:

```text
<?xml version="1.0"?>
<html>
  <body>
  <a href="http://www.example.com?foo=bar=foo&amp;test=amp"> foo  bar </a>
</body>
</html>
[#<Nokogiri::XML::SyntaxError: 2:46: FATAL: EntityRef: expecting ';'>,
 #<Nokogiri::XML::SyntaxError: 2:71: FATAL: xmlParseEntityRef: no name>]
----------
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body>
  <a href="http://www.example.com?foo=bar&amp;bar=foo&amp;test=amp"> foo &amp; bar </a>
</body></html>
[#<Nokogiri::XML::SyntaxError: 2:46: ERROR: htmlParseEntityRef: expecting ';'>,
 #<Nokogiri::XML::SyntaxError: 2:71: ERROR: htmlParseEntityRef: no name>]
----------
<html><head></head><body>
  <a href="http://www.example.com?foo=bar&amp;bar=foo&amp;test=amp"> foo &amp; bar </a>

</body></html>
[]
```

and on JRuby (to check consistency against the Xerces and NekoHTML parsers):

```text
<?xml version="1.0"?>
<html><body>
  </body></html>
[#<Nokogiri::XML::SyntaxError: The reference to entity "bar" must end with the ';' delimiter.>,
 #<Nokogiri::XML::SyntaxError: The reference to entity "bar" must end with the ';' delimiter.>]
----------
<html><head></head><body>
  <a href="http://www.example.com?foo=bar&amp;bar=foo&amp;test=amp"> foo &amp; bar </a>

</body></html>
[#<Nokogiri::XML::SyntaxError: Bare ampersand found.>,
 #<Nokogiri::XML::SyntaxError: Unknown general entity "bar".>,
 #<Nokogiri::XML::SyntaxError: Bare ampersand found.>]
----------
```

Note that all of these parsers are consistent in flagging the use of a bare ampersand as a parsing error, and although the XML parsers recover differently, all of the HTML parsers recover consistently.

@strzibny Are you intentionally using `XML::Builder` for what looks like HTML content? Just curious, the behavior of libxml2's HTML parser is consistent, but I did want to suggest that you can avoid the second issue being reported (dropping the bare `&` in a text node) by using an HTML4 or HTML5 parser.

**Comment by flavorjones** [comment]
@strzibny Can you tell me what version of Nokogiri you're upgrading from? I went back to libxml2 2.9.10 (Nokogiri v1.11.3) and the behavior of the parser to replace bare ampersands in the `href` attribute hadn't changed since then.

**Comment by strzibny** [comment]
Thanks a lot for all the answers, as I said I wasn't sure if this is an actual bug, just that it surprised me. After thinking more about it, I believe I simply have to escape ampersand in cases when this previously work.

@flavorjones I was upgrading from 1.12.5 to 1.13.0 (and then 1.13.3) both on libxml2-2.9.13-1.fc35.x86_64.

Although I am still interested what change caused this, I am closing the issue as this is regarding invalid XML.

**Comment by flavorjones** [comment]
@strzibny I'm not able to reproduce what you're reporting using stock libxml2 2.9.13 and Nokogiri 1.12.5. Here's the script I'm using (note that I try both XML DOM parser and the XML Builder):

```ruby
#! /usr/bin/env ruby

require 'nokogiri'
require 'yaml'

puts Nokogiri::VERSION_INFO.to_yaml

html = <<~HTML
<html><body>
  <a href=\"http://www.example.com?foo=bar&bar=foo&amp;test=amp\"> foo & bar </a>
</body></html>
HTML

document = Nokogiri::XML::Document.parse(html)
puts document.to_xml
pp document.errors

puts "=========="

doc = Nokogiri::XML::Builder.new(encoding: 'UTF-8') do |xml|
  xml.root do
     xml.string({}) {  
        xml << "ss <a href=\"http://www.example.com?foo=bar&bar=foo&amp;test=amp\">sss</a> ss"
     }
  end
end
puts doc.to_xml
pp doc.doc.errors
```

Here's what I see:

```text
---
warnings: []
nokogiri:
  version: 1.12.5
  cppflags:
  - "-I/home/flavorjones/code/oss/nokogiri/ext/nokogiri"
  ldflags: []
ruby:
  version: 3.1.0
  platform: x86_64-linux
  gem_platform: x86_64-linux
  description: ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
  engine: ruby
libxml:
  source: system
  memory_management: ruby
  iconv_enabled: true
  compiled: 2.9.13
  loaded: 2.9.13
libxslt:
  source: system
  datetime_enabled: true
  compiled: 1.1.34
  loaded: 1.1.34
other_libraries:
  libgumbo: 1.0.0-nokogiri
<?xml version="1.0"?>
<html>
  <body>
  <a href="http://www.example.com?foo=bar=foo&amp;test=amp"> foo  bar </a>
</body>
</html>
[#<Nokogiri::XML::SyntaxError: 2:46: FATAL: EntityRef: expecting ';'>,
 #<Nokogiri::XML::SyntaxError: 2:71: FATAL: xmlParseEntityRef: no name>]
==========
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <string>ss <a href="http://www.example.com?foo=bar&amp;bar=foo&amp;test=amp">sss</a> ss</string>
</root>
[#<Nokogiri::XML::SyntaxError: 1:47: FATAL: EntityRef: expecting ';'>]
```

**Comment by strzibny** [comment]
@flavorjones Yet I see it there:

```
<html>
  <body>
  <a href="http://www.example.com?foo=bar=foo&amp;test=amp"> foo  bar </a>
</body>
</html>
```
Notice the missing `&`.

**Comment by strzibny** [comment]
@strzibny I run your script in both versions. The old version looks same like yours. The new one:

```
---
warnings: []
nokogiri:
  version: 1.13.0
  cppflags:
  - "-I/home/strzibny/.gem/ruby/3.0.3/gems/nokogiri-1.13.0-x86_64-linux/ext/nokogiri"
  - "-I/home/strzibny/.gem/ruby/3.0.3/gems/nokogiri-1.13.0-x86_64-linux/ext/nokogiri/include"
  - "-I/home/strzibny/.gem/ruby/3.0.3/gems/nokogiri-1.13.0-x86_64-linux/ext/nokogiri/include/libxml2"
  ldflags: []
ruby:
  version: 3.0.3
  platform: x86_64-linux
  gem_platform: x86_64-linux
  description: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
  engine: ruby
libxml:
  source: packaged
  precompiled: true
  patches:
  - 0001-Remove-script-macro-support.patch
  - 0002-Update-entities-to-remove-handling-of-ssi.patch
  - 0003-libxml2.la-is-in-top_builddir.patch
  - 0004-use-glibc-strlen.patch
  - 0005-avoid-isnan-isinf.patch
  - 0006-update-automake-files-for-arm64.patch
  - 0007-Fix-XPath-recursion-limit.patch
  - '0008-htmlParseComment-handle-abruptly-closed-comments.patch'
  - '0009-allow-wildcard-namespaces.patch'
  libxml2_path: "/home/strzibny/.gem/ruby/3.0.3/gems/nokogiri-1.13.0-x86_64-linux/ext/nokogiri"
  memory_management: ruby
  iconv_enabled: true
  compiled: 2.9.12
  loaded: 2.9.12
libxslt:
  source: packaged
  precompiled: true
  patches:
  - 0001-update-automake-files-for-arm64.patch
  - 0002-Fix-xml2-config-check-in-configure-script.patch
  datetime_enabled: true
  compiled: 1.1.34
  loaded: 1.1.34
other_libraries:
  zlib: 1.2.11
  libgumbo: 1.0.0-nokogiri
<?xml version="1.0"?>
<html>
  <body>
  <a href="http://www.example.com?foo=bar=foo&amp;test=amp"> foo  bar </a>
</body>
</html>
[#<Nokogiri::XML::SyntaxError: 2:46: FATAL: EntityRef: expecting ';'>,
 #<Nokogiri::XML::SyntaxError: 2:71: FATAL: xmlParseEntityRef: no name>]
==========
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <string>ss <a href="http://www.example.com?foo=bar=foo&amp;test=amp">sss</a> ss</string>
</root>
[#<Nokogiri::XML::SyntaxError: 1:47: FATAL: EntityRef: expecting ';'>]
```
