### ISSUE TITLE
[help] Nokogiri stops parsing @ ASCII-8BIT \xA0

### ISSUE THREAD

**Issue by aaronstillwell** [sparklemotion/nokogiri#2511]
**What problem are you trying to solve?**

I'm trying to parse a HTML document, encoded with `ASCII-8BIT` which features the `\xA0` character. Nokogiri seems to quietly stop parsing the document when encountering such a character, as per the examples below.

Is this expected behaviour? If so, what the recommended approach to parsing documents correctly encoded with this character?

**Please show your code!**

```ruby
#! /usr/bin/env ruby

require 'nokogiri'

html = <<-EOF
<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n

<head>\r\n
  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=us-ascii\" />\r\n<title></title>\r\n
  <meta name=\"generator\" content=\"foo\" />\r\n
</head>\r\n

<body>
  <div style=\"text-align:left;font-family:Arial, Helvetica, sans-serif; font-size: 10pt;\">
    <div>foo</div>
    <div>bar</div>
    <div>foo</div>
    <div>\xA0</div>
  </div>\r\n
  <div style=\"text-align:left;font-family:Arial, Helvetica, sans-serif; font-size: 10pt;\">
    <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget aliquet dui. Integer consectetur
      ante et
      libero semper, et egestas leo lacinia. In pretium lorem nec varius accumsan. Maecenas ornare bibendum tempus. Ut
      ultricies viverra tellus, et facilisis metus posuere eget. Fusce nec est magna. Curabitur ultricies turpis urna,
      sagittis efficitur eros aliquet vitae. Fusce commodo dictum turpis. Integer a ex laoreet, vehicula arcu ac,
      posuere
      eros. Aliquam ut quam fermentum, porttitor libero in, sagittis tellus. Donec vel ante turpis. Quisque scelerisque
      enim
      at enim ultricies porttitor.</div>
    <div>\xA0</div>
  </div>
  <div>\xA0</div>
  <div>\xA0</div>
</body>\r\n

</html>
EOF

doc = Nokogiri::HTML(html.force_encoding('ASCII-8BIT'))
pp doc
# #(Document:0x3fd3d380aa20 {
#   name = "document",
#   children = [
#     #(DTD:0x3fd3d38e3528 { name = "html" }),
#     #(Element:0x3fd3d38e3514 {
#       name = "html",
#       attributes = [
#         #(Attr:0x3fd3d38e26b4 {
#           name = "xmlns",
#           value = "http://www.w3.org/1999/xhtml"
#           })],
#       children = [
#         #(Text "\r\n" + "\n" + "\n"),
#         #(Element:0x3fd3d38e2650 {
#           name = "head",
#           children = [
#             #(Text "\r\n" + "\n" + "  "),
#             #(Element:0x3fd3d38ea56c {
#               name = "meta",
#               attributes = [
#                 #(Attr:0x3fd3d38ee9b4 {
#                   name = "http-equiv",
#                   value = "Content-Type"
#                   }),
#                 #(Attr:0x3fd3d38ee9a0 {
#                   name = "content",
#                   value = "text/html; charset=us-ascii"
#                   })]
#               }),
#             #(Text "\r\n"),
#             #(Element:0x3fd3d38ea4e0 { name = "title" }),
#             #(Text "\r\n" + "\n" + "  "),
#             #(Element:0x3fd3d38ea3dc {
#               name = "meta",
#               attributes = [
#                 #(Attr:0x3fd3d38f7460 { name = "name", value = "generator" }),
#                 #(Attr:0x3fd3d38f744c { name = "content", value = "foo" })]
#               }),
#             #(Text "\r\n" + "\n")]
#           }),
#         #(Text "\r\n" + "\n" + "\n"),
#         #(Element:0x3fd3d38e2614 {
#           name = "body",
#           children = [
#             #(Text "\n" + "  "),
#             #(Element:0x3fd3d38faed0 {
#               name = "div",
#               attributes = [
#                 #(Attr:0x3fd3d38fa278 {
#                   name = "style",
#                   value = "text-align:left;font-family:Arial, Helvetica, sans-serif; font-size: 10pt;"
#                   })],
#               children = [
#                 #(Text "\n" + "    "),
#                 #(Element:0x3fd3d38fa228 {
#                   name = "div",
#                   children = [ #(Text "foo")]
#                   }),
#                 #(Text "\n" + "    "),
#                 #(Element:0x3fd3d38fa200 {
#                   name = "div",
#                   children = [ #(Text "bar")]
#                   }),
#                 #(Text "\n" + "    "),
#                 #(Element:0x3fd3d38fa1d8 {
#                   name = "div",
#                   children = [ #(Text "foo")]
#                   }),
#                 #(Text "\n" + "    "),
#                 #(Element:0x3fd3d38fa1b0 { name = "div" })]
#               })]
#           })]
#       })]
#   })

doc = Nokogiri::HTML(html.force_encoding('UTF-8'))
pp doc
# #(Document:0x3ffa56092b2c {
#   name = "document",
#   children = [
#     #(DTD:0x3ffa56092460 { name = "html" }),
#     #(Element:0x3ffa5609244c {
#       name = "html",
#       attributes = [
#         #(Attr:0x3ffa5741733c {
#           name = "xmlns",
#           value = "http://www.w3.org/1999/xhtml"
#           })],
#       children = [
#         #(Text "\r\n" + "\n" + "\n"),
#         #(Element:0x3ffa574172c4 {
#           name = "head",
#           children = [
#             #(Text "\r\n" + "\n" + "  "),
#             #(Element:0x3ffa5741f7a8 {
#               name = "meta",
#               attributes = [
#                 #(Attr:0x3ffa5741e664 {
#                   name = "http-equiv",
#                   value = "Content-Type"
#                   }),
#                 #(Attr:0x3ffa5741e600 {
#                   name = "content",
#                   value = "text/html; charset=us-ascii"
#                   })]
#               }),
#             #(Text "\r\n"),
#             #(Element:0x3ffa5741f76c { name = "title" }),
#             #(Text "\r\n" + "\n" + "  "),
#             #(Element:0x3ffa5741f744 {
#               name = "meta",
#               attributes = [
#                 #(Attr:0x3ffa5609b63c { name = "name", value = "generator" }),
#                 #(Attr:0x3ffa5609b628 { name = "content", value = "foo" })]
#               }),
#             #(Text "\r\n" + "\n")]
#           }),
#         #(Text "\r\n" + "\n" + "\n"),
#         #(Element:0x3ffa57417288 {
#           name = "body",
#           children = [
#             #(Text "\n" + "  "),
#             #(Element:0x3ffa5609ebe8 {
#               name = "div",
#               attributes = [
#                 #(Attr:0x3ffa560a34b8 {
#                   name = "style",
#                   value = "text-align:left;font-family:Arial, Helvetica, sans-serif; font-size: 10pt;"
#                   })],
#               children = [
#                 #(Text "\n" + "    "),
#                 #(Element:0x3ffa560a3468 {
#                   name = "div",
#                   children = [ #(Text "foo")]
#                   }),
#                 #(Text "\n" + "    "),
#                 #(Element:0x3ffa560a3418 {
#                   name = "div",
#                   children = [ #(Text "bar")]
#                   }),
#                 #(Text "\n" + "    "),
#                 #(Element:0x3ffa560a33f0 {
#                   name = "div",
#                   children = [ #(Text "foo")]
#                   }),
#                 #(Text "\n" + "    "),
#                 #(Element:0x3ffa560a33c8 {
#                   name = "div",
#                   children = [ #(Text "\xA0")]
#                   }),
#                 #(Text "\n" + "  ")]
#               }),
#             #(Text "\r\n" + "\n" + "  "),
#             #(Element:0x3ffa5609ebac {
#               name = "div",
#               attributes = [
#                 #(Attr:0x3ffa560b34f8 {
#                   name = "style",
#                   value = "text-align:left;font-family:Arial, Helvetica, sans-serif; font-size: 10pt;"
#                   })],
#               children = [
#                 #(Text "\n" + "    "),
#                 #(Element:0x3ffa560b3430 {
#                   name = "div",
#                   children = [
#                     #(Text "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget aliquet dui. Integer consectetur\n" +
#                       "      ante et\n" +
#                       "      libero semper, et egestas leo lacinia. In pretium lorem nec varius accumsan. Maecenas ornare bibendum tempus. Ut\n" +
#                       "      ultricies viverra tellus, et facilisis metus posuere eget. Fusce nec est magna. Curabitur ultricies turpis urna,\n" +
#                       "      sagittis efficitur eros aliquet vitae. Fusce commodo dictum turpis. Integer a ex laoreet, vehicula arcu ac,\n" +
#                       "      posuere\n" +
#                       "      eros. Aliquam ut quam fermentum, porttitor libero in, sagittis tellus. Donec vel ante turpis. Quisque scelerisque\n" +
#                       "      enim\n" +
#                       "      at enim ultricies porttitor.")]
#                   }),
#                 #(Text "\n" + "    "),
#                 #(Element:0x3ffa560b33cc {
#                   name = "div",
#                   children = [ #(Text "\xA0")]
#                   }),
#                 #(Text "\n" + "  ")]
#               }),
#             #(Text "\n" + "  "),
#             #(Element:0x3ffa5609eb84 {
#               name = "div",
#               children = [ #(Text "\xA0")]
#               }),
#             #(Text "\n" + "  "),
#             #(Element:0x3ffa5609eb48 {
#               name = "div",
#               children = [ #(Text "\xA0")]
#               }),
#             #(Text "\n")]
#           }),
#         #(Text "\r\n" + "\n" + "\n")]
#       })]
#   })
```

**Environment**

```
# Nokogiri (1.13.3)
    ---
    warnings: []
    nokogiri:
      version: 1.13.3
      cppflags:
      - "-I/home/app/vendor/bundle/ruby/3.1.0/gems/nokogiri-1.13.3-x86_64-linux/ext/nokogiri"
      - "-I/home/app/vendor/bundle/ruby/3.1.0/gems/nokogiri-1.13.3-x86_64-linux/ext/nokogiri/include"
      - "-I/home/app/vendor/bundle/ruby/3.1.0/gems/nokogiri-1.13.3-x86_64-linux/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.1.1
      platform: x86_64-linux
      gem_platform: x86_64-linux
      description: ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - '0008-htmlParseComment-handle-abruptly-closed-comments.patch'
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-Revert-Different-approach-to-fix-quadratic-behavior.patch
      libxml2_path: "/home/app/vendor/bundle/ruby/3.1.0/gems/nokogiri-1.13.3-x86_64-linux/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.13
      loaded: 2.9.13
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.35
      loaded: 1.1.35
    other_libraries:
      zlib: 1.2.11
      libgumbo: 1.0.0-nokogiri
```

**Additional context**

The way the HTML is presented in my use case is not within my control.
