### ISSUE TITLE
Replacing a node breaks indent

### ISSUE THREAD

**Issue by svoop** [sparklemotion/nokogiri#2521]
Maybe a bug, could also be a misunderstanding on my part.

Given a simple, but un-pretty XML document. Thanks to parsing with `&:noblanks` it can be pretty printed like so:

```ruby
require 'nokogiri'
xml = <<~END
  <root>
  <first><child>foo</child></first>
  <second><child>bar</child></second>
  </root>
END
doc = Nokogiri.XML(xml, &:noblanks)
puts doc.to_xml(indent: 2)
```

```xml
<?xml version="1.0"?>
<root>
  <first>
    <child>foo</child>
  </first>
  <second>
    <child>bar</child>
  </second>
</root>
```

---

I now would like to replace the `second` node with some new un-pretty markup, however, this does away with the pretty printing:

```ruby
require 'nokogiri'
xml = <<~END
  <root>
  <first><child>foo</child></first>
  <second><child>bar</child></second>
  </root>
END
doc = Nokogiri.XML(xml, &:noblanks)
xml = <<~END
  <third>
  <child>baz</child>
  </third>
END
doc.at_css('second').replace(xml)
puts doc.to_xml(indent: 2)
```

```xml
<?xml version="1.0"?>
<root><first><child>foo</child></first><third>
<child>baz</child>
</third>
</root>
```

---

Things look a little better when the trailing whitespace of the replacing markup is stripped, however, indent is still off:

```ruby
require 'nokogiri'
xml = <<~END
  <root>
  <first><child>foo</child></first>
  <second><child>bar</child></second>
  </root>
END
doc = Nokogiri.XML(xml, &:noblanks)
xml = <<~END
  <third>
  <child>baz</child>
  </third>
END
doc.at_css('second').replace(xml.chomp)
puts doc.to_xml(indent: 2)
```

```xml
<?xml version="1.0"?>
<root>
  <first>
    <child>foo</child>
  </first>
  <third>
<child>baz</child>
</third>
</root>
```

---

The only workaround is to remove all whitespace between the nodes which yields the expected result:

```ruby
require 'nokogiri'
xml = <<~END
  <root>
  <first><child>foo</child></first>
  <second><child>bar</child></second>
  </root>
END
doc = Nokogiri.XML(xml, &:noblanks)
xml = "<third><child>baz</child></third>"
doc.at_css('second').replace(xml)
puts doc.to_xml(indent: 2)
```

```xml
<?xml version="1.0"?>
<root>
  <first>
    <child>foo</child>
  </first>
  <third>
    <child>baz</child>
  </third>
</root>
```

Is there a (better) way to replace a node and maintain correct indent or could this be a bug?

---

```
% nokogiri -v
# Nokogiri (1.13.4)
    ---
    warnings: []
    nokogiri:
      version: 1.13.4
      cppflags:
      - "-I/Users/me/.gem/ruby/3.1.0/gems/nokogiri-1.13.4-arm64-darwin/ext/nokogiri"
      - "-I/Users/me/.gem/ruby/3.1.0/gems/nokogiri-1.13.4-arm64-darwin/ext/nokogiri/include"
      - "-I/Users/me/.gem/ruby/3.1.0/gems/nokogiri-1.13.4-arm64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.1.2
      platform: arm64-darwin21
      gem_platform: arm64-darwin-21
      description: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - '0008-htmlParseComment-handle-abruptly-closed-comments.patch'
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-Revert-Different-approach-to-fix-quadratic-behavior.patch
      libxml2_path: "/Users/me/.gem/ruby/3.1.0/gems/nokogiri-1.13.4-arm64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.13
      loaded: 2.9.13
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.35
      loaded: 1.1.35
    other_libraries:
      zlib: 1.2.12
      libiconv: '1.16'
      libgumbo: 1.0.0-nokogiri
```
