### ISSUE TITLE
upstream html5lib-tests failure

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#2567]
This commit upstream:

> https://github.com/html5lib/html5lib-tests/issues/143

is failing with this message:

```
Failure:
TestHtml5TreeConstructionTests20#test_39 [/home/flavorjones/code/oss/nokogiri/test/html5/test_tree_construction.rb:96]
Minitest::Assertion: Wrong number of errors for <!doctype html><button><p></button>x.
Expected: 3
  Actual: 0
```

This failure can be seen in the relevant "upstream" CI job, e.g. https://github.com/sparklemotion/nokogiri/runs/6722287019?check_suite_focus=true#step:8:4197

I'm not sure how to fix this and need help. @stevecheckoway I'd be happy to pair with you on it so you can start transferring some of the expertise you've got on the gumbo parser.

**Comment by stevecheckoway** [comment]
I was trying to dig into this and I'm afraid I'm running into a series of problems, only some of which are likely to be related to Nokogiri.

First problem: When I try to compile the C extension by running `bundle exec rake`, it fails. Here's the relevant section of mkmf.log.
```
DYLD_FALLBACK_LIBRARY_PATH=.:/nix/store/i7k4f3mw9nnnwvnznrmm38iy847i7yxc-ruby-3.1.2/lib "clang -o conftest -I/nix/store/i7k4f3mw9nnnwvnznrmm38iy847i7yxc-ruby-3.1.2/include/ruby-3.1.0/x86_64-darwin17 -I/nix/store/i7k4f3mw9nnnwvnznrmm38iy847i7yxc-ruby-3.1.2/include/ruby-3.1.0/ruby/backward -I/nix/store/i7k4f3mw9nnnwvnznrmm38iy847i7yxc-ruby-3.1.2/include/ruby-3.1.0 -I../../../../ext/nokogiri -I/Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxml2/2.9.14/include/libxml2 -I/Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxslt/1.1.35/include -I/Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxml2/2.9.14/include/libxml2 -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -DNOKOGIRI_PACKAGED_LIBRARIES -DNOKOGIRI_LIBXML2_PATCHES="\"0001-Remove-script-macro-support.patch 0002-Update-entities-to-remove-handling-of-ssi.patch 0003-libxml2.la-is-in-top_builddir.patch 0004-use-glibc-strlen.patch 0006-update-automake-files-for-arm64.patch 0008-htmlParseComment-handle-abruptly-closed-comments.patch 0009-allow-wildcard-namespaces.patch\"" -DNOKOGIRI_LIBXSLT_PATCHES="\"0001-update-automake-files-for-arm64.patch\"" -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens -Wundef  -fno-common -pipe -std=c99 -Wno-declaration-after-statement -g -Winline -Wmissing-noreturn conftest.c  -L. -L/nix/store/i7k4f3mw9nnnwvnznrmm38iy847i7yxc-ruby-3.1.2/lib -L/Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxml2/2.9.14/lib -L/Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxslt/1.1.35/lib -L. -fstack-protector-strong -L/nix/store/kn3sb477vkh5rqh9ss8b7xfkwfnl1lb9-gettext-0.21/lib -L/nix/store/r1hk06mv95z1n6lf6d6gx2x64s0ysq2c-file-5.41/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ruby-2.7.6/lib -L/nix/store/03g1w9ssw6w2ay9jgzn0ankx162ddcdd-libffi-3.4.2-dev/lib -L/nix/store/8bvsa5cdnhygy6fzsciq40ir9x8fl3is-ncurses-6.3-dev/lib -L/nix/store/w05k1yl7rqp0r5kkv0gd7hwq0848disd-zlib-1.2.12-dev/lib -L/nix/store/wkl4ambiw6hx5h27fdi8jyah3rk9balk-openssl-1.1.1o-dev/lib -L/nix/store/9gcqdisglw28k37q12fkliqraziiy1db-gdbm-1.23/lib -L/nix/store/qndd43fqa9ygcban7q7sbp7z2xyyc0ba-libyaml-0.2.5/lib -L/nix/store/46i7p12y0xhbrwmky9c0zkbqj2ylbhv6-libiconv-50/lib -L/nix/store/y0cz4m93wg611dfj0pym65v41hwwav68-objc4-709.1/lib -L/nix/store/p9phdd7xbzixriss330dlndbnmsfn12q-libunwind-35.3/lib -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-clang-wrapper-11.1.0/resource-root/lib -L/nix/store/4df4jhlj71vblmxhrr7dkkqpak8a42c8-Libsystem-1238.60.2/lib    /Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxslt/1.1.35/lib/libexslt.a -lm -liconv -lpthread -lz /Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxml2/2.9.14/lib/libxml2.a /Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxslt/1.1.35/lib/libxslt.a -lm -liconv -lpthread -lz /Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxml2/2.9.14/lib/libxml2.a -llzma -lruby-3.1.2 /Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxslt/1.1.35/lib/libexslt.a -lm -liconv -lpthread -lz /Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxml2/2.9.14/lib/libxml2.a /Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxslt/1.1.35/lib/libxslt.a -lm -liconv -lpthread -lz /Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxml2/2.9.14/lib/libxml2.a -llzma  "
conftest.c:16:13: error: conflicting types for 'xmlParseDoc'
extern void xmlParseDoc();
            ^
/Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxml2/2.9.14/include/libxml2/libxml/parser.h:844:3: note: previous declaration is here
                xmlParseDoc             (const xmlChar *cur);
                ^
conftest.c:17:27: error: too few arguments to function call, single argument 'cur' was not specified
int t(void) { xmlParseDoc(); return 0; }
              ~~~~~~~~~~~ ^
/Users/steve/programming/nokogiri/ports/x86_64-darwin17/libxml2/2.9.14/include/libxml2/libxml/parser.h:844:3: note: 'xmlParseDoc' declared here
                xmlParseDoc             (const xmlChar *cur);
                ^
2 errors generated.
```
I'm not sure why the conftest.c includes both the header for `xmlParseDoc` and its own declaration. For link tests, I'd expect it to not include the header.

I tested this with Ruby 3.1.2 and Ruby 2.7.6.

Second problem, when I look at that output, I'm seeing `-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ruby-2.7.6/lib` and I have absolutely no idea why it's trying to do anything with Ruby 2.7.6 and I don't know what that all `e` hash is supposed to be. Unsurprisingly, that directory does not exist. The correct path is `/nix/store/srkrmhv3512xyakgfcnd9ma1nrh6hszg-ruby-2.7.6/`. This has got to be an issue with Nix, but I'm not sure where exactly the issue is.

Somewhat amusingly, Nokogiri is the example the Nix documentation shows for installing a gem. And indeed, I can install it.
```
% nix-shell -p "ruby_3_1.withPackages (ps: [ ps.nokogiri ])" --run 'nokogiri --version'
# Nokogiri (1.13.3)
    ---
    warnings: []
    nokogiri:
      version: 1.13.3
      cppflags:
      - "-I/nix/store/c9xl32mbvwcyb9jq23wxs3cajk0rcbgh-ruby3.1.2-nokogiri-1.13.3/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.3/ext/nokogiri"
      ldflags: []
    ruby:
      version: 3.1.2
      platform: x86_64-darwin17
      gem_platform: x86_64-darwin-17
      description: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin17]
      engine: ruby
    libxml:
      source: system
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.14
      loaded: 2.9.14
    libxslt:
      source: system
      datetime_enabled: true
      compiled: 1.1.35
      loaded: 1.1.35
    other_libraries:
      libgumbo: 1.0.0-nokogiri
```

A third issue I encountered although I'm not sure exactly how I managed to get to this point since I cannot replicate it is running `rake` modified several source files, removing  the frozen strings magic comment which caused a subsequent run of `rake` to complain about.

And I'm kinda running out of steam on this right now. Any idea how to fix the `conflicting types for 'xmlParseDoc'` error?
