### ISSUE TITLE
Unquoted attributes in HTML [help]

### ISSUE THREAD

**Issue by raquelhortab** [sparklemotion/nokogiri#2582]
**What problem are you trying to solve?**

I am using nokogiri to check whether a text is a well-formed HTML document. To do so I'm using 

```
Nokogiri::HTML::Document.parse(html)
```

I want to check all tags are properly closed, and the function above does not do that, so I used 

```
Nokogiri::XML.parse(html){|config|config.strict}
```
However, this function does not allow some syntax that HTML allows: unquoted attribute values. For instance, I could have this tag:

```
<table border=1>...</table>
```
which would be a correct HTML tag but not a correct XML tag.

The question is, how can I check the correctness of the HTML code without being so XML-strict? 

**Environment**

I'm using ruby 1.9.3 so I cannot use the latest version.

```
# Nokogiri (1.6.7)
    ---
    warnings: []
    nokogiri: 1.6.7
    ruby:
      version: 1.9.3
      platform: x86_64-linux
      description: ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/raquel/.rvm/gems/ruby-1.9.3-p551@codelearn/gems/nokogiri-1.6.7/ports/x86_64-pc-linux-gnu/libxml2/2.9.2"
      libxslt_path: "/home/raquel/.rvm/gems/ruby-1.9.3-p551@codelearn/gems/nokogiri-1.6.7/ports/x86_64-pc-linux-gnu/libxslt/1.1.28"
      libxml2_patches:
      - 0001-Revert-Missing-initialization-for-the-catalog-module.patch
      - 0002-Fix-missing-entities-after-CVE-2014-3660-fix.patch
      - 0003-Stop-parsing-on-entities-boundaries-errors.patch
      - 0004-Cleanup-conditional-section-error-handling.patch
      - 0005-CVE-2015-1819-Enforce-the-reader-to-run-in-constant-.patch
      - 0006-Another-variation-of-overflow-in-Conditional-section.patch
      - 0007-Fix-an-error-in-previous-Conditional-section-patch.patch
      - '0008-CVE-2015-8035-Fix-XZ-compression-support-loop.patch'
      - '0009-Updated-config.guess.patch'
      - 0010-Fix-parsering-short-unclosed-comment-uninitialized-access.patch
      libxslt_patches:
      - 0001-Adding-doc-update-related-to-1.1.28.patch
      - 0002-Fix-a-couple-of-places-where-f-printf-parameters-wer.patch
      - 0003-Initialize-pseudo-random-number-generator-with-curre.patch
      - 0004-EXSLT-function-str-replace-is-broken-as-is.patch
      - 0006-Fix-str-padding-to-work-with-UTF-8-strings.patch
      - 0007-Separate-function-for-predicate-matching-in-patterns.patch
      - '0008-Fix-direct-pattern-matching.patch'
      - '0009-Fix-certain-patterns-with-predicates.patch'
      - 0010-Fix-handling-of-UTF-8-strings-in-EXSLT-crypto-module.patch
      - 0013-Memory-leak-in-xsltCompileIdKeyPattern-error-path.patch
      - 0014-Fix-for-bug-436589.patch
      - 0015-Fix-mkdir-for-mingw.patch
      - 0016-Fix-for-type-confusion-in-preprocessing-attributes.patch
      - 0017-Updated-config.guess.patch
      compiled: 2.9.2
      loaded: 2.9.2
```

PD: I realized [I am not the only one](https://stackoverflow.com/questions/38637042/nokogiri-xml-parser-with-bad-attribute-values) who's had this problem

Thanks
