### ISSUE TITLE
[install] Rails 7 with TruffleRuby does fail on nokogiri installation

### ISSUE THREAD

**Issue by MrWormHole** [sparklemotion/nokogiri#2604]
**Have you read and followed the installation tutorial at http://www.nokogiri.org/tutorials/installing_nokogiri.html?**

- [X] Yes!

**What is the complete output of `gem install` or `bundle install`?**

```
Using rails 7.0.3.1
Bundle complete! 14 Gemfile dependencies, 71 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  importmap:install
rails aborted!
/home/mrwormhole/.rbenv/versions/truffleruby-dev/lib/gems/gems/nokogiri-1.13.8-x86_64-linux/lib/nokogiri/3.0/nokogiri.so: undefined symbol: rb_eTypeError
<internal:core> core/kernel.rb:293:in `require_relative'
<internal:core> core/kernel.rb:293:in `require_relative'
<internal:core> core/kernel.rb:234:in `gem_original_require'
<internal:core> core/kernel.rb:234:in `gem_original_require'
<internal:core> core/kernel.rb:234:in `gem_original_require'
<internal:core> core/kernel.rb:234:in `gem_original_require'
/home/mrwormhole/Desktop/Hobby/Rails/yolo_app/config/application.rb:3:in `<top (required)>'
<internal:core> core/kernel.rb:293:in `require_relative'
/home/mrwormhole/Desktop/Hobby/Rails/yolo_app/Rakefile:4:in `<top (required)>'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:234:in `gem_original_require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
       rails  turbo:install stimulus:install
rails aborted!
/home/mrwormhole/.rbenv/versions/truffleruby-dev/lib/gems/gems/nokogiri-1.13.8-x86_64-linux/lib/nokogiri/3.0/nokogiri.so: undefined symbol: rb_eTypeError
<internal:core> core/kernel.rb:293:in `require_relative'
<internal:core> core/kernel.rb:293:in `require_relative'
<internal:core> core/kernel.rb:234:in `gem_original_require'
<internal:core> core/kernel.rb:234:in `gem_original_require'
<internal:core> core/kernel.rb:234:in `gem_original_require'
<internal:core> core/kernel.rb:234:in `gem_original_require'
/home/mrwormhole/Desktop/Hobby/Rails/yolo_app/config/application.rb:3:in `<top (required)>'
<internal:core> core/kernel.rb:293:in `require_relative'
/home/mrwormhole/Desktop/Hobby/Rails/yolo_app/Rakefile:4:in `<top (required)>'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:234:in `gem_original_require'
bin/rails:4:in `<main>'
```

**If installation completed but is broken, what is the complete output from `nokogiri -v`?**

```
# Nokogiri (1.13.8)
    ---
    warnings: []
    nokogiri:
      version: 1.13.8
      cppflags:
      - "-I/home/mrwormhole/.rbenv/versions/truffleruby-dev/lib/gems/gems/nokogiri-1.13.8/ext/nokogiri"
      - "-I/home/mrwormhole/.rbenv/versions/truffleruby-dev/lib/gems/gems/nokogiri-1.13.8/ext/nokogiri/include"
      - "-I/home/mrwormhole/.rbenv/versions/truffleruby-dev/lib/gems/gems/nokogiri-1.13.8/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.0.3
      platform: x86_64-linux
      gem_platform: x86_64-linux
      description: truffleruby 22.3.0-dev-0e42c2a6, like ruby 3.0.3, GraalVM CE Native
        [x86_64-linux]
      engine: truffleruby
    libxml:
      source: packaged
      precompiled: false
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - '0008-htmlParseComment-handle-abruptly-closed-comments.patch'
      - '0009-allow-wildcard-namespaces.patch'
      libxml2_path: "/home/mrwormhole/.rbenv/versions/truffleruby-dev/lib/gems/gems/nokogiri-1.13.8/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.14
      loaded: 2.9.14
    libxslt:
      source: packaged
      precompiled: false
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.35
      loaded: 1.1.35
    other_libraries:
      libgumbo: 1.0.0-nokogiri
```

**If installation failed during compilation, what are the complete contents of the `mkmf.log` file generated during the failed installation?**

I don't have that file

**Tell us about your system!**

What is the output from `ruby -v`?
truffleruby 22.3.0-dev-0e42c2a6, like ruby 3.0.3, GraalVM CE Native [x86_64-linux]

What is the output from `gem -v`?
3.2.32

What is the output from `gem env`?

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.32
  - RUBY VERSION: 3.0.3 (2022-07-23 patchlevel 0) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/mrwormhole/.rbenv/versions/truffleruby-dev/lib/gems
  - USER INSTALLATION DIRECTORY: /home/mrwormhole/.local/share/gem/truffleruby/3.0.3.7
  - RUBY EXECUTABLE: /home/mrwormhole/.rbenv/versions/truffleruby-dev/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/mrwormhole/.rbenv/versions/truffleruby-dev/bin
  - SPEC CACHE DIRECTORY: /home/mrwormhole/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/runner/work/truffleruby-dev-builder/truffleruby-dev-builder/etc
  - RUBYGEMS PLATFORMS:
     - ruby
  - GEM PATHS:
     - /home/mrwormhole/.rbenv/versions/truffleruby-dev/lib/gems
     - /home/mrwormhole/.local/share/gem/truffleruby/3.0.3.7
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/mrwormhole/.rbenv/versions/truffleruby-dev/bin
     - /home/mrwormhole/.rbenv/libexec
     - /home/mrwormhole/.rbenv/plugins/ruby-build/bin
     - /home/mrwormhole/.rbenv/plugins/rbenv-vars/bin
     - /home/mrwormhole/.rbenv/shims
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/bin
     - /usr/sbin
     - /home/mrwormhole/.local/share/JetBrains/Toolbox/scripts
     - /usr/local/go/bin
     - /home/mrwormhole/go/bin
     - /home/mrwormhole/.arkade/bin/
     - /home/mrwormhole/.cargo/bin
     - /home/mrwormhole/.rbenv/bin
     - /home/mrwormhole/.rbenv/plugins/ruby-build/bin
```

If you're using Bundler:
- what is the output from `bundle version`?  

Bundler version 2.3.18 (2022-07-14 commit fc31b7f7d9)

- what is the output from `bundle config`? (Take care to redact any credentials)

Don't have that, says `Settings are listed in order of priority. The top value will be used.`

If Linux or a BSD variant, please note:
- Fedora 36 
- Linux sourbrownie 5.18.11-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jul 12 22:52:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- the contents of `/etc/lsb-release`.
```LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 36 (Thirty Six)
Release:	36
Codename:	ThirtySix
```
