### ISSUE TITLE
v1.13.0 XML::Document drops ampersand when parsing in-context fragments

### ISSUE THREAD

**Issue by tylerjc** [sparklemotion/nokogiri#2655]
**Please describe the bug**

* https://github.com/sparklemotion/nokogiri/releases/tag/v1.13.0
* There's some kind of issue/change between these versions that is eating ampersand characters (&). As far as I'm aware, this isn't happening with any other characters, but definitely could be.
* We had upgraded to v1.13.8 during our Rails upgrade, and that's when we started noticing this issue. We backtracked the versions to figure out when it started happening, and narrowed it down to v1.12.5 last working as expected.

**Help us reproduce what you're seeing**

<img width="765" alt="image" src="https://user-images.githubusercontent.com/87337138/193338379-4dbacbfb-80d4-49d7-9641-e16bd96ebe0b.png">
<img width="763" alt="image" src="https://user-images.githubusercontent.com/87337138/193338436-8c576430-e8d7-423e-90c7-55e6e3ac6d69.png">

**Environment**

```
# Nokogiri (1.13.8)
    ---
    warnings: []
    nokogiri:
      version: 1.13.8
      cppflags:
      - "-I/Users/tylercook/.rvm/gems/ruby-2.6.1/gems/nokogiri-1.13.8-x86_64-darwin/ext/nokogiri"
      - "-I/Users/tylercook/.rvm/gems/ruby-2.6.1/gems/nokogiri-1.13.8-x86_64-darwin/ext/nokogiri/include"
      - "-I/Users/tylercook/.rvm/gems/ruby-2.6.1/gems/nokogiri-1.13.8-x86_64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.6.1
      platform: x86_64-darwin20
      gem_platform: x86_64-darwin-20
      description: ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin20]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - '0008-htmlParseComment-handle-abruptly-closed-comments.patch'
      - '0009-allow-wildcard-namespaces.patch'
      libxml2_path: "/Users/tylercook/.rvm/gems/ruby-2.6.1/gems/nokogiri-1.13.8-x86_64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.14
      loaded: 2.9.14
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.35
      loaded: 1.1.35
    other_libraries:
      zlib: 1.2.12
      libiconv: '1.16'
      libgumbo: 1.0.0-nokogiri
```
