### ISSUE TITLE
On first build, racc and rex modify files

### ISSUE THREAD

**Issue by stevecheckoway** [sparklemotion/nokogiri#2771]
**Please describe the bug**

The first time I clone the nokogiri repo and build it, racc and rex make changes to two files:

```diff
diff --git a/lib/nokogiri/css/parser.rb b/lib/nokogiri/css/parser.rb
index 2299092a..7c9f4785 100644
--- a/lib/nokogiri/css/parser.rb
+++ b/lib/nokogiri/css/parser.rb
@@ -1,7 +1,6 @@
-# frozen_string_literal: true
 #
 # DO NOT MODIFY!!!!
-# This file is automatically generated by Racc 1.6.0
+# This file is automatically generated by Racc 1.6.2
 # from Racc grammar file "".
 #

diff --git a/lib/nokogiri/css/tokenizer.rb b/lib/nokogiri/css/tokenizer.rb
index d2a5b2e7..6eba7175 100644
--- a/lib/nokogiri/css/tokenizer.rb
+++ b/lib/nokogiri/css/tokenizer.rb
@@ -1,4 +1,3 @@
-# frozen_string_literal: true
 #--
 # DO NOT MODIFY!!!!
 # This file is automatically generated by rex 1.0.7
```

**Help us reproduce what you're seeing**

```
$ git clone https://github.com/sparklemotion/nokogiri
$ cd nokogiri
$ bundle config set --local path vendor/bundle
$ bundle install
$ bundle exec rake
$ bundle exec rake rubocop
```

The first use of `rake` succeeds. The second fails:

```
Running RuboCop...
Inspecting 193 files
.................................................................................................................................................................................................

193 files inspected, no offenses detected
Running RuboCop...
Inspecting 2 files
CC

Offenses:

lib/nokogiri/css/parser.rb:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
#
^
lib/nokogiri/css/tokenizer.rb:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
#--
^

2 files inspected, 2 offenses detected, 2 offenses autocorrectable
RuboCop failed!
```

**Expected behavior**

I expect the first `rake` to not modify files.

**Environment**

```
# Nokogiri (1.14.1.dev)
    ---
    warnings: []
    nokogiri:
      version: 1.14.1.dev
      cppflags:
      - "-I/private/tmp/nokogiri/ext/nokogiri"
      - "-I/private/tmp/nokogiri/ext/nokogiri/include"
      - "-I/private/tmp/nokogiri/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.1.2
      platform: arm64-darwin22
      gem_platform: arm64-darwin-22
      description: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin22]
      engine: ruby
    libxml:
      source: packaged
      precompiled: false
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      libxml2_path: "/private/tmp/nokogiri/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.10.3
      loaded: 2.10.3
    libxslt:
      source: packaged
      precompiled: false
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.37
      loaded: 1.1.37
    other_libraries:
      libgumbo: 1.0.0-nokogiri
```

**Additional context**

After `git checkout lib` to reset the files, `bundle exec rake` will not modify them further.

I believe this is a time stamp issue. On the first clone, `parser.rb`'s modified time is the same as `parser.y`'s which causes `rake` to rebuild `parser.rb`. If I subsequently `git checkout lib`, then the modified time is updated once again so that `parser.rb` will be newer than `parser.y`.

This is easy to trigger by touching `parser.y` and then running `rake` again which will rebuild `parser.rb` without the magic comment.
