### ISSUE TITLE
[bug] `write_to` fails in Nokogiri 1.14.0 when writing to an IO that doesn't implement `external_encoding`, such as `Zip::OutputStream`

### ISSUE THREAD

**Issue by dmolesUC** [sparklemotion/nokogiri#2773]
**Please describe the bug**

In Nokogiri 1.14.0, `Node.write_to` calls `external_encoding` on the output stream. (I'm not sure why it does this as from the [IO](https://ruby-doc.org/core-3.1.2/IO.html#method-i-external_encoding) and [Encoding](https://ruby-doc.org/core-3.1.2/Encoding.html#top) docs `external_encoding` appears to be only for reading, but whatever.)

This fails when the underlying output stream is not an actual IO but only a mostly-IO-like object such as [`Zip::OutputStream`](https://www.rubydoc.info/github/rubyzip/rubyzip/Zip/OutputStream).

This was not an issue in 1.13.x, so I'm guessing it's related to https://github.com/sparklemotion/nokogiri/commit/795464cec3a3ae96e0f929aa6226d03722108ce9.

**Help us reproduce what you're seeing**

```ruby
#!/usr/bin/env ruby

require 'nokogiri'
require 'minitest/autorun'
require 'zip'

class Test < MiniTest::Spec
  before { @tmpdir = Dir.mktmpdir }
  after { FileUtils.rm_rf(@tmpdir) }

  describe "Node#write_to" do
    it "should write to a Zip::OutputStream" do
      doc = Nokogiri::XML("<test/>")

      zipfile_path = File.join(@tmpdir, 'test.zip')
      Zip::OutputStream.open(zipfile_path) do |out|
        out.put_next_entry('test.xml')
        doc.write_to(out, encoding: 'UTF-8')
      end
    end
  end
end
```

**Expected behavior**

- Test above should complete without errors.

**Actual behavior**

- Test fails with

  ```none
  NoMethodError:
    undefined method `external_encoding' for #<Zip::OutputStream:0x0000000131dece98>
  # /Users/david/.rvm/gems/ruby-2.7.5/gems/nokogiri-1.14.0-arm64-darwin/lib/nokogiri/xml/node.rb:1368:in `native_write_to'
  # /Users/david/.rvm/gems/ruby-2.7.5/gems/nokogiri-1.14.0-arm64-darwin/lib/nokogiri/xml/node.rb:1368:in `write_to'
  # /Users/david/.rvm/gems/ruby-2.7.5/gems/nokogiri-1.14.0-arm64-darwin/lib/nokogiri/html5/node.rb:37:in `write_to'  
  ```

**Environment**

```
# Nokogiri (1.14.0)
    ---
    warnings: []
    nokogiri:
      version: 1.14.0
      cppflags:
      - "-I/Users/david/.rvm/gems/ruby-2.7.5/gems/nokogiri-1.14.0-arm64-darwin/ext/nokogiri"
      - "-I/Users/david/.rvm/gems/ruby-2.7.5/gems/nokogiri-1.14.0-arm64-darwin/ext/nokogiri/include"
      - "-I/Users/david/.rvm/gems/ruby-2.7.5/gems/nokogiri-1.14.0-arm64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.7.5
      platform: arm64-darwin21
      gem_platform: arm64-darwin-21
      description: ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [arm64-darwin21]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      libxml2_path: "/Users/david/.rvm/gems/ruby-2.7.5/gems/nokogiri-1.14.0-arm64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.10.3
      loaded: 2.10.3
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.37
      loaded: 1.1.37
    other_libraries:
      zlib: 1.2.13
      libiconv: '1.17'
      libgumbo: 1.0.0-nokogiri
```

**Additional context**

Above test requires RubyZip; tested with RubyZip 2.3.2.
