### ISSUE TITLE
[bug] extra </span> inserted after Nokogiri::HTML.parse

### ISSUE THREAD

**Issue by seanstory** [sparklemotion/nokogiri#2796]
**Please describe the bug**

I'm attempting to parse html content from a site I do not control. Specifically, https://2e.aonprd.com. 
I'm taking the raw HTMl and attempting to extract text content, excluding common header and footer text, to use for a search usecase. My plan was to do something like:

```
html_content = get_html_content(url)
parsed_data = Nokogiri::HTML.parse(html_content)
text_i_care_about = parsed_data.at_css('[id="ctl00_RadDrawer1_Content_MainContent_DetailedOutput"]').text # forgive the long selector
```

However, I've noticed that some pages are getting `""` content.

When I go to browser dev tools and access text by the selector with `$$("#ctl00_RadDrawer1_Content_MainContent_DetailedOutput").map(e=>e.textContent)`, I get the text I'm expecting, so it's not an issue with having gotten the selector wrong.

When I step through with irb, I can see that an extra `</span>` is being inserted right before the text content, so that the result of the `Nokogiri::HTML.parse` is closing my identfied element early. I'll attach the raw HTML, for an example page of https://2e.aonprd.com/(X(1)S(jjv5qg45qaziuq55lopb3o45))/Classes.aspx?ID=1

[html.zip](https://github.com/sparklemotion/nokogiri/files/10798002/html.zip)

**Help us reproduce what you're seeing**

```ruby
#! /usr/bin/env ruby

require 'nokogiri'

content = File.read('raw.html')
parsed_data = Nokogiri::HTML.parse(content)
body_content = parsed_data.at_css('[id="ctl00_RadDrawer1_Content_MainContent_DetailedOutput"]')
puts body_content.text # the empty string
puts parsed_data # scroll up, and see that right after `ctl00_RadDrawer1_Content_MainContent_DetailedOutput` there's loads of text, but a new, erroneous </span> has been added right before it
```

**Expected behavior**

Nokogiri shouldn't add extra closing tags

**Environment**
OSX 13.2.1
Platform: arm64-darwin
reproduced in:
- JRuby 9.3.3.0, Nokogiri 1.13.10
- MRI Ruby 2.6.9, Nokogiri 1.13.4
- MRI Ruby 2.7.7, Nokogiri 1.14.2

```
# Nokogiri (1.14.2)
    ---
    warnings: []
    nokogiri:
      version: 1.14.2
      cppflags:
      - "-I/opt/homebrew/Cellar/rbenv/1.2.0/versions/2.7.7/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.2-arm64-darwin/ext/nokogiri"
      - "-I/opt/homebrew/Cellar/rbenv/1.2.0/versions/2.7.7/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.2-arm64-darwin/ext/nokogiri/include"
      - "-I/opt/homebrew/Cellar/rbenv/1.2.0/versions/2.7.7/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.2-arm64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.7.7
      platform: arm64-darwin22
      gem_platform: arm64-darwin-22
      description: ruby 2.7.7p221 (2022-11-24 revision 168ec2b1e5) [arm64-darwin22]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      libxml2_path: "/opt/homebrew/Cellar/rbenv/1.2.0/versions/2.7.7/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.2-arm64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.10.3
      loaded: 2.10.3
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.37
      loaded: 1.1.37
    other_libraries:
      zlib: 1.2.13
      libiconv: '1.17'
      libgumbo: 1.0.0-nokogiri
```
