### ISSUE TITLE
XSLT segfault

### ISSUE THREAD

**Issue by Roguelazer** [sparklemotion/nokogiri#2800]
**Please describe the bug**

I've found a reproducible XSLT-related crash; it happens in both macOS and Linux and with both Ruby 3.1 and 3.2, but is rather much easier to trigger on macOS (not sure why). I have not been able to reproduce it with my minimal reproducer below on Ruby 2.7, but my full (much larger) application also crashes on Ruby 2.7, so I think it's broken there, too.

It can be fixed by `dup`ing the document passed to `XSLT#transform`, or by disabling garbage-collection process-wide.

**Reproduction Script**

```ruby
require "nokogiri"

INPUT = <<~EOX
  <?xml version="1.0" encoding="UTF-8"?>
  <ReturnData>
    <Keys>
      <Key>Value</Key>
      <Key>Value</Key>
    </Keys>
  </ReturnData>
EOX

STYLESHEET = <<~EOX
  <?xml version="1.0" encoding="UTF-8"?>
  <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:strip-space elements="*"/>
  </xsl:stylesheet>
EOX

def munge_xml(doc)
  new = Nokogiri::XML::Builder.new(encoding: "UTF-8") do |xml|
    xml.AppData {
      xml.Copied {}
    }
  end.doc
  copied = new.at("//Copied")
  doc.at("//ReturnData").children.each do |child|
    copied.add_child(child.dup(1, new))
  end
  new
end

def main
  30.times do
    doc = Nokogiri::XML(INPUT)
    munge_xml(doc)
    stylesheet = Nokogiri::XSLT STYLESHEET
    if ARGV[0] == "dup"
      puts stylesheet.transform(doc.dup).to_s.size
    else
      puts stylesheet.transform(doc).to_s.size
    end
  end
end

main
```

Run this as "ruby script.rb" and it should crash (most of the time; it depends on exactly what the GC feels like doing), run it as "ruby script.rb dup" and it does not crash ever.

**Backtrace**
```
/Users/james/pg/efile-viewer-2/.bundle/ruby/3.2.0/gems/nokogiri-1.14.2-arm64-darwin/lib/nokogiri/xml/node.rb:1363: [BUG] Segmentation fault at 0x0000000000000000
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin22]

-- Crash Report log information --------------------------------------------
   See Crash Report log file in one of the following locations:
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0008 p:---- s:0056 e:000055 CFUNC  :*
c:0007 p:0142 s:0051 e:000050 METHOD /Users/james/pg/efile-viewer-2/.bundle/ruby/3.2.0/gems/nokogiri-1.14.2-arm64-darwin/lib/nokogiri/xml/node.rb:1363
c:0006 p:0019 s:0039 e:000038 METHOD /Users/james/pg/efile-viewer-2/.bundle/ruby/3.2.0/gems/nokogiri-1.14.2-arm64-darwin/lib/nokogiri/html5/node.rb:37
c:0005 p:0099 s:0026 e:000025 METHOD /Users/james/pg/efile-viewer-2/.bundle/ruby/3.2.0/gems/nokogiri-1.14.2-arm64-darwin/lib/nokogiri/xml/node.rb:1295
c:0004 p:0010 s:0017 e:000016 METHOD /Users/james/pg/efile-viewer-2/.bundle/ruby/3.2.0/gems/nokogiri-1.14.2-arm64-darwin/lib/nokogiri/xml/node.rb:1191
c:0003 p:0058 s:0013 e:000011 METHOD repro.rb:40
c:0002 p:0027 s:0006 e:000005 EVAL   repro.rb:44 [FINISH]
c:0001 p:0000 s:0003 E:000210 DUMMY  [FINISH]

-- Ruby level backtrace information ----------------------------------------
repro.rb:44:in `<main>'
repro.rb:40:in `main'
/Users/james/pg/efile-viewer-2/.bundle/ruby/3.2.0/gems/nokogiri-1.14.2-arm64-darwin/lib/nokogiri/xml/node.rb:1191:in `to_s'
/Users/james/pg/efile-viewer-2/.bundle/ruby/3.2.0/gems/nokogiri-1.14.2-arm64-darwin/lib/nokogiri/xml/node.rb:1295:in `serialize'
/Users/james/pg/efile-viewer-2/.bundle/ruby/3.2.0/gems/nokogiri-1.14.2-arm64-darwin/lib/nokogiri/html5/node.rb:37:in `write_to'
/Users/james/pg/efile-viewer-2/.bundle/ruby/3.2.0/gems/nokogiri-1.14.2-arm64-darwin/lib/nokogiri/xml/node.rb:1363:in `write_to'
/Users/james/pg/efile-viewer-2/.bundle/ruby/3.2.0/gems/nokogiri-1.14.2-arm64-darwin/lib/nokogiri/xml/node.rb:1363:in `*'

-- Machine register context ------------------------------------------------
  x0: 0x0000600003fe2880  x1: 0x000000010700ccd4  x2: 0x000000016d5ddab0
  x3: 0x0000000102f0e3a8  x4: 0x0000000000000000  x5: 0x0000000000001d40
  x6: 0x00006000013e9d40  x7: 0x0000000130008150 x18: 0x0000000000000000
 x19: 0x000000013d80b000 x20: 0x0000000105c6c8d8 x21: 0x0000000000000005
 x22: 0x000000013d80b388 x23: 0x0000000105c70410 x24: 0x000000016d5ddc10
 x25: 0x000000000000001a x26: 0x0000000000000000 x27: 0x0000000000000028
 x28: 0x000000013d80b388  lr: 0x0000000102f08038  fp: 0x000000016d5ddbe0
  sp: 0x000000016d5ddbb0

-- C level backtrace information -------------------------------------------
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(rb_vm_bugreport+0x324) [0x103056d84]
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(rb_bug_for_fatal_signal) [0x102ee8514]
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(sig_do_nothing) [0x102fde430]
/usr/lib/system/libsystem_platform.dylib(_sigtramp+0x38) [0x1978442a4]
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(gc_marks_rest) [0x102f08038]
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(gc_start) [0x102f0cbd0]
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(newobj_alloc) [0x102f0793c]
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(rb_wb_protected_newobj_of) [0x102efc630]
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(str_new0) [0x102fea4b8]
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(rb_str_times) [0x102fed0a0]
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(vm_call_cfunc_with_frame) [0x10304d090]
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(vm_sendish) [0x10304ef4c]
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(vm_exec_core) [0x103036534]
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(rb_vm_exec) [0x103045710]
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(rb_ec_exec_node) [0x102eef704]
/opt/homebrew/Cellar/ruby/3.2.1/lib/libruby.3.2.dylib(ruby_run_node) [0x102eef578]
/opt/homebrew/Cellar/ruby/3.2.1/bin/ruby(main+0x68) [0x102823f34]
```

**Environment**

```
# Nokogiri (1.14.2)
    ---
    warnings: []
    nokogiri:
      version: 1.14.2
      cppflags:
      - "-I/Users/james/pg/efile-viewer-2/.bundle/ruby/3.2.0/gems/nokogiri-1.14.2-arm64-darwin/ext/nokogiri"
      - "-I/Users/james/pg/efile-viewer-2/.bundle/ruby/3.2.0/gems/nokogiri-1.14.2-arm64-darwin/ext/nokogiri/include"
      - "-I/Users/james/pg/efile-viewer-2/.bundle/ruby/3.2.0/gems/nokogiri-1.14.2-arm64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.2.1
      platform: arm64-darwin22
      gem_platform: arm64-darwin-22
      description: ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin22]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      libxml2_path: "/Users/james/pg/efile-viewer-2/.bundle/ruby/3.2.0/gems/nokogiri-1.14.2-arm64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.10.3
      loaded: 2.10.3
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.37
      loaded: 1.1.37
    other_libraries:
      zlib: 1.2.13
      libiconv: '1.17'
      libgumbo: 1.0.0-nokogiri
```
