### ISSUE TITLE
[bug] first_element_child fails with NullPointerException on JRuby

### ISSUE THREAD

**Issue by rsim** [sparklemotion/nokogiri#2802]
**Please describe the bug**

If `Nokogiri::XML::Element` does not contain child elements then `first_element_child` fails with `NullPointerException`.

**Help us reproduce what you're seeing**

In JRuby
```ruby
Nokogiri::XML("<foo>bar</foo>").first_element_child.first_element_child
```
fails with
```
Java::JavaLang::NullPointerException:
from nokogiri.XmlNode.first_element_child(XmlNode.java:733)
```

**Expected behavior**

I should return `nil` as in MRI if there are no child elements.

**Environment**

```
# Nokogiri (1.13.10)
    ---
    warnings: []
    nokogiri:
      version: 1.13.10
    ruby:
      version: 2.6.8
      platform: java
      gem_platform: universal-java-11
      description: jruby 9.3.7.0 (2.6.8) 2022-08-16 c79ef237e0 OpenJDK 64-Bit Server VM
        11.0.13+8-LTS on 11.0.13+8-LTS [arm64-darwin]
      engine: jruby
      jruby: 9.3.7.0
    other_libraries:
      xerces: Xerces-J 2.12.2
      nekohtml: NekoHTML 1.9.22.noko2
```

**Additional context**

The problem is with the implementation of the method
```java
  public IRubyObject
  first_element_child(ThreadContext context)
  {
    List<Node> elementNodes = getElements(node, true);
    if (elementNodes.size() == 0) { return context.nil; }
    return getCachedNodeOrCreate(context.runtime, elementNodes.get(0));
  }
```
as `getElements(node, true)` returns `null` if there are no child elements and then `elementNodes.size()` fails with `NullPointerException`. This line should be fixed as
```java
    if (elementNodes == null || elementNodes.size() == 0) { return context.nil; }
```

Please fix this both for Nokogiri 1.13.x and 1.14.x.
We are still using JRuby 9.3.x which is Ruby 2.6.8 compatible and therefore we cannot use the latest Nokogiri 1.14.x which requires Ruby 2.7 compatibility.
