### ISSUE TITLE
[bug] glibc doesn't seem to be needed under Alpine Linux (README.md)

### ISSUE THREAD

**Issue by x-yuri** [sparklemotion/nokogiri#2849]
**Please describe the bug**

The readme says:

> Nokogiri ships pre-compiled, "native" gems for the following platforms:
> * Linux: 
>   * x86-linux and x86_64-linux (req: glibc >= 2.17)

which sounds like `glibc` is needed in this case. From what I can see it's not.

**Help us reproduce what you're seeing**

```
$ docker run --rm -it ruby:2.7.7-alpine3.16 sh
/ # gem install nokogiri
Fetching nokogiri-1.14.2-x86_64-linux.gem
Successfully installed nokogiri-1.14.2-x86_64-linux
1 gem installed
/ # ruby -rnokogiri -e ''
```

**Expected behavior**

According to the README it should fail.

**Environment**

```
# Nokogiri (1.14.2)
    ---
    warnings: []
    nokogiri:
      version: 1.14.2
      cppflags:
      - "-I/usr/local/bundle/gems/nokogiri-1.14.2-x86_64-linux/ext/nokogiri"
      - "-I/usr/local/bundle/gems/nokogiri-1.14.2-x86_64-linux/ext/nokogiri/include"
      - "-I/usr/local/bundle/gems/nokogiri-1.14.2-x86_64-linux/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.7.7
      platform: x86_64-linux-musl
      gem_platform: x86_64-linux-musl
      description: ruby 2.7.7p221 (2022-11-24 revision 168ec2b1e5) [x86_64-linux-musl]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      libxml2_path: "/usr/local/bundle/gems/nokogiri-1.14.2-x86_64-linux/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.10.3
      loaded: 2.10.3
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.37
      loaded: 1.1.37
    other_libraries:
      zlib: 1.2.13
      libgumbo: 1.0.0-nokogiri
```

**Additional context**
