### ISSUE TITLE
Bad performance with long CSS selectors

### ISSUE THREAD

**Issue by heaven** [sparklemotion/nokogiri#2850]
The problem is with long CSS selectors on this page https://hanzoutlet.com/product/womens-oversized-knitted-long-sleeve-sweater

The selector itself is as simple as this: `div div div div div div div div` and the performance degrades exponentially with every new `div` added.

Here are a few Benchmark examples:

```
Benchmark.measure do
  @doc.css("div div div div div div").size
end

=> 3.585842   0.010797   3.596639 (  3.603034)

Benchmark.measure do
  @doc.css("div div div div div div div").size
end

=> 61.903859   0.241406  62.145265 ( 62.184888)

Benchmark.measure do
  @doc.css("div div div div div div div div").size
end

=> 771.152340   3.506642 774.658982 (774.929020)
```

Running this selector from JS takes milliseconds.

```
# Nokogiri (1.14.2)
    ---
    warnings: []
    nokogiri:
      version: 1.14.2
      cppflags:
      - "-I/Users/heaven/.rvm/gems/ruby-2.7.6@alli-ai/gems/nokogiri-1.14.2-arm64-darwin/ext/nokogiri"
      - "-I/Users/heaven/.rvm/gems/ruby-2.7.6@alli-ai/gems/nokogiri-1.14.2-arm64-darwin/ext/nokogiri/include"
      - "-I/Users/heaven/.rvm/gems/ruby-2.7.6@alli-ai/gems/nokogiri-1.14.2-arm64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 2.7.6
      platform: arm64-darwin22
      gem_platform: arm64-darwin-22
      description: ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin22]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      libxml2_path: "/Users/heaven/.rvm/gems/ruby-2.7.6@alli-ai/gems/nokogiri-1.14.2-arm64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.10.3
      loaded: 2.10.3
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.37
      loaded: 1.1.37
    other_libraries:
      zlib: 1.2.13
      libiconv: '1.17'
      libgumbo: 1.0.0-nokogiri
```
