### ISSUE TITLE
nokogiri-1.15.0-x86_64-linux requires ruby version >= 2.7, < 3.3.dev, which is incompatible with the current version, 3.3.0.preview1

### ISSUE THREAD

**Issue by rgaufman** [sparklemotion/nokogiri#2881]
Please allow installation with Ruby 3.3.0-preview1 :)

As a temporary workaround, I ran this:

```
bundle config set deployment 'false'
```

**Comment by flavorjones** [comment]
I appreciate your enthusiasm! You can install Nokogiri with the preview version of Ruby by choosing the "ruby" platform gem.

We have no plans to ship precompiled support for preview releases of Ruby.

**Comment by adfoster-r7** [comment]
Just if it helps any future travellers; I worked around this locally and on CI with the `BUNDLE_FORCE_RUBY_PLATFORM=true` environment variable

Example:

```yaml
# ...
      - name: Setup Ruby
        env:
          BUNDLE_WITHOUT: "coverage development pcap"
          BUNDLE_FORCE_RUBY_PLATFORM: "true"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${{ matrix.ruby }}'
          bundler-cache: true
# ...
```

It forces compilation of all of the Gems; From the docs:

> ### FORCE_RUBY_PLATFORM
> ...
> This can be handy (assuming the pure ruby variant works fine) when:
> ...
> * The platform specific variant does not yet support a newer ruby
>
> Source:
>https://github.com/rubygems/rubygems/blob/eb91e868b22bc5c05c14d273af2de7b299bba42f/bundler/lib/bundler/man/gemfile.5.ronn?plain=1#L235-L247
