### ISSUE TITLE
[bug] `Nokogiri::XML::Reader.from_io.each` misidentifies character encoding?

### ISSUE THREAD

**Issue by koshigoe** [sparklemotion/nokogiri#2882]
**Please describe the bug**

`Nokogiri::XML::Reader.from_io.each` cause exception `Nokogiri::XML::SyntaxError` when XML node contain long non-ascii characters.
The XML node contain only valid UTF-8 characters, but cause error `FATAL: Input is not proper UTF-8, indicate encoding !`.

**Help us reproduce what you're seeing**

```ruby
require 'nokogiri'
require 'stringio'

NON_ASCII = "\u{3042}"
XML_TEMPLATE =<<~XML
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <a>%<content>s</a>
</root>
XML

[325, 326].each do |length|
  io = StringIO.new(format(XML_TEMPLATE, content: NON_ASCII * length))
  Nokogiri::XML::Reader.from_io(io).tap { |x| pp x  }.each { }
  puts "OK: #{length}"
rescue => e
  puts "NG: #{length} (#{e.inspect})"
end

__END__

ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [arm64-darwin22]

### nokogiri 1.14.4

OK: 325
OK: 326

### nokogiri 1.15.0

OK: 325
NG: 326 (#<Nokogiri::XML::SyntaxError: 3:332: FATAL: Input is not proper UTF-8, indicate encoding !>)
```

**Expected behavior**

Do not raise error.

**Environment**

```
# Nokogiri (1.15.0)
    ---
    warnings: []
    nokogiri:
      version: 1.15.0
      cppflags:
      - "-I/Users/koshigoe/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/nokogiri-1.15.0-arm64-darwin/ext/nokogiri"
      - "-I/Users/koshigoe/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/nokogiri-1.15.0-arm64-darwin/ext/nokogiri/include"
      - "-I/Users/koshigoe/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/nokogiri-1.15.0-arm64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.1.4
      platform: arm64-darwin22
      gem_platform: arm64-darwin-22
      description: ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [arm64-darwin22]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-update-config.guess-and-config.sub-for-libxml2.patch
      - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch
      libxml2_path: "/Users/koshigoe/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/nokogiri-1.15.0-arm64-darwin/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.11.3
      loaded: 2.11.3
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-config.guess-and-config.sub-for-libxslt.patch
      datetime_enabled: true
      compiled: 1.1.38
      loaded: 1.1.38
    other_libraries:
      zlib: 1.2.13
      libiconv: '1.17'
      libgumbo: 1.0.0-nokogiri
```

**Additional context**

```
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [arm64-darwin22]
```
