### ISSUE TITLE
[help] '&amp;' is converted to '&', how to disable the conversion?

### ISSUE THREAD

**Issue by maksonlee** [sparklemotion/nokogiri#2959]
**What problem are you trying to solve?**
```
content = '<Failure message="org.junit.ComparisonFailure: expected:&amp;lt;TRANSIT_[TASK_CLOSE]&amp;gt; but was:&amp;lt;TRANSIT_[ACTIVITY_OPEN]&amp;gt;&#13;" />'
xml_doc  = Nokogiri::XML(content)
puts xml_doc.root['message'].inspect
```
```'&amp;'``` is converted to '&' automatically, how to disable it?
```
"org.junit.ComparisonFailure: expected:&lt;TRANSIT_[TASK_CLOSE]&gt; but was:&lt;TRANSIT_[ACTIVITY_OPEN]&gt;\r"
```

**Environment**

```
# Nokogiri (1.15.4)
    ---
    warnings: []
    nokogiri:
      version: 1.15.4
      cppflags:
      - "-I/home/administrator/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.4-x86_64-linux/ext/nokogiri"
      - "-I/home/administrator/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.4-x86_64-linux/ext/nokogiri/include"
      - "-I/home/administrator/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.4-x86_64-linux/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.2.2
      platform: x86_64-linux
      gem_platform: x86_64-linux
      description: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-update-config.guess-and-config.sub-for-libxml2.patch
      - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch
      libxml2_path: "/home/administrator/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/nokogiri-1.15.4-x86_64-linux/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.11.5
      loaded: 2.11.5
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-config.guess-and-config.sub-for-libxslt.patch
      datetime_enabled: true
      compiled: 1.1.38
      loaded: 1.1.38
    other_libraries:
      zlib: 1.2.13
      libgumbo: 1.0.0-nokogiri
```
