### ISSUE TITLE
[bug] Difference between 1.14 and 1.15 related to UTF-8 - ASCII conversion

### ISSUE THREAD

**Issue by tagliala** [sparklemotion/nokogiri#2965]
**Please describe the bug**

Hello, and apologies if this a duplicate of an existing issue. This may be related to #918.

When updating the gems in a test suite of a third-party library premailer/premailer#430, I've noticed some breaking tests related to encoding.

This has been bisected to 0c05c1f and it is a consequence of the update of libxml2 from 2.10 to 2.11

There is a difference in the output when running

```rb
::Nokogiri::HTML('<p>é</p>', nil, 'ASCII-8BIT').at("body").inner_html
```

Outputs:

```
"<p>&eacute;</p>" # v 1.14 
"<p>&Atilde;&copy;</p>" # v 1.15 
```

**Help us reproduce what you're seeing**

```ruby
#! /usr/bin/env ruby
# frozen_string_literal: true

require 'nokogiri'
require 'minitest/autorun'

class Test < Minitest::Spec
  describe 'Node#css' do
    it 'should output &acute; html entity' do
      html = '<p>é</p>'

      doc = ::Nokogiri::HTML(html, nil, 'ASCII-8BIT')

      assert_equal '<p>&eacute;</p>', doc.at('body').inner_html
    end
  end
end
```

**Expected behavior**

I do not know what is the correct behavior.

It looks like the output from 1.15 (libxml2 v2.11) is correct, because the input string contains a unicode char, but I would like to have a confirmation

**Environment**

```
# Nokogiri (1.14.5)
    ---
    warnings: []
    nokogiri:
      version: 1.14.5
      cppflags:
      - "-I~/.rvm/gems/ruby-3.2.2/gems/nokogiri-1.14.5/ext/nokogiri"
      - "-I~/.rvm/gems/ruby-3.2.2/gems/nokogiri-1.14.5/ext/nokogiri/include"
      - "-I~/.rvm/gems/ruby-3.2.2/gems/nokogiri-1.14.5/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.2.2
      platform: x86_64-darwin22
      gem_platform: x86_64-darwin-22
      description: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]
      engine: ruby
    libxml:
      source: packaged
      precompiled: false
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      libxml2_path: "~/.rvm/gems/ruby-3.2.2/gems/nokogiri-1.14.5/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.10.4
      loaded: 2.10.4
    libxslt:
      source: packaged
      precompiled: false
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.37
      loaded: 1.1.37
    other_libraries:
      libgumbo: 1.0.0-nokogiri

---

# Nokogiri (1.15.4)
    ---
    warnings: []
    nokogiri:
      version: 1.15.4
      cppflags:
      - "-I~/.rvm/gems/ruby-3.2.2/gems/nokogiri-1.15.4/ext/nokogiri"
      - "-I~/.rvm/gems/ruby-3.2.2/gems/nokogiri-1.15.4/ext/nokogiri/include"
      - "-I~/.rvm/gems/ruby-3.2.2/gems/nokogiri-1.15.4/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.2.2
      platform: x86_64-darwin22
      gem_platform: x86_64-darwin-22
      description: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]
      engine: ruby
    libxml:
      source: packaged
      precompiled: false
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-update-config.guess-and-config.sub-for-libxml2.patch
      - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch
      libxml2_path: "~/.rvm/gems/ruby-3.2.2/gems/nokogiri-1.15.4/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.11.5
      loaded: 2.11.5
    libxslt:
      source: packaged
      precompiled: false
      patches:
      - 0001-update-config.guess-and-config.sub-for-libxslt.patch
      datetime_enabled: true
      compiled: 1.1.38
      loaded: 1.1.38
    other_libraries:
      libgumbo: 1.0.0-nokogiri
```

**Additional context**

When omitting `'ASCII-8BIT'` parameter the behavior is the same with both versions, but the output will miss html entities.

In the attempt of getting entities, in the output `©` is rendered as `&#169;`, and this behavior is the same between 1.14 and 1.15

```
::Nokogiri::HTML('<p>é ©</p>', nil).at("body").inner_html
"<p>é ©</p>"

::Nokogiri::HTML('<p>é ©</p>', nil).at("body").inner_html(encoding: 'US-ASCII')
"<p>&#233; &#169;</p>"
```
