### ISSUE TITLE
[bug] Attribute contents HTML-encoded after serialization

### ISSUE THREAD

**Issue by mamhoff** [sparklemotion/nokogiri#3104]
**Please describe the bug**

Given an HTML document with a space in the `href` portion of the `a` element, `document.to_html` will incorrectly encode that space. This is only the case with the HTML4 parser.

**Help us reproduce what you're seeing**

```rb
#! /usr/bin/env ruby

require 'nokogiri'
require 'minitest/autorun'

class Test < Minitest::Spec
  describe "Node#css" do
    it "should find a div using chained classes" do
      html = '<a href="/hello/ "> Hello </a>'
      
      doc = Nokogiri::HTML::Document.parse(html)
      serialized_doc = doc.to_html
      assert_false serialized_doc.match(/%20/)
    end
  end
end
```

**Expected behavior**

I would expect the href attribute value not to be HTML-encoded.

**Environment**

```
# Nokogiri (1.16.0)
    ---
    warnings: []
    nokogiri:
      version: 1.16.0
      cppflags:
      - "-I/home/anselm/.gem/ruby/3.2.2/gems/nokogiri-1.16.0-x86_64-linux/ext/nokogiri"
      - "-I/home/anselm/.gem/ruby/3.2.2/gems/nokogiri-1.16.0-x86_64-linux/ext/nokogiri/include"
      - "-I/home/anselm/.gem/ruby/3.2.2/gems/nokogiri-1.16.0-x86_64-linux/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.2.2
      platform: x86_64-linux
      gem_platform: x86_64-linux
      description: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-update-config.guess-and-config.sub-for-libxml2.patch
      - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.12.3
      loaded: 2.12.3
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-config.guess-and-config.sub-for-libxslt.patch
      datetime_enabled: true
      compiled: 1.1.39
      loaded: 1.1.39
    other_libraries:
      zlib: '1.3'
      libgumbo: 1.0.0-nokogiri

```

**Additional context**

We ran into this because we use Nokogiri to sanitize HTML snippets (the idea is to filter out some elements), and got reports from our users that some links don't work. They had mistakenly added a space to the end of the URL, which Nokogiri then encoded as `%20`, leading to broken links.
