### ISSUE TITLE
[help] How to search VML tags using search method

### ISSUE THREAD

**Issue by vishal-bacancy** [sparklemotion/nokogiri#3126]
I want to get elements by the tag name, but the issue is tag names are written in VML like below:

![image](https://github.com/sparklemotion/nokogiri/assets/34997369/3b7b2ee0-e93a-4c0e-93cf-e25702864124) 

ref: https://www.w3.org/TR/NOTE-VML

I want to use `search` method for that as it is more generic.

The below code was working in nokogiri 1.14.5

```

%w[
        shapetype
        shape
        group
        background
        path
        fill
        shadow
        textbox
        textpath
        imagedata
        line
        polyline
        curve
        rect
        oval
        arc
        image
        stroke
      ].each do |key|
        doc.search("[name()='v:#{key}']").each do |node|
          node.replace(node.children)
        end
      end

```

But after updating the nokogiri to 1.16.2, it started giving the below error

`Nokogiri::XML::XPath::SyntaxError: xmlXPathCompOpEval: function name not found`

**Environment**
Development

Nokogiri version info:
```
# Nokogiri (1.16.2)
    ---
    warnings: []
    nokogiri:
      version: 1.16.2
      cppflags:
      - "-I/home/vishal-bac/.rvm/gems/ruby-3.2.2/gems/nokogiri-1.16.2-x86_64-linux/ext/nokogiri"
      - "-I/home/vishal-bac/.rvm/gems/ruby-3.2.2/gems/nokogiri-1.16.2-x86_64-linux/ext/nokogiri/include"
      - "-I/home/vishal-bac/.rvm/gems/ruby-3.2.2/gems/nokogiri-1.16.2-x86_64-linux/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.2.2
      platform: x86_64-linux
      gem_platform: x86_64-linux
      description: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-update-config.guess-and-config.sub-for-libxml2.patch
      - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.12.5
      loaded: 2.12.5
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-config.guess-and-config.sub-for-libxslt.patch
      datetime_enabled: true
      compiled: 1.1.39
      loaded: 1.1.39
    other_libraries:
      zlib: '1.3'
      libgumbo: 1.0.0-nokogiri

```
