### ISSUE TITLE
Fragment with unclosed script element has "</body></html>" appended as CDATA

### ISSUE THREAD

**Issue by rgrove** [sparklemotion/nokogiri#315]
In Nokogiri 1.4.2, creating a document fragment from a string with an unclosed `<script>` element results in the script element being closed, but `</body></html>` is also appended to the CDATA inside the script element.

Here's a simple repro case in IRB:

```
>> Nokogiri::HTML.fragment("foo <script>bar")
=> #<Nokogiri::HTML::DocumentFragment:0x809e9ab4 name="#document-fragment" children=[#<Nokogiri::XML::Text:0x809e9780 "foo ">, #<Nokogiri::XML::Element:0x809e9730 name="script" children=[#<Nokogiri::XML::CDATA:0x809e9140 "bar</body></html>">]>]>
```

Nokogiri 1.4.1 did not do this.

Here's the output of `nokogiri -v` on my machine, in case it's relevant:

```
--- 
warnings: []

nokogiri: 1.4.2
ruby: 
  version: 1.9.1
  platform: i386-darwin10
libxml: 
  binding: extension
  compiled: 2.7.6
  loaded: 2.7.6
```
