### ISSUE TITLE
[help] Nokogiri href escaping change between 1.13 and 1.14

### ISSUE THREAD

**Issue by rahim** [sparklemotion/nokogiri#3202]
I'm trying to understand a change in behaviour I've tracked down to Nokogiri updates that arrived in version 1.14.0, specifically the automatic URL encoding of some characters contained within hrefs which was occurring previously but then stopped at this version.

With 1.13.8 (but I believe any version prior to 1.14.0):

```
irb(main):002:0> Nokogiri::HTML::DocumentFragment.parse('<p>\\</p><a href="\foo}"/>').to_html
=> "<p>\\</p><a href=\"%5Cfoo%7D\"></a>"
                       ^^^   ^^^
```

With 1.15.4 (but I believe any version from 1.14.0 onwards):

```
irb(main):003:0> Nokogiri::HTML::DocumentFragment.parse('<p>\\</p><a href="\foo}"/>').to_html
=> "<p>\\</p><a href=\"\\foo}\"></a>"
                       ^^   ^
```

I'm struggling to find anything in the changelog in relation to this. I'm wondering whether I'm missing something or whether this is unintended?

**Environment**

```
# Nokogiri (1.13.8)
    ---
    warnings: []
    nokogiri:
      version: 1.13.8
      cppflags:
      - "-I/usr/local/bundle/gems/nokogiri-1.13.8-aarch64-linux/ext/nokogiri"
      - "-I/usr/local/bundle/gems/nokogiri-1.13.8-aarch64-linux/ext/nokogiri/include"
      - "-I/usr/local/bundle/gems/nokogiri-1.13.8-aarch64-linux/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.1.2
      platform: aarch64-linux
      gem_platform: aarch64-linux
      description: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [aarch64-linux]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - 0004-use-glibc-strlen.patch
      - 0005-avoid-isnan-isinf.patch
      - 0006-update-automake-files-for-arm64.patch
      - '0008-htmlParseComment-handle-abruptly-closed-comments.patch'
      - '0009-allow-wildcard-namespaces.patch'
      libxml2_path: "/usr/local/bundle/gems/nokogiri-1.13.8-aarch64-linux/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.9.14
      loaded: 2.9.14
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-automake-files-for-arm64.patch
      datetime_enabled: true
      compiled: 1.1.35
      loaded: 1.1.35
    other_libraries:
      zlib: 1.2.12
      libgumbo: 1.0.0-nokogiri
```

```
# Nokogiri (1.15.4)
    ---
    warnings: []
    nokogiri:
      version: 1.15.4
      cppflags:
      - "-I/usr/local/bundle/gems/nokogiri-1.15.4-aarch64-linux/ext/nokogiri"
      - "-I/usr/local/bundle/gems/nokogiri-1.15.4-aarch64-linux/ext/nokogiri/include"
      - "-I/usr/local/bundle/gems/nokogiri-1.15.4-aarch64-linux/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.1.2
      platform: aarch64-linux
      gem_platform: aarch64-linux
      description: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [aarch64-linux]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-update-config.guess-and-config.sub-for-libxml2.patch
      - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch
      libxml2_path: "/usr/local/bundle/gems/nokogiri-1.15.4-aarch64-linux/ext/nokogiri"
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.11.5
      loaded: 2.11.5
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-config.guess-and-config.sub-for-libxslt.patch
      datetime_enabled: true
      compiled: 1.1.38
      loaded: 1.1.38
    other_libraries:
      zlib: 1.2.13
      libgumbo: 1.0.0-nokogiri
```
