### ISSUE TITLE
[bug] Cannot parse schema with redefine of https source with nononet enabled

### ISSUE THREAD

**Issue by ryanong** [sparklemotion/nokogiri#3236]
**Please describe the bug**

When trying to parse an XML schema with a redefine that is remote and nononet config flag, it raises with the error
```
Nokogiri::XML::SyntaxError:
       6:0: ERROR: Element '{http://www.w3.org/2001/XMLSchema}redefine': Failed to load the document 'https://www.fincen.gov/sites/default/files/schema/base/BSA_XML_2.0.xsd' for redefinition.
```

**Help us reproduce what you're seeing**

```ruby
#! /usr/bin/env ruby

require 'nokogiri'
require 'minitest/autorun'
require 'net/http'

class Test < Minitest::Spec
  describe "Nokogiri::XML::Schema.new" do
    it "should be able to load an xml with a https redefine and nononet config flag without crashing" do
      xsd = Net::HTTP.get(URI("https://www.fincen.gov/sites/default/files/schema/base/BOIRSchema.xsd"))
      schema = Nokogiri::XML::Schema.new(xsd, Nokogiri::XML::ParseOptions.new.nononet)
    end
  end
end
```

**Expected behavior**

No error

**Environment**
```
# Nokogiri (1.16.6)
    ---
    warnings: []
    nokogiri:
      version: 1.16.6
      cppflags:
      - "-I/Users/ryan.ong/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.6-arm64-darwin/ext/nokogiri"
      - "-I/Users/ryan.ong/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.6-arm64-darwin/ext/nokogiri/include"
      - "-I/Users/ryan.ong/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.6-arm64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.3.2
      platform: arm64-darwin23
      gem_platform: arm64-darwin-23
      description: ruby 3.3.2 (2024-05-30 revision e5a195edf6) [arm64-darwin23]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - 0003-libxml2.la-is-in-top_builddir.patch
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-update-config.guess-and-config.sub-for-libxml2.patch
      - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.12.8
      loaded: 2.12.8
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-config.guess-and-config.sub-for-libxslt.patch
      datetime_enabled: true
      compiled: 1.1.39
      loaded: 1.1.39
    other_libraries:
      zlib: 1.3.1
      libiconv: '1.17'
      libgumbo: 1.0.0-nokogiri
```

**Additional context**
