### ISSUE TITLE
[bug] XML entity codes are printed along with expansion in to_s on JRuby

### ISSUE THREAD

**Issue by i-h8-github** [sparklemotion/nokogiri#3270]
**Please describe the bug**

On JRuby, calling `to_s` on an element with an entity reference will print the code and its expansion, as opposed to just the XML contents of the element verbatim as in MRI.

**Help us reproduce what you're seeing**

`tst.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Test [
<!ENTITY t "Test">
]>
<pos>&t;</pos>
```

`tst.rb:`
```ruby
require 'nokogiri'
doc = Nokogiri::XML(File.open('tst.xml'))
doc.xpath("//pos").each do |p| puts p end
```
`output:`
```
$ jruby tst.rb
<pos>&t;Test</pos>
```
**Expected behavior**

```
$ ruby tst.rb
<pos>&t;</pos>
```

**Environment**

```
# Nokogiri (1.13.10)
    ---
    warnings: []
    nokogiri:
      version: 1.13.10
    ruby:
      version: 2.6.8
      platform: java
      gem_platform: universal-java-11
      description: jruby 9.3.9.0 (2.6.8) 2022-10-24 537cd1f8bc OpenJDK 64-Bit Server VM
        11.0.23+9-post-Ubuntu-1ubuntu122.04.1 on 11.0.23+9-post-Ubuntu-1ubuntu122.04.1
        +jit [x86_64-linux]
      engine: jruby
      jruby: 9.3.9.0
    other_libraries:
      xerces: Xerces-J 2.12.2
      nekohtml: NekoHTML 1.9.22.noko2
```

**Additional context**

None.
