### ISSUE TITLE
[bug] v1.18.x requiring glibc 2.29 (Rocky 8.10 ships with 2.28)

### ISSUE THREAD

**Issue by tejclark** [sparklemotion/nokogiri#3399]
Upgrading to 1.18.1 caused our application to be unable to start due to glibc 2.29 requirement. Rocky (and I presume Alma) 8.10 unfortunately ship with glibc 2.28. We had to add `force_ruby_platform` to get the application to start.

**Help us reproduce what you're seeing**

```
/lib64/libm.so.6: version `GLIBC_2.29' not found (required by /var/www/app/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.1-x86_64-linux-gnu/lib/nokogiri/3.3/nokogiri.so) - /var/www/app vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.1-x86_64-linux-gnu/lib/nokogiri/3.3/nokogiri.so (LoadError)
  /var/www/app/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.1-x86_64-linux-gnu/lib/nokogiri/extension.rb:7:in `require_relative'
  /var/www/app/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.1-x86_64-linux-gnu/lib/nokogiri/extension.rb:7:in `<main>'
  /var/www/app/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.1-x86_64-linux-gnu/lib/nokogiri.rb:8:in `require_relative'
  /var/www/app/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.1-x86_64-linux-gnu/lib/nokogiri.rb:8:in `<main>'
```

**Expected behavior**

To work with `glibc >= 2.17` as stated in the documentation.

**Environment**

(Had to add `gem "nokogiri", force_ruby_platform: true` to our Gemfile before we were able to run `nokogiri -v`)

```
# Nokogiri (1.18.1)
    ---
    warnings: []
    nokogiri:
      version: 1.18.1
      cppflags:
      - "-I/var/www/app/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.1/ext/nokogiri"
      - "-I/var/www/app/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.1/ext/nokogiri/include"
      - "-I/var/www/app/vendor/bundle/ruby/3.3.0/gems/nokogiri-1.18.1/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.3.6
      platform: x86_64-linux
      gem_platform: x86_64-linux
      description: ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [x86_64-linux]
      engine: ruby
    libxml:
      source: packaged
      precompiled: false
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-update-config.guess-and-config.sub-for-libxml2.patch
      - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch
      - '0019-xpath-Use-separate-static-hash-table-for-standard-fu.patch'
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.13.5
      loaded: 2.13.5
    libxslt:
      source: packaged
      precompiled: false
      patches:
      - 0001-update-config.guess-and-config.sub-for-libxslt.patch
      datetime_enabled: true
      compiled: 1.1.42
      loaded: 1.1.42
    other_libraries:
      libgumbo: 1.0.0-nokogiri
```
