### ISSUE TITLE
Partial script tag not being sanitized

### ISSUE THREAD

**Issue by shashankmehra** [sparklemotion/nokogiri#3444]
With Rails 7.1 the HTML5 sanitizer has become the default sanitizer vendor. A test in my project started to fail which was checking that strings like `<script>alert(1)</script` are being sanitized correctly.

The failure was due to Nokogiri parser giving different outputs for HTML5 and HTML4:

```
pry(main)> Nokogiri::HTML5::Document.parse('<script>test</script')
=> #(Document:0x1ba30 {
  name = "document",
  children = [
    #(Element:0x1ba44 {
      name = "html",
      children = [ #(Element:0x1ba58 { name = "head", children = [ #(Element:0x1ba6c { name = "script", children = [ #(Text "test</script")] })] }), #(Element:0x1ba80 { name = "body" })]
      })]
  })
```

The HTML5 parser is leaving `</script` unparsed. However HTML4 doesn't do that:

```
pry(main)> Nokogiri::HTML4::Document.parse('<script>test</script')
=> #(Document:0x1b9cc {
  name = "document",
  children = [
    #(DTD:0x1b9e0 { name = "html" }),
    #(Element:0x1b9f4 { name = "html", children = [ #(Element:0x1ba08 { name = "head", children = [ #(Element:0x1ba1c { name = "script", children = [ #(CDATA "test")] })] })] })]
  })
```

Strangely partial video tag seems to be working fine for HTML4 and HTML5:
```
pry(main)> Nokogiri::HTML5::Document.parse('<video>test</video')
=> #(Document:0x1ba94 {
  name = "document",
  children = [
    #(Element:0x1baa8 {
      name = "html",
      children = [ #(Element:0x1babc { name = "head" }), #(Element:0x1bad0 { name = "body", children = [ #(Element:0x1bae4 { name = "video", children = [ #(Text "test")] })] })]
      })]
  })
```

**Expected behavior**

Partial script tag should be sanitized the same way video tag is being sanitized (or how HTML4 sanitizer sanitizes script tag).

**Environment**

```
# Nokogiri (1.18.3)
    ---
    warnings: []
    nokogiri:
      version: 1.18.3
      cppflags:
      - "-I/Users/shashank/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/nokogiri-1.18.3-arm64-darwin/ext/nokogiri"
      - "-I/Users/shashank/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/nokogiri-1.18.3-arm64-darwin/ext/nokogiri/include"
      - "-I/Users/shashank/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/nokogiri-1.18.3-arm64-darwin/ext/nokogiri/include/libxml2"
      ldflags: []
    ruby:
      version: 3.2.2
      platform: arm64-darwin21
      gem_platform: arm64-darwin-21
      description: ruby 3.2.2 (2023-03-30 revision e51014f9c0) +YJIT [arm64-darwin21]
      engine: ruby
    libxml:
      source: packaged
      precompiled: true
      patches:
      - 0001-Remove-script-macro-support.patch
      - 0002-Update-entities-to-remove-handling-of-ssi.patch
      - '0009-allow-wildcard-namespaces.patch'
      - 0010-update-config.guess-and-config.sub-for-libxml2.patch
      - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch
      - '0019-xpath-Use-separate-static-hash-table-for-standard-fu.patch'
      memory_management: ruby
      iconv_enabled: true
      compiled: 2.13.6
      loaded: 2.13.6
    libxslt:
      source: packaged
      precompiled: true
      patches:
      - 0001-update-config.guess-and-config.sub-for-libxslt.patch
      datetime_enabled: true
      compiled: 1.1.42
      loaded: 1.1.42
    other_libraries:
      zlib: 1.3.1
      libiconv: '1.17'
      libgumbo: 1.0.0-nokogiri
```
