### ISSUE TITLE
Issues with nokogiri on Leopard with Homebrew.

### ISSUE THREAD

**Issue by joearasin** [sparklemotion/nokogiri#349]
Running nokogiri -v outputs:
    nokogiri -v
    --- 
    nokogiri: 1.4.3.1
    warnings: []

```
libxml: 
  compiled: 2.7.7
  loaded: 2.7.7
  binding: extension
ruby: 
  platform: i686-darwin9.8.0
  engine: mri
  version: 1.8.6
```

But I am still getting the 

```
WARNING: Nokogiri was built against LibXML version 2.7.7, but has dynamically loaded 2.6.16
```

And bugs ensue. Any reason for this?
