### ISSUE TITLE
Node#swap crashing bug

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#362]
From the mailing list:

```
f = Nokogiri::XML.fragment( "<div class='section'><span class='greeting'></span></div>" )
f.css( 'div' ).each do | node |
  node.swap( '<h1>hi</h1>' )
end
```

reproduced with 

```
ruby: 
  engine: mri
  version: 1.8.7
  platform: x86_64-linux
libxml: 
  loaded: 2.7.6
  binding: extension
  compiled: 2.7.6
nokogiri: 1.4.3.1
```
