### ISSUE TITLE
segfault in recursive parsing (1.4.4) in ruby 1.9.2

### ISSUE THREAD

**Issue by lls** [sparklemotion/nokogiri#382]
The below code breaks ruby 1.9.2 but works in 1.8.7. It also works without the thread so I'm not sure if it is a nokogiri issue or a ruby one.

```
require 'nokogiri'


def content(node)
    if node.class==Nokogiri::XML::Text then element_text(node)
    else node_content(node, "")
    end
  end

  def node_content(node, ini_text)
    node.children.inject(ini_text) do |text, node|
      text + (content(node))
    end
  end

  def element_text(node)
    node_content(node, node.content)
  end


fonts = (1..200).to_a.map{|i| ["<FONT>","</FONT>"]}.flatten.sort.reverse.join("")
document = Nokogiri::HTML.parse("<HTML><BODY>#{fonts}</BODY></HTML>", nil, "UTF8")


th=Thread.new{content(document)}
th.join
```

system:
    nokogiri -v
    --- 
    warnings: []

```
nokogiri: 1.4.4
ruby: 
  version: 1.9.2
  platform: x86_64-linux
  engine: ruby
libxml: 
  binding: extension
  compiled: 2.7.7
  loaded: 2.7.7
```
