### ISSUE TITLE
error parsing fragment (1) for a long wysiwig editor input

### ISSUE THREAD

**Issue by markiz** [sparklemotion/nokogiri#468]
Okay, here is a situation: I've got a WYSIWIG editor (CKEditor to be precise) which accepts some data on input. People use MS Word for formatting and copy-paste it into wysiwig. Output is html or xml-like formatted document which I later scrub with loofah which uses nokogiri underneath. This brings us to an error

```
RuntimeError: error parsing fragment (1)
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/nokogiri-1.4.4/lib/nokogiri/xml/node.rb:509:in `in_context'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/nokogiri-1.4.4/lib/nokogiri/xml/node.rb:509:in `parse'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/nokogiri-1.4.4/lib/nokogiri/html/document_fragment.rb:22:in `initialize'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/nokogiri-1.4.4/lib/nokogiri/xml/node.rb:485:in `new'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/nokogiri-1.4.4/lib/nokogiri/xml/node.rb:485:in `fragment'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/nokogiri-1.4.4/lib/nokogiri/xml/node.rb:885:in `coerce'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/nokogiri-1.4.4/lib/nokogiri/xml/node.rb:280:in `add_previous_sibling'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/nokogiri-1.4.4/lib/nokogiri/xml/node.rb:328:in `before'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/loofah-1.0.0/lib/loofah/scrubbers.rb:78:in `scrub'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/loofah-1.0.0/lib/loofah/scrubber.rb:118:in `traverse_conditionally_bottom_up'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/loofah-1.0.0/lib/loofah/scrubber.rb:78:in `traverse'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/loofah-1.0.0/lib/loofah/instance_methods.rb:46:in `scrub!'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/loofah-1.0.0/lib/loofah/instance_methods.rb:44:in `scrub!'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/nokogiri-1.4.4/lib/nokogiri/xml/node_set.rb:239:in `each'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/nokogiri-1.4.4/lib/nokogiri/xml/node_set.rb:238:in `upto'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/nokogiri-1.4.4/lib/nokogiri/xml/node_set.rb:238:in `each'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/loofah-1.0.0/lib/loofah/instance_methods.rb:44:in `scrub!'
```

I used loofah 1.0.0 and nokogiri 1.4.4, and here's a testcase (warning: lots of cyrillic symbols): https://gist.github.com/1d62699155ff0f398c8f

Checked it on my OS X:

```
--- 
warnings: []

nokogiri: 1.4.4
ruby: 
  version: 1.9.2
  platform: x86_64-darwin10.6.0
  engine: ruby
libxml: 
  binding: extension
  compiled: 2.7.3
  loaded: 2.7.3
```

and on CentOS:

```
--- 
warnings: []

ruby: 
  engine: ruby
  version: 1.8.7
  platform: x86_64-linux
libxml: 
  loaded: 2.7.6
  binding: extension
  compiled: 2.7.6
nokogiri: 1.4.4
```
