### ISSUE TITLE
Segmentation fault nokogiri/xml/node.rb:809

### ISSUE THREAD

**Issue by sorens** [sparklemotion/nokogiri#469]
# summary

I am hitting a segmentation fault @ `nokogiri/xml/node_set.rb:237` but in my attempts to reproduce it, i keep hitting a segmentation fault @ `nokogiri/xml/node.rb:809`. I am not sure if they are related or not, but for the time being this bug report is only about `node.rb:809` since the instructions below can only reproduce that issue.
# setup info

> nokogiri -v

```
--- 
warnings: []

ruby: 
  engine: mri
  version: 1.8.7
  platform: i686-darwin10.4.0
libxml: 
  loaded: 2.7.3
  binding: extension
  compiled: 2.7.3
nokogiri: 1.4.4
```

> rest client info

```
rest-client (1.6.1)
      mime-types (>= 1.16)
```
# steps to reproduce

create a new rails project

```
rails create nokobug1
```

modify the gemfile to include

```
gem 'rest-client'
gem 'nokogiri'
```

run `bundle install`

run `rails c`

in the rails console:

```
url = "http://feeds.nytimes.com/click.phdo?i=918cfd8171427ec0733d6707cce739a8"
raw_data = RestClient.get( url )
parsed = Nokogiri::HTML( raw_data )
r = parsed.xpath( '//*[contains(@class, "entry-content")]' )
r.to_html.class
r.to_html.class
r.to_html.class
r.to_html.class
```

note: you may have to repeat the last command a few times. I have not been able to narrow it down to a precise number. It just seems if you try to access r.to_html multiple times, you get the segmentation fault.
