### ISSUE TITLE
SEGV when adding/modifying attribute

### ISSUE THREAD

**Issue by jslabovitz** [sparklemotion/nokogiri#513]
I've run into a problem when adding attributes to certain nodes in an XML document. It seems to be either a memory corruption issue, or Nokogiri trying to mark a nil object for garbage collection. The result is a SEGV in what I think is the garbage collection phase.

I stripped down a much longer bunch of code to find the minimum needed to trigger the problem.  Basically, the SEGV happens when a specific attribute of a given node is set _twice._ Note that this is probably more complicated than typical Nokogiri usage, as we're using XML entity references and creating corresponding DTD with those entities.

The problem occurs under both 1.8.7 (on Mac OS X, CentOS, and Linux) and 1.9.2 (on Mac OS X at least), but appears most often under 1.9.2.  We saw this with Nokogiri 1.4.7, 1.5.0, and the edge as installed from Github.  Here is the 'nokogiri -v' output:

```
# Nokogiri (1.5.0)
    ---
    warnings: []
    nokogiri: 1.5.0
    ruby:
      version: 1.9.2
      platform: x86_64-darwin11.0.0
      description: ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin11.0.0]
      engine: ruby
    libxml:
      binding: extension
      compiled: 2.7.7
      loaded: 2.7.7
```

A test script is at https://gist.github.com/1134865.  The XML file is at http://www.sendspace.com/file/gqy4wp.  The SEGV dump is at https://gist.github.com/1134879.

Let me know if there's any other info I can provide.
