### ISSUE TITLE
Segfault: Nokogiri 1.5.0, ruby 1.9.2p290, libxml2.7.8

### ISSUE THREAD

**Issue by benmiles** [sparklemotion/nokogiri#600]
I am getting intermittent segfaults when running this code (segfaults about 50% of the time)

```
require 'nokogiri'
require 'CGI'

html = %Q{<sec>Foo &amp; bar</sec>}

node = Nokogiri::XML::DocumentFragment.parse(html).at('.//sec')
s = node.inner_text

node.swap %(<b>#{s}</b>)                    # segfault
# node.swap %(<b>#{CGI::escapeHTML s}</b>)  # no segfault
```

output of nokogiri -v

```
# Nokogiri (1.5.0)
    ---
    warnings: []
    nokogiri: 1.5.0
    ruby:
      version: 1.9.2
      platform: x86_64-darwin10.8.0
      description: ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin10.8.0]
      engine: ruby
    libxml:
      binding: extension
      compiled: 2.7.8
      loaded: 2.7.8
```
