### ISSUE TITLE
Segmentation Fault on require

### ISSUE THREAD

**Issue by hhaamm** [sparklemotion/nokogiri#670]
# Nokogiri (1.5.2)

```

---
warnings: []
nokogiri: 1.5.2
ruby:
  version: 1.9.2
  platform: i686-linux
  description: ruby 1.9.2p180 (2011-02-18 revision 30909) [i686-linux]
  engine: ruby
libxml:
  binding: extension
  compiled: 2.7.8
  loaded: 2.7.8
```

SO: Ubuntu 11.10

Code:

require 'rubygems'
require 'nokogiri'

puts $1
puts $2
origin = $1
# doc = Nokogiri::HTML(origin)

Error:

xxxxxxxxx@xxxxxxxxxx:/media/data/home/xxxxxxxx/xxxxxxxx/xxxxxxxxx$ ./psp_html_converter 01.html bla
/home/xxxxxxxx/.rvm/gems/ruby-1.9.2-p180/gems/nokogiri-1.5.2/lib/nokogiri/nokogiri.so: [BUG] Segmentation fault
ruby 1.8.7 (2011-06-30 patchlevel 352) [i686-linux]

Abortado

I'm using RVM and have Ruby 1.9.2. I don't really understand why it says in the last line "ruby 1.8.7". It is probable related with the error right?
