### ISSUE TITLE
Disappearing &quot; in XML

### ISSUE THREAD

**Issue by rhulse** [sparklemotion/nokogiri#732]
I am reading in an XML file and find that &quot; is being stripped.

Reading the file in:

```
doc = File.open(file_path) do |file|
  Nokogiri::XML( file )
end
```

and then outputting:

```
puts doc
```

shows that the quotes are gone.

There is an XML tag that contains some (clean) html:

<tag>

<p>\&quot;This is the text.\&quot;</p>

</tag>

This is happening on my Mac and in production.

Mac:

$nokogiri -v
  Nokogiri (1.5.5)
    --- 
    warnings: []

```
ruby: 
  engine: mri
  version: 1.8.7
  description: ruby 1.8.7 (2011-06-30 patchlevel 352) [i686-darwin11.2.0]
  platform: i686-darwin11.2.0
libxml: 
  loaded: 2.7.3
  binding: extension
  compiled: 2.7.3
nokogiri: 1.5.5
```

Production:

$ nokogiri -v
    Nokogiri (1.5.5)
    --- 
    warnings: []

```
ruby: 
  engine: mri
  version: 1.8.7
  description: ruby 1.8.7 (2010-08-16 patchlevel 302) [x86_64-linux]
  platform: x86_64-linux
libxml: 
  loaded: 2.7.8
  binding: extension
  compiled: 2.7.8
nokogiri: 1.5.5
```
