### ISSUE TITLE
Parsing text nodes bigger than libxml2's XML_MAX_TEXT_LENGTH cause truncation/crashes

### ISSUE THREAD

**Issue by owen** [sparklemotion/nokogiri#740]
https://groups.google.com/forum/?fromgroups#!topic/nokogiri-talk/xKkfrdcf1oU

libxml2 defines XML_MAX_TEXT_LENGTH as ~10 MB. Attempting to parse an XML file with a text node larger than 10MB causes odd behavior:
- on Linux / libxml2 2.7.6, the node is truncated to fit in XML_MAX_TEXT_LENGTH and "error: xmlSAX2Characters: huge text node: out of memory" is displayed.
- on OS X / libxml2 2.7.3 (system default) Ruby segfaults
- on OS X / libxml2 2.8.0 (homebrew), the node is truncated as on Linux.

Expected behavior: I'd expect a Ruby exception to be thrown - as it stands I can't detect & handle truncation.

The nokogiri-talk link above contains the OS X backtrace and the XML file used to reproduce this issue.

**Comment by matisoffn** [comment]
+1

**Comment by knightwupz** [comment]
+1, how to solve this?

**Comment by flavorjones** [comment]
All, I'll look into this as part of a 1.8.0 release. If it slips, I'll update this ticket.

**Comment by flavorjones** [comment]
# modern libxml2 versions

This does not appear to be an issue with libxml 2.9.x. For a file that's 14M in size:

```
> Nokogiri::XML.parse(File.open("large.xml")).root.children.first.text.length
 => 9999894 
> puts Nokogiri::XML.parse(File.open("large.xml")).errors
xmlSAX2Characters: huge text node
Extra content at the end of the document
```

but notice that the `HUGE` config option allows us to parse the whole thing:

```
> Nokogiri::XML.parse(File.open("large.xml")) {|c| c.huge}.root.children.first.text.length
 => 14065665
> puts Nokogiri::XML.parse(File.open("large.xml")) {|c| c.huge}.errors
 => nil 
```

# older libxml2 versions

The problem originally reported was with much older versions of libxml2; e.g. 2.7.3.

Compiling Nokogiri v1.7.0.1 against libxml 2.7.3:

```
# Nokogiri (1.7.0.1)
    ---
    warnings: []
    nokogiri: 1.7.0.1
    ruby:
      version: 2.4.0
      platform: x86_64-linux
      description: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/flavorjones/code/oss/nokogiri/ports/x86_64-pc-linux-gnu/libxml2/2.7.3"
      libxslt_path: "/home/flavorjones/code/oss/nokogiri/ports/x86_64-pc-linux-gnu/libxslt/1.1.20"
      libxml2_patches: []
      libxslt_patches: []
      compiled: 2.7.3
      loaded: 2.7.3
```

results in a segfault when parsing a large file; but the segfault can be avoided by setting the `HUGE` option (as above).

# conclusion

Unfortunately, there's nothing I can think of to prevent old, buggy versions of libxml2 from crashing in this case; the bug is completely internal to libxml2.

As a workaround, consider using the `HUGE` option; or consider using the vendored version of libxml2; or consider upgrading your system's libxml2 version.

Apologies it took so long to close this out.
