### ISSUE TITLE
Nokogiri and libxml not playing with Rails on Mountain Lion?

### ISSUE THREAD

**Issue by AstonJ** [sparklemotion/nokogiri#742]
I've installed Nokogiri, and everything works fine in irb, however, in the Rails console (or when running any Rails command) I get:

```
WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.7.8
```

nokogiri -v shows:

```
# Nokogiri (1.5.5)
    ---
    warnings: []
    nokogiri: 1.5.5
    ruby:
      version: 1.9.3
      platform: x86_64-darwin12.0.0
      description: ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin12.0.0]
      engine: ruby
    libxml:
      binding: extension
      compiled: 2.8.0
      loaded: 2.8.0
```

I installed Nokogiri with:

```
sudo gem install nokogiri -- --with-xml2-include=/usr/local/Cellar/libxml2/2.8.0/include/libxml2 --with-xml2-lib=/usr/local/Cellar/libxml2/2.8.0/lib --with-xslt-dir=/usr/local/Cellar/libxslt/1.1.26 --with-iconv-include=/usr/local/Cellar/libiconv/1.13.1/include --with-iconv-lib=/usr/local/Cellar/libiconv/1.13.1/lib
```

As libxml2 with brew now installs 2.8.0 (still showing 2.7.8 in the instructions on the Nokogiri site - which is what I followed first).

Is this is a bug? Or have I messed up the install somehow? (Thanks in advance for any help.)
