### ISSUE TITLE
Error trying to replace top-level text node in DocumentFragment

### ISSUE THREAD

**Issue by senotrusov** [sparklemotion/nokogiri#775]
The code:

``` ruby
html = "foo"
doc = Nokogiri::HTML::DocumentFragment.parse(html)
doc.children[0].replace "bar"
```

Gives us error:

```
RuntimeError: error parsing fragment (1)
  from nokogiri-1.5.5/lib/nokogiri/xml/node.rb:532:in `in_context'
  from nokogiri-1.5.5/lib/nokogiri/xml/node.rb:532:in `parse'
  from nokogiri-1.5.5/lib/nokogiri/html/document_fragment.rb:22:in `initialize'
  from nokogiri-1.5.5/lib/nokogiri/xml/node.rb:508:in `new'
  from nokogiri-1.5.5/lib/nokogiri/xml/node.rb:508:in `fragment'
  from nokogiri-1.5.5/lib/nokogiri/xml/node.rb:925:in `coerce'
  from nokogiri-1.5.5/lib/nokogiri/xml/node.rb:406:in `replace'
```

As I can tell, that error raises from `in_context` function in `xml_node.c`.

Meanwhile, replacing the text nodes which are not in the top level, works as expected:

``` ruby
html = "<div>foo</div>"
doc = Nokogiri::HTML::DocumentFragment.parse(html)

doc.children[0].children[0].replace "bar"
doc.to_html # => "<div>bar</div>"
```

Just reporting, don't feel competent to provide patch to that issue, sorry.

nokogiri -v:

```
warnings: []
nokogiri: 1.5.5
ruby:
  version: 1.9.3
  platform: x86_64-linux
  description: ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
  engine: ruby
libxml:
  binding: extension
  compiled: 2.7.8
  loaded: 2.7.8
```
