### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nokogiri#856]
Reproduced under:

```
# Nokogiri (1.5.6)
    ---
    warnings: []
    nokogiri: 1.5.6
    ruby:
      version: 1.9.3
      platform: x86_64-linux
      description: ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      compiled: 2.8.0
      loaded: 2.8.0
```

Here's the repro script from @armhold:

```
#!/usr/bin/env ruby

require 'nokogiri'

def get_memory_usage
  `ps -o rss= -p #{Process.pid}`.to_i
end

HTML_CONTENT = "This is some html<br/>This is some more html<br/>" * 10

def run_nokogiri
  doc = Nokogiri::HTML.parse(HTML_CONTENT)
  doc.css("br").each { |node| node.replace("\n ")}
  doc.text

  nil
end

i = 0
loop do
  run_nokogiri

  i += 1
  if i % 1000 == 0
    GC.start

    puts "iteration #{i}"
    puts "current memory: #{get_memory_usage}"
  end
end
```
