### ISSUE TITLE
duplicated xmlns tag in v1.5.7

### ISSUE THREAD

**Issue by th1988** [sparklemotion/nokogiri#865]
new nokogiri version 1.5.7 produces following error:

``` ruby
xml.ONIXmessage(:release=>"2.1",:xmlns=>"http://www.editeur.org/onix/2.1/short","xmlns:xsi".to_sym=>"http://www.w3.org/2001/XMLSchema-instance","xsi:schemaLocation".to_sym=>"http://www.editeur.org/onix/2.1/short http://www.editeur.org/onix/2.1/short/ONIX_BookProduct_Release2.1_short.xsd") do
xml.foo "bar"
...
...
end
```

returns

```
<ONIXmessage xmlns="http://www.editeur.org/onix/2.1/short" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" release="2.1" xmlns="http://www.editeur.org/onix/2.1/short" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.editeur.org/onix/2.1/short http://www.editeur.org/onix/2.1/short/ONIX_BookProduct_Release2.1_short.xsd">
```

nokogiri version info:

```
# Nokogiri (1.5.7)
    ---
    warnings: []
    nokogiri: 1.5.7
    ruby:
      version: 2.0.0
      platform: x86_64-linux
      description: ruby 2.0.0p0 (2013-02-24 revision 39474) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      compiled: 2.7.8
      loaded: 2.7.8
```
