### ISSUE TITLE
jruby NPE occurs in NokogiriNamespaceCache.java

### ISSUE THREAD

**Issue by montdidier** [sparklemotion/nokogiri#929]
It looks like I hit this unresolved issue 

https://github.com/sparklemotion/nokogiri/issues/888

However; I have a test case for you. 

NPE occurred when I use rubyXL ( and nokogiri 1.5.9 ) on jruby 1.7.3 (also with jruby 1.7.4)

Reading the attached file works fine with 
nokogiri 1.5.9 on REE 1.8.7 and probably others

The sample script. 

https://gist.github.com/montdidier/5811630

The data file for the script is nokogiri_npe_example_short.xlsx. Sorry it's a uuencoded binary file, but hopefully not too hard to work with. See gist below.

https://gist.github.com/montdidier/5811612

On OSX at least you can copy uuencoded data to pasteboard and in a terminal 

```
pbpaste | uudecode
```

To re-create the data file  

Output of nokogiri -v 

```
Nokogiri (1.5.9)
--- 
warnings: []

nokogiri: 1.5.9
ruby: 
  version: 1.8.7
  platform: java
  description: jruby 1.7.4 (ruby-1.8.7p370) 2013-05-16 2390d3b on Java HotSpot(TM) 64-Bit Server VM 1.6.0_45-b06-451-11M4406 [darwin-x86_64]
  engine: jruby
  jruby: 1.7.4
xerces: Xerces-J 2.9.0
nekohtml: NekoHTML 1.9.12
```
