### ISSUE TITLE
Missleading error message "undefined method `empty?'"

### ISSUE THREAD

**Issue by GreatSUN** [sparklemotion/nokogiri#967]
This error message gets displayed if you try to give Nokogiri::XML another Nokogiri::XML object by accident. 

Examplecode:
        xmlSource = Nokogiri::XML(Nokogiri::XML(IO.read('./test.xml'))

ErrorMsg:
        NoMethodError: undefined method `empty?' for #<Nokogiri::XML::Document:0x2b7c730901f8>
                from /usr/lib64/ruby/gems/1.8/gems/nokogiri-1.4.3.1/lib/nokogiri/xml/document.rb:31:in`parse'
                from /usr/lib64/ruby/gems/1.8/gems/nokogiri-1.4.3.1/lib/nokogiri/xml.rb:33:in `XML'

nokogiri -v output:
        --- 
        warnings: []

```
    ruby: 
      engine: mri
      version: 1.8.7
      platform: x86_64-linux
    libxml: 
      loaded: 2.6.26
      binding: extension
      compiled: 2.6.26
    nokogiri: 1.4.3.1
```

Could you please fix this and give back some error message like "Expected string object" or likewise?
Other option could be to check if it is already an Nokogiri::XML:Document and just return the object though.

Thanks!
